<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Browse_vm.accountDetailsForm.attachment</name>
   <tag></tag>
   <elementGuidId>4c3e9c89-d17f-470d-9b01-e7f818eada8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'file' and @name = 'vm.accountDetailsForm.attachment' and @id = '1651825579431_35']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='1651825579431_35']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.btn.btn-primary.btn-file</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e712abee-b2e0-41e4-96e5-0d93acfc4d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>821c7e7a-8f39-4eb2-b2f3-2f20e99be029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>image</name>
      <type>Main</type>
      <value>vm.accountDetailsForm.attachment</value>
      <webElementGuid>cca529d8-f303-4434-b0f1-a1e912a4ccfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vm.accountDetailsForm.attachment</value>
      <webElementGuid>51690099-a096-49df-a01f-1ca94285aed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>vm.accountDetailsForm.attachment</value>
      <webElementGuid>10117552-ee9c-4b04-9196-cc4a877cc2f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min-file-count</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>49261739-ed05-45c3-934e-1045d90b3317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-showremove</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>87340bff-3f77-49ea-b764-68fe7846415c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-show-cancel</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>58236856-241e-4cb7-b1aa-5bfb85f46af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>resize-max-height</name>
      <type>Main</type>
      <value>70</value>
      <webElementGuid>8532a43d-0ddb-4b60-8ee3-912de4402306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>resize-max-width</name>
      <type>Main</type>
      <value>70</value>
      <webElementGuid>9742cc46-4e64-4073-9736-acfe22a1b043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>resize-quality</name>
      <type>Main</type>
      <value>0.7</value>
      <webElementGuid>2510143f-1526-4d8f-aee4-db4cf507114e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-isolate-scope ng-valid-required</value>
      <webElementGuid>4316b0f9-f7dd-45a5-afa9-a2f5d7f9096f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1651825579431_35</value>
      <webElementGuid>abd4fc50-e25a-4daf-be94-66edc22902b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1651825579431_35&quot;)</value>
      <webElementGuid>a9f6f11d-e8b9-413c-a0ff-8dd855767b5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='1651825579431_35']</value>
      <webElementGuid>67bdccc8-c4fd-44db-b93b-547a5265a951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step1']/div/div/div[2]/div/form/div[12]/div/div/div/div/div[3]/div[2]/div/input</value>
      <webElementGuid>edbf573a-a72d-4c4a-b8cc-c4b1098e2cfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browse …'])[1]/following::input[1]</value>
      <webElementGuid>16744384-4dd9-4d2b-90a4-758d55df94ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove'])[1]/following::input[1]</value>
      <webElementGuid>013bc0f5-36d6-4e12-b78d-43baffe4f7ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account logo is required.'])[1]/preceding::input[1]</value>
      <webElementGuid>891f2fbb-8cbf-4500-a89f-2d6555a6f183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Details'])[1]/preceding::input[1]</value>
      <webElementGuid>4c39fb3b-aecb-4aec-8fac-125e084eca16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>127915dd-f9fd-4502-a42f-ea13fdf555b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'vm.accountDetailsForm.attachment' and @id = '1651825579431_35']</value>
      <webElementGuid>69403ae2-b1fe-4051-8581-3a597be8cdd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
