<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>navigatorDropdown</name>
   <tag></tag>
   <elementGuidId>83489d93-2dfb-4921-ab4c-694d650c1b14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button#dropdown-menu-align-left</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
