<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RingCentralCommunicationMode</name>
   <tag></tag>
   <elementGuidId>4af855f4-97f9-41a9-a89b-7a8f8506058d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[type='url']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
