<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Load more</name>
   <tag></tag>
   <elementGuidId>896a5a63-9338-4593-9082-3712051236c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='loadMore'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-12 > #loadMore</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d721a500-f88d-421a-b0da-aa6f538c40e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loadMore</value>
      <webElementGuid>21f6ffc3-cf04-4967-b711-35268cc679bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>vm.totalComments > vm.totalCommentsList.length</value>
      <webElementGuid>af8b656d-2752-4125-bdc5-3e6e3f69d9a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vm.getLeadComments(vm.selectedlead.id, vm.selectedlead.lcode, true)</value>
      <webElementGuid>5f8ae32a-ab3b-4a65-a3d5-4cac8076651e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loadmore ng-scope</value>
      <webElementGuid>002b1510-5f78-4b38-b477-f8bf1b99cce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Load more</value>
      <webElementGuid>409f137b-a015-411c-ac0b-e1c604523366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mCSB_1_container&quot;)/div[@class=&quot;col-md-12&quot;]/button[@id=&quot;loadMore&quot;]</value>
      <webElementGuid>2ec1a0fa-a6f4-4e69-acd6-e961b6b46ac8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='loadMore'])[2]</value>
      <webElementGuid>748a7add-37ce-46e0-b2e3-1827c72b9a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mCSB_1_container']/div[4]/button</value>
      <webElementGuid>829c6611-cf95-4654-95d1-f5ee2b4e72e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hired'])[8]/following::button[1]</value>
      <webElementGuid>6960736a-2477-4682-93ea-be57f18cb7b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hired'])[7]/following::button[1]</value>
      <webElementGuid>96f0685f-f1b5-4033-a53d-2787e6e9bfd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bot'])[1]/preceding::button[1]</value>
      <webElementGuid>ca186826-a099-4b05-9368-8066e40c5411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule Date'])[1]/preceding::button[1]</value>
      <webElementGuid>39d51618-5b8f-4949-9b80-861ee2dded41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Load more']/parent::*</value>
      <webElementGuid>2438689d-146e-45b5-8d5b-aca7307d6236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>aae71ccc-9018-4226-8aae-e90bda2d3abe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'loadMore' and (text() = '  Load more' or . = '  Load more')]</value>
      <webElementGuid>e3ec0237-ebbe-4830-81b8-2abebcba6cb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
