<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Hired</name>
   <tag></tag>
   <elementGuidId>c4445c0b-a7a3-490a-b07a-e7fd173e2c23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.lead-details-status > span.ng-scope</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f793a371-f89a-4f94-ad07-f19167db0d2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-translate</name>
      <type>Main</type>
      <value>LEAD_STATUS.HIRED</value>
      <webElementGuid>0f8ba0c7-8bf8-4caf-a57c-a93f53827945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-scope</value>
      <webElementGuid>904a93cf-7b39-4c7f-bd20-b9c7f0a73592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hired</value>
      <webElementGuid>d173d53e-8765-4af6-b1d7-97b93431a0cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-append-to-body&quot;)/span[@class=&quot;lead-details-status&quot;]/span[@class=&quot;ng-scope&quot;]</value>
      <webElementGuid>cec75a88-4373-45c7-bc5f-28665412b397</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='btn-append-to-body']/span/span</value>
      <webElementGuid>0cc96e01-0379-41d8-ba2f-ad7a3dbbe471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current Status'])[1]/following::span[4]</value>
      <webElementGuid>4242a1c3-29c1-4364-9f8d-e381bd490e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Modified By'])[1]/following::span[4]</value>
      <webElementGuid>953ea237-bafd-4b4e-bf14-da7cb77ea474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shortlisted'])[1]/preceding::span[2]</value>
      <webElementGuid>2c13ac6d-719c-49d5-9705-5c6ad56d0b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contacted'])[16]/preceding::span[4]</value>
      <webElementGuid>fdbb4188-64dd-46dd-9075-e1bbcdd94e08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span/span</value>
      <webElementGuid>3d48819b-635d-4adf-89df-37db7a79da58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Hired' or . = 'Hired')]</value>
      <webElementGuid>a974f92d-c088-424b-81da-73031bb44239</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
