<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Contacted</name>
   <tag></tag>
   <elementGuidId>bb634237-59b9-4db3-97ae-5fb90cec8058</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navItem1_4']/table/tbody/tr/td[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>be0b7e2e-5b1c-4606-a4bb-2c168ff7f2fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>12%</value>
      <webElementGuid>c50fedc6-76dc-4a9c-8341-3429cb5bb615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Contacted   </value>
      <webElementGuid>ee6fc094-2994-4bc3-94bc-93f939324c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navItem1_4&quot;)/table[@class=&quot;lead-score-data&quot;]/tbody[1]/tr[1]/td[7]</value>
      <webElementGuid>f6cb92be-29c9-493f-b329-756c8d4cd432</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navItem1_4']/table/tbody/tr/td[7]</value>
      <webElementGuid>afd13ef6-3f69-4bba-9018-86b491a6bbc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bristol Center'])[1]/following::td[1]</value>
      <webElementGuid>45f0b1d7-5cd8-4d75-9ee2-ee8eadfc1ebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hidumba Hidumba'])[1]/following::td[3]</value>
      <webElementGuid>5cbce27f-96d7-44a1-88e4-7938687c8bbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duplicate_Software Engineer_6454_Spanish'])[2]/preceding::td[1]</value>
      <webElementGuid>5d444233-17f7-412b-b602-158fcfddbca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/table/tbody/tr/td[7]</value>
      <webElementGuid>8bf8d27f-2f60-4028-99e1-bef323ab6b07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = ' Contacted   ' or . = ' Contacted   ')]</value>
      <webElementGuid>78867f21-aa1d-4f6a-9506-bc21f923a2f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
