<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Hired</name>
   <tag></tag>
   <elementGuidId>ce86db0f-d8c1-4936-b32d-cd7142b488e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navItem1_0']/table/tbody/tr/td[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>6d4acd20-9c1f-4aee-a212-66684eb18a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>12%</value>
      <webElementGuid>a7fdfb60-f23a-4d05-a479-50e08a8bd539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Hired   </value>
      <webElementGuid>a5705403-c417-4396-a389-ee59f70346c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navItem1_0&quot;)/table[@class=&quot;lead-score-data&quot;]/tbody[1]/tr[1]/td[7]</value>
      <webElementGuid>d895ad3f-646a-44c3-be61-0c53112cb008</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navItem1_0']/table/tbody/tr/td[7]</value>
      <webElementGuid>e39098c4-a799-48a3-97d7-416303b73587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Khan Khan'])[1]/following::td[3]</value>
      <webElementGuid>267801a8-9f5d-42cd-8a3f-adcc3633b558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='_en'])[1]/following::td[7]</value>
      <webElementGuid>a4e5927a-557b-4b2b-a1ef-d1e28a11a257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Software Engineer_Perl Developer'])[2]/preceding::td[1]</value>
      <webElementGuid>13d79163-b98d-43b6-940d-790a726c31da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]</value>
      <webElementGuid>0e89c8fc-0519-420f-8367-e08394d606c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = ' Hired   ' or . = ' Hired   ')]</value>
      <webElementGuid>df557128-ce0f-4204-a8d0-e85cef312782</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
