<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Software_Testing_geuT</name>
   <tag></tag>
   <elementGuidId>3fb41963-cfcb-4092-8044-9e271f2858d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span[class=move-icon-dec]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='contentMainDiv']/div[3]/div/div[3]/div/div[2]/div/div/table/tbody/tr/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>1898db77-876b-4f72-a722-306b66c97571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Software_Testing_geuT  </value>
      <webElementGuid>3c9a59b0-1273-4255-8217-d8ab60e6e429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentMainDiv&quot;)/div[@class=&quot;container-main ng-scope&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 dashboard-main&quot;]/div[@class=&quot;panel border-panel&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;table-responsive campaign-table dashboard-table dashboard-table-small&quot;]/table[@class=&quot;table table-striped table-hover draggable-table campaign-table min-table ng-scope&quot;]/tbody[1]/tr[@class=&quot;ng-scope&quot;]/td[3]</value>
      <webElementGuid>bfabd539-9756-40f5-a745-8903ba8a1c24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentMainDiv']/div[3]/div/div[3]/div/div[2]/div/div/table/tbody/tr/td[3]</value>
      <webElementGuid>e8131f3c-3242-4706-a61b-7460a59fbabc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JOB_3938'])[1]/following::td[1]</value>
      <webElementGuid>835f1729-db4d-4bbb-bd63-b1b9e76104ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bot'])[1]/following::td[3]</value>
      <webElementGuid>85dc1b79-646d-4fb0-87bd-4b8be6f0f994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Boost'])[1]/preceding::td[7]</value>
      <webElementGuid>a62e4f28-3870-46bc-bce5-7388b153e81e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]</value>
      <webElementGuid>fb93adac-31d1-44dd-b8f5-70dc4457ce23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = ' Software_Testing_geuT  ' or . = ' Software_Testing_geuT  ')]</value>
      <webElementGuid>50fcfc15-514d-49cf-909e-6523d8f92648</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
