<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Interview booked at  June 27th 2022 fro_9e7afc</name>
   <tag></tag>
   <elementGuidId>a8b03803-fb85-4a42-a9bf-596966ed3dcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[3]/div/div[2]/div/div/form/div/div[2]/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.bg-grey2.border.mb-3.p-3.rounded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>eeac3d35-4b47-4e27-bcc3-33ef585d0712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-grey2 border mb-3 p-3 rounded</value>
      <webElementGuid>beccd92f-8d6d-4c5a-be48-4ac12fc2449c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Interview booked at  June 27th 2022 from 12:00:00PM to 12:30:00PM</value>
      <webElementGuid>c8616c2d-0d56-4cb0-be1c-f5396791248f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;main-panel App&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;page-inner&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-8&quot;]/form[1]/div[@class=&quot;card tabs-container&quot;]/div[@class=&quot;card-body tabs-content&quot;]/div[@class=&quot;showTab&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;bg-grey2 border mb-3 p-3 rounded&quot;]</value>
      <webElementGuid>95050ed6-7f30-4878-8c39-402d7ffe9365</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[3]/div/div[2]/div/div/form/div/div[2]/div/div/div/div</value>
      <webElementGuid>0e706f47-882d-413f-ac07-8ed2338b75b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In - HR Evaluation'])[1]/following::div[10]</value>
      <webElementGuid>c6830db4-dceb-4986-a876-2f5ad2e7d4f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atish Sharma'])[2]/preceding::div[1]</value>
      <webElementGuid>4bfeaff3-fc6a-4d07-b071-9eda3e6b8f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Interview booked at']/parent::*</value>
      <webElementGuid>3b828ade-2982-4b25-9c89-5c2a3770cd88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/div/div/div</value>
      <webElementGuid>b981d7a5-5ec0-467d-bf86-f3ef6acf934e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Interview booked at  June 27th 2022 from 12:00:00PM to 12:30:00PM' or . = 'Interview booked at  June 27th 2022 from 12:00:00PM to 12:30:00PM')]</value>
      <webElementGuid>e91723a4-aa74-4f8a-9643-3b2491421c44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
