<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Atish Sharma</name>
   <tag></tag>
   <elementGuidId>9d6facd5-0f63-4605-bde2-ac0bb63367c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/nav/div/ul/li/a/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h4.m-0.ml-3.text-white</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>294eb739-9b13-4cd8-94ad-6e9847aaf0ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-0 ml-3 text-white</value>
      <webElementGuid>b90e21fc-b188-4738-94fe-b942ac55da53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Atish Sharma</value>
      <webElementGuid>59686e80-5217-4934-9688-cd11040ceb9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;main-header&quot;]/nav[@class=&quot;navbar navbar-header navbar-expand-lg&quot;]/div[@class=&quot;container-fluid&quot;]/ul[@class=&quot;navbar-nav topbar-nav ml-auto align-items-center&quot;]/li[@class=&quot;nav-item dropdown hidden-caret&quot;]/a[@class=&quot;dropdown-toggle profile-pic align-items-center d-flex&quot;]/h4[@class=&quot;m-0 ml-3 text-white&quot;]</value>
      <webElementGuid>01a647be-e849-4df0-910a-eda8b4c05a65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/nav/div/ul/li/a/h4</value>
      <webElementGuid>81b5b160-6c7a-4aad-ab96-aefd76a49026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atish Sharma'])[1]/preceding::h4[1]</value>
      <webElementGuid>3441975b-2b2d-4f1b-b1ea-b71c6feb89f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/preceding::h4[2]</value>
      <webElementGuid>7e21d090-b4e3-4677-bc32-e5a187ddc444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Atish Sharma']/parent::*</value>
      <webElementGuid>634d6651-f221-44ce-bde8-14caface6d4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>55afd49b-ff86-4646-a58d-9e1d036902eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = ' Atish Sharma' or . = ' Atish Sharma')]</value>
      <webElementGuid>cce1d22a-2e45-43a5-a345-a293373b5a3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
