<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AllNot ScheduledCalendar SharedInter_ca03d5</name>
   <tag></tag>
   <elementGuidId>eec51f76-870c-4cae-8caf-e5b5ede74a8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[3]/div/div/div/div[2]/div/div/div/div/div[3]/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select.form-control</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a27f6a3a-1aa6-4ecf-8285-54f025bd38b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c4f86c19-a6d5-4159-a727-4fb5e996e668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AllNot ScheduledCalendar SharedInterview ScheduledHiredNot Selected</value>
      <webElementGuid>f4bd401d-6da0-4867-bbc4-ee2e72249c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;main-panel App&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;page-inner&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-9 d-flex justify-content-end align-items-start&quot;]/div[@class=&quot;filter-dropdown&quot;]/div[@class=&quot;card filter-dropdown-menu p-3 show&quot;]/div[@class=&quot;candidate-filter-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;form-group&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>1f785dca-5ead-4246-9aff-1e2745e2f131</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[3]/div/div/div/div[2]/div/div/div/div/div[3]/div/select</value>
      <webElementGuid>a81ba1c9-05fd-48b0-9085-ed5e91df48b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Status'])[1]/following::select[1]</value>
      <webElementGuid>37d2594d-8ced-4448-bdc1-fbdad48087d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Job, Panelist or Candidate'])[1]/following::select[1]</value>
      <webElementGuid>f12321f2-25db-4cb8-a23d-9e3035a89913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/preceding::select[1]</value>
      <webElementGuid>3f8df137-f0f3-4cb8-bb4c-89244cb4b33b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[1]/preceding::select[1]</value>
      <webElementGuid>d94f527e-3e49-42ff-b31d-7cb1bed333e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>e7a350cf-9514-4291-b714-59d5af5d561c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'AllNot ScheduledCalendar SharedInterview ScheduledHiredNot Selected' or . = 'AllNot ScheduledCalendar SharedInterview ScheduledHiredNot Selected')]</value>
      <webElementGuid>1e233426-5bb9-44c5-8eca-860d8ea37143</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
