<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next</name>
   <tag></tag>
   <elementGuidId>d63e4b0e-a65c-4a41-90b3-f9c42b6b3dad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='myCarousel']/div/div/div[2]/div[2]/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn-next-ques.ng-scope</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>47488179-6005-4e9a-9e13-76e1a7d78615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>($index !=(vm.selectedPage.content.fields.fields.length-1))&amp;&amp;!!vm.selectedPage.content.style.timer &amp;&amp; !vm.selectedPage.content.style.timer.enabled &amp;&amp; (field.type != 'textarea')</value>
      <webElementGuid>0af225b7-bf52-47df-8021-4945e5b3b08d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slide</name>
      <type>Main</type>
      <value>next</value>
      <webElementGuid>e4365997-aabc-4f9d-910b-bfc9d1264fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#myCarousel</value>
      <webElementGuid>62a2ffcd-010a-4a37-b0f9-bed64b9b321b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vm.questionnariesNavigation('next')</value>
      <webElementGuid>8d3e00f8-4b07-421b-8800-62a270e37898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-next-ques ng-scope</value>
      <webElementGuid>36971478-88ac-456d-bcb7-7d4c799a5f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>!field.isAnswered</value>
      <webElementGuid>245ce16d-0538-493d-8d9b-d6ae6c5342d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next </value>
      <webElementGuid>d02fb993-913f-4170-b059-315f8ac78084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myCarousel&quot;)/div[@class=&quot;carousel-inner ng-scope&quot;]/div[@class=&quot;item ng-scope active&quot;]/div[2]/div[@class=&quot;survey-footer-bar&quot;]/button[@class=&quot;btn-next-ques ng-scope&quot;]</value>
      <webElementGuid>b8fb6cf2-0b92-4439-9ac3-68d1d7dc2b16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myCarousel']/div/div/div[2]/div[2]/button[2]</value>
      <webElementGuid>d4bfaf87-9f24-41df-8968-d6ddba09ad32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/following::button[2]</value>
      <webElementGuid>bcf438c3-6367-41e9-a9f2-b13d3cd3d903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do you want to connect again'])[1]/preceding::button[1]</value>
      <webElementGuid>123759b7-46ec-4b73-8861-20c1a9cf7e7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[2]/preceding::button[1]</value>
      <webElementGuid>3148a83d-efa6-43b3-a147-d6c67477ca5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next']/parent::*</value>
      <webElementGuid>2354f6d8-87ee-4987-9ac4-fbdb8fbb55af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>6209d93c-d685-4e42-a38e-1a9d5a0304a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Next ' or . = 'Next ')]</value>
      <webElementGuid>4e475670-500c-46bb-b1d0-06a10f1eb247</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
