<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Done</name>
   <tag></tag>
   <elementGuidId>d0b2e449-a8dc-49c8-b3ad-f53ad13b9160</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='myCarousel']/div/div[2]/div[2]/div[2]/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d111137e-4192-41c3-9536-4e070a4ababa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>($index ==(vm.selectedPage.content.fields.fields.length-1)) &amp;&amp; !!vm.selectedPage.content.style.timer &amp;&amp; !vm.selectedPage.content.style.timer.enabled &amp;&amp; (field.type != 'textarea')</value>
      <webElementGuid>f766b385-359d-4f9e-8bf0-f432adf4805d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slide</name>
      <type>Main</type>
      <value>next</value>
      <webElementGuid>0a8ec212-edc0-4847-9d32-da319937bdf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#myCarousel</value>
      <webElementGuid>6a500168-ed86-4da8-917f-0d70802a591d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vm.questionnariesNavigation('done')</value>
      <webElementGuid>1f6032b2-0f08-4b22-a49e-286333f82c3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-next-ques ng-scope</value>
      <webElementGuid>859080ca-2350-4404-85c7-328453567fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>!field.isAnswered</value>
      <webElementGuid>01c23ccc-5fd1-4735-9ac2-136bb0c1673c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Done </value>
      <webElementGuid>e9391fb8-a2ba-47bd-b37c-67c67906ae34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myCarousel&quot;)/div[@class=&quot;carousel-inner ng-scope&quot;]/div[@class=&quot;item ng-scope active&quot;]/div[2]/div[@class=&quot;survey-footer-bar&quot;]/button[@class=&quot;btn-next-ques ng-scope&quot;]</value>
      <webElementGuid>eaf2ed91-10c0-479b-a127-29ae4004f186</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myCarousel']/div/div[2]/div[2]/div[2]/button[2]</value>
      <webElementGuid>4f90759a-688f-4cb8-9b35-a3671b5c0a30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[2]/following::button[2]</value>
      <webElementGuid>7e228e3c-739f-4922-8564-a3177d07f254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thank you for completing this form! We look forward to connecting with you soon!'])[1]/preceding::button[1]</value>
      <webElementGuid>6baf4f8c-5090-40da-b440-f0b603fb599c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/preceding::button[1]</value>
      <webElementGuid>5c16d59e-0ae2-4c4a-997c-4e1022622855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Done']/parent::*</value>
      <webElementGuid>661dd525-dd80-435a-a1d2-1ba63f4f1f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/button[2]</value>
      <webElementGuid>92d2471d-6138-4be5-a052-c2f53c3fd70c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Done ' or . = 'Done ')]</value>
      <webElementGuid>753467bf-f890-4eb2-b2ba-939589feed4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
