<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Do you want to connect again_Do you w_9cc71c</name>
   <tag></tag>
   <elementGuidId>7c560239-7c69-46e6-9a02-8546878ea30e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Do you want to connect again']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Do you want to connect again&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ccb282b-39c6-4fd8-a8e2-cabbef567bf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e01a4fea-94ef-4631-a0bd-955990ddcd4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>vm.isExternalMicrosite</value>
      <webElementGuid>111a9c82-45c8-4100-877c-2873848bafe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styled ng-scope ng-isolate-scope</value>
      <webElementGuid>c89b6b66-81a3-41fb-8ad6-83c2d9d3a89d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Do you want to connect again</value>
      <webElementGuid>ab51d8d1-1fa2-4e40-8dab-bae261750c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-value</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>961ac829-276b-4b7f-953f-c4e698d5c90e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-checked</name>
      <type>Main</type>
      <value>option.value==field.answer</value>
      <webElementGuid>794a0b0b-ee63-452e-a00c-ab5bf94c01e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vm.saveSurveyResponse(field._id,field.displayName, option.value, field.options,vm.selectedPage.content.fields.fields, false, vm.selectedPage.content.style.timer.responseTime)</value>
      <webElementGuid>6e317109-52bf-4d38-b212-bbfef4956a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-iframe</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0409c077-316a-4ef1-a42c-cd1bbb6e8c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stopanimation</name>
      <type>Main</type>
      <value>vm.selectedPage.content.style.timer</value>
      <webElementGuid>4b62633e-19a3-41d3-97eb-9ba5d57d6b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myCarousel&quot;)/div[@class=&quot;carousel-inner ng-scope&quot;]/div[@class=&quot;item ng-scope active&quot;]/div[2]/div[@class=&quot;text-center checkRadioContainer&quot;]/div[@class=&quot;answer-label ng-scope&quot;]/input[@class=&quot;styled ng-scope ng-isolate-scope&quot;]</value>
      <webElementGuid>e1826a27-ed63-4661-8350-5b7ea4464449</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Do you want to connect again']</value>
      <webElementGuid>ea39000d-c622-4f88-8b48-a3c1d28bfd89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myCarousel']/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>0eca1937-439d-4a1b-ae18-262272a8551d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/input</value>
      <webElementGuid>8b691654-a4ae-4c91-a468-8ab84c05ebdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'Do you want to connect again']</value>
      <webElementGuid>a8ce030b-6418-49f7-be81-f989bbede63b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
