<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Do you like the hiring process_Do you_e48fde</name>
   <tag></tag>
   <elementGuidId>fb846760-0200-41ce-b540-70cd6e1c2ec9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Do you like the hiring process']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Do you like the hiring process&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89f8f3ab-05a7-4bc0-95a2-360d5824e0a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>7084ead6-2763-49c4-8f4a-c50af09e039c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>vm.isExternalMicrosite</value>
      <webElementGuid>10ba3d99-b6d3-4f27-958c-a664b62eebe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styled ng-scope ng-isolate-scope</value>
      <webElementGuid>5f2f136f-7d84-4e5a-8fa1-3ed95449b357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Do you like the hiring process</value>
      <webElementGuid>dfc9f64f-b187-494f-b01f-c11f2ee42ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-value</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>36dc19af-4fe8-4e94-ab33-fbf8b1f8465e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-checked</name>
      <type>Main</type>
      <value>option.value==field.answer</value>
      <webElementGuid>6b9047b3-f0aa-42b8-ad96-450614921512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vm.saveSurveyResponse(field._id,field.displayName, option.value, field.options,vm.selectedPage.content.fields.fields, false, vm.selectedPage.content.style.timer.responseTime)</value>
      <webElementGuid>23a08f25-c345-40d0-8dd1-ddb7fb0293d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-iframe</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d1ac5c53-c3fd-485f-b2af-cb477e390ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stopanimation</name>
      <type>Main</type>
      <value>vm.selectedPage.content.style.timer</value>
      <webElementGuid>941ed3b2-d356-43d1-8baf-85d9b15bf71a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myCarousel&quot;)/div[@class=&quot;carousel-inner ng-scope&quot;]/div[@class=&quot;item ng-scope active&quot;]/div[2]/div[@class=&quot;text-center checkRadioContainer&quot;]/div[@class=&quot;answer-label ng-scope&quot;]/input[@class=&quot;styled ng-scope ng-isolate-scope&quot;]</value>
      <webElementGuid>e4988bd6-3c26-4ff9-8ea0-d66a3634ddc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Do you like the hiring process']</value>
      <webElementGuid>89985bb9-9196-40f1-8ec0-3ea0f1437216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myCarousel']/div/div/div[2]/div/div/input</value>
      <webElementGuid>f204b8d3-d7e5-4621-b4f1-5e368bfe87b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>386c2a86-eab9-4376-ab6b-637670ce3351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'Do you like the hiring process']</value>
      <webElementGuid>79770e87-25d2-4995-a520-af2acc94f0f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
