<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sendButtonLocator</name>
   <tag></tag>
   <elementGuidId>c67ed8cb-f972-4f44-8533-470ac18756b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chats']/div/div[3]/div[2]/div/button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-yellow.ng-scope > i.fas.fa-paper-plane</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>63e026d5-f5ed-41c0-b617-2c765b5aeeb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-paper-plane</value>
      <webElementGuid>224df151-5c5c-4d42-acc5-049183250ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d4c425db-4e1f-4d4d-a94b-1b93c92c467a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chats&quot;)/div[@class=&quot;chat&quot;]/div[@class=&quot;slimScrollDiv&quot;]/div[2]/div[@class=&quot;chat-message clearfix ng-scope&quot;]/button[@class=&quot;btn btn-yellow ng-scope&quot;]/i[@class=&quot;fas fa-paper-plane&quot;]</value>
      <webElementGuid>44f494f8-c842-4454-afc5-55326b59f3c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chats']/div/div[3]/div[2]/div/button/i</value>
      <webElementGuid>6d063166-d007-496c-bb7f-93588fc4c855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/button/i</value>
      <webElementGuid>2cd052fc-1673-4464-b9d2-a5a7ed3e4e3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
