<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SMS</name>
   <tag></tag>
   <elementGuidId>2366f661-e59d-4282-803d-85d348462437</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='altra']/ul/li[2]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.tab-item > span.ng-scope</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d34aa90e-ef94-4d08-bba3-b83932c9a13b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-if</name>
      <type>Main</type>
      <value>vm.selectedAccount.enableSmsCommunication &amp;&amp; vm.selectedlead.campaignSmsEnabled</value>
      <webElementGuid>441a6085-bf73-4a5c-ad4a-77dd7085479d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-scope</value>
      <webElementGuid>4b366b94-e310-47b8-99b8-f62dcb9f2585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SMS</value>
      <webElementGuid>d09a3dec-9402-4e9a-bf0a-884e620f7fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;altra&quot;)/ul[@class=&quot;nav nav-tabs&quot;]/li[2]/a[@class=&quot;tab-item&quot;]/span[@class=&quot;ng-scope&quot;]</value>
      <webElementGuid>8d2491cc-f207-47a6-ac4d-ba3011cc42f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='altra']/ul/li[2]/a/span</value>
      <webElementGuid>72c20671-ab52-4d06-8076-8ca709e527cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perl Developer'])[20]/following::span[4]</value>
      <webElementGuid>0440a75f-5d29-47fd-b13f-0f3c372dbaa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SMS']/parent::*</value>
      <webElementGuid>eaaea2b0-23f8-409b-a2e3-38b17457afe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li[2]/a/span</value>
      <webElementGuid>420d940c-53c4-447f-889f-a97c4061d4e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'SMS' or . = 'SMS')]</value>
      <webElementGuid>3579ae8e-63a2-404f-b655-1f1b95c2282a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
