<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Username  The email address is invalid _df9b17</name>
   <tag></tag>
   <elementGuidId>54f3b7a8-bfaf-4884-8c76-fdf569f216ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='contentMainDiv']/section/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.login-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>45f9bfde-87eb-4a1a-92bf-a0f7d51357cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-container</value>
      <webElementGuid>23cfff74-952d-4db1-b085-ad445f873b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>            Username  The email address is invalid Username is required.   Password   Password is required.   Forgot Password? Reset   Login    © 2022  Mobile Talent  - All Rights Reserved. Version 5.13     </value>
      <webElementGuid>054f0b04-a2ca-4c5f-acaa-c83d882592ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentMainDiv&quot;)/section[@class=&quot;container login-form ng-scope&quot;]/div[@class=&quot;login-container&quot;]</value>
      <webElementGuid>767f982d-508b-45c5-a332-3c67b96b41b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentMainDiv']/section/div</value>
      <webElementGuid>88f96765-6aca-4aad-b06f-407fcb3843ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div</value>
      <webElementGuid>d6d0f8b1-0b50-4d58-ab85-2c81f68eaa30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '            Username  The email address is invalid Username is required.   Password   Password is required.   Forgot Password? Reset   Login    © 2022  Mobile Talent  - All Rights Reserved. Version 5.13     ' or . = '            Username  The email address is invalid Username is required.   Password   Password is required.   Forgot Password? Reset   Login    © 2022  Mobile Talent  - All Rights Reserved. Version 5.13     ')]</value>
      <webElementGuid>f93496bc-54bd-45b8-82e7-f445ee0cd46d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
