<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Thank you for completing the pre-qualif_a215ac</name>
   <tag></tag>
   <elementGuidId>d428b00a-5149-48f2-90c2-86d0c0cd8725</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='taTextElement7270844986416516']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#taTextElement7270844986416516</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d527ea24-03b6-45ee-9368-0daa7a5db5b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>taTextElement7270844986416516</value>
      <webElementGuid>8b672bbe-8cd2-4553-965d-51dc187983af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6816da8d-4784-4606-b730-4d2a5385a401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ta-bind</name>
      <type>Main</type>
      <value>ta-bind</value>
      <webElementGuid>c1ff0af8-ddef-44f4-82cb-c776df89ca81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>html</value>
      <webElementGuid>48360b45-9a31-4c3b-9351-e59747110098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Add Job description or copy and paste from a similar job posting</value>
      <webElementGuid>afa7493b-96ab-424d-9751-f95a7b49790d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-valid ta-bind ng-dirty ng-valid-parse</value>
      <webElementGuid>51e96ff0-ec48-4a58-956a-0054dbc3f8e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thank you for completing the pre-qualification form. We will be in touch soon with next steps.Thank you for completing the pre-qualification form. We will be in touch soon with next steps.Thank you for completing the pre-qualification form. We will be in touch soon with next steps.Thank you for completing the pre-qualification form. We will be in touch soon with next steps.Thank you for completing the pre-qualification form. We will be in touch soon with next steps.Thank you for completing the pre-qualification form. We will be in touch soon with next steps.Thank you for completing the pre-qualification form. We will be in touch soon with next steps.</value>
      <webElementGuid>29c8fce9-b991-4b88-bf19-8317fdaac957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;taTextElement7270844986416516&quot;)</value>
      <webElementGuid>c379d31e-6ac4-4e1e-b6d2-6c66b27c9f2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='taTextElement7270844986416516']</value>
      <webElementGuid>03d37ddd-5d95-403a-951d-8a526d328ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step1']/div/div/div/div[10]/div/text-angular/div[2]/div[3]</value>
      <webElementGuid>e572adac-32f2-4fb0-b53f-2782845b9861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter minimum 200 characters.'])[1]/preceding::div[1]</value>
      <webElementGuid>611e3e1e-dc44-4525-b1d3-f6c1921da119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter job description.'])[1]/preceding::div[1]</value>
      <webElementGuid>4d447e0c-0cf8-4ffb-aa8f-dbb41b855e85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]</value>
      <webElementGuid>d60b031f-5da6-46b8-ad00-e3f0df0831ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'taTextElement7270844986416516' and @placeholder = 'Add Job description or copy and paste from a similar job posting' and (text() = 'Thank you for completing the pre-qualification form. We will be in touch soon with next steps.Thank you for completing the pre-qualification form. We will be in touch soon with next steps.Thank you for completing the pre-qualification form. We will be in touch soon with next steps.Thank you for completing the pre-qualification form. We will be in touch soon with next steps.Thank you for completing the pre-qualification form. We will be in touch soon with next steps.Thank you for completing the pre-qualification form. We will be in touch soon with next steps.Thank you for completing the pre-qualification form. We will be in touch soon with next steps.' or . = 'Thank you for completing the pre-qualification form. We will be in touch soon with next steps.Thank you for completing the pre-qualification form. We will be in touch soon with next steps.Thank you for completing the pre-qualification form. We will be in touch soon with next steps.Thank you for completing the pre-qualification form. We will be in touch soon with next steps.Thank you for completing the pre-qualification form. We will be in touch soon with next steps.Thank you for completing the pre-qualification form. We will be in touch soon with next steps.Thank you for completing the pre-qualification form. We will be in touch soon with next steps.')]</value>
      <webElementGuid>0514c049-3df4-4944-a6bb-d16657fec247</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
