<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__startTime</name>
   <tag></tag>
   <elementGuidId>2cc6701c-e2d8-4755-ac98-98b6d7f6c690</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='startTime'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-sm-10.col-lg-10.calendar-icon > #startTime</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5af4f8e6-ca99-493d-ab6d-d62cea2ad47b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>911122b0-7c5a-49da-97a0-69e4720df35d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>startTime</value>
      <webElementGuid>3e685723-5f3d-4130-848a-8c714a3128c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>27daff9e-57a7-486d-9bc9-7e899466ea20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>startTime</value>
      <webElementGuid>0d80a379-ebe3-4263-af53-2fb0f90b8d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>e03e1d49-8cfc-484a-b3cb-1f1de2d84e4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control inputDateTime full-width ng-pristine ng-untouched ng-invalid ng-invalid-required ng-valid-date ng-valid-min ng-valid-max</value>
      <webElementGuid>1021c761-1c37-4fe9-a7a0-e4513160584b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>time-type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>16054aeb-e3a2-4a7d-9913-23650fef413d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>schedule.scheduleTime</value>
      <webElementGuid>6e8942f9-4c30-4f5b-acfe-10ddc1dd88d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>time-format</name>
      <type>Main</type>
      <value>hh:mm a</value>
      <webElementGuid>f945e454-5603-4731-afc8-45b8bc62c04f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>hh:mm AM/PM</value>
      <webElementGuid>12a30c0b-f94c-4edd-beb9-6d16f94777b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>model-time-format</name>
      <type>Main</type>
      <value>HH:mm</value>
      <webElementGuid>c345aadd-fd69-4e8b-ae62-db454e921fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-length</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>43093864-ca27-40ce-a13f-4cc0e2cc0b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hour-step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b4e8d05b-cbcf-4ad8-b85a-4eea4b3f4388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-minute-step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a2b5f724-d3a0-479f-bb64-8b122c38755d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-keydown</name>
      <type>Main</type>
      <value>bulkSmsCtrl.preventBackspace();</value>
      <webElementGuid>c2ba5e11-3f13-4173-866f-8ad0119dcf4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>bulkSmsCtrl.setTime($index);</value>
      <webElementGuid>eb7ddd6c-5f3a-4f7b-bcca-b10ddea4ae89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return false</value>
      <webElementGuid>2ea46edc-c0dd-4931-9652-700fe45439f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>!schedule.scheduleDate</value>
      <webElementGuid>348a9455-844d-4f1c-93e7-95b173279554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bulkSms&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body no-padding modal-bulk-sms&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;schedule-block&quot;]/form[@class=&quot;ng-invalid ng-invalid-required ng-valid-maxlength ng-dirty ng-valid-parse ng-valid-date ng-valid-min ng-valid-max&quot;]/fieldset[@class=&quot;ng-scope&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-10 col-lg-10 calendar-icon&quot;]/input[@id=&quot;startTime&quot;]</value>
      <webElementGuid>ecdd5ef9-6367-4196-96b2-1c0412254d67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='startTime'])[2]</value>
      <webElementGuid>edb3c890-536c-4344-9525-d046df5b81dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bulkSms']/div/div/div[2]/div/div/div[5]/form/fieldset/div[3]/div/input</value>
      <webElementGuid>051155e2-e569-4542-9770-de8b16ccd2ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[3]/div/input</value>
      <webElementGuid>a646fdd3-a59b-48e7-b5ef-f81ed1308520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'startTime' and @name = 'startTime' and @placeholder = 'hh:mm AM/PM']</value>
      <webElementGuid>041ff7d1-34b2-45a8-9594-7b16aea20320</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
