<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchByStatusOnMTP</name>
   <tag></tag>
   <elementGuidId>9030e221-5e7c-4c1e-a49d-c6aed3ed0272</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul[class='multiselect-search-list']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
