<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_02</name>
   <tag></tag>
   <elementGuidId>e2ea1bb8-ae6b-4d9b-963e-9d496eeb1f18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bulkSms']/div/div/div[2]/div/div/div[5]/form/fieldset/div[3]/div/div/table/tbody/tr[2]/td/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3540d60c-e097-445f-8c82-eac4dd81f5d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'text-muted': row[0].muted}</value>
      <webElementGuid>64bf13a1-941b-481e-a583-38b0721f41ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind</name>
      <type>Main</type>
      <value>row[0].label</value>
      <webElementGuid>ef8d8526-6246-4e72-b378-794ded7147ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>47fe011f-6a01-489b-a7ea-c616c4dec092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>02</value>
      <webElementGuid>86c8b60b-7d74-4b06-8f5c-05e4664dbce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bulkSms&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body no-padding modal-bulk-sms&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;schedule-block&quot;]/form[@class=&quot;ng-invalid ng-invalid-required ng-valid-maxlength ng-dirty ng-valid-parse ng-valid-date ng-valid-min ng-valid-max&quot;]/fieldset[@class=&quot;ng-scope&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-10 col-lg-10 calendar-icon&quot;]/div[@class=&quot;dropdown-menu timepicker ng-scope am-fade bottom-left&quot;]/table[1]/tbody[1]/tr[@class=&quot;ng-scope&quot;]/td[@class=&quot;text-center&quot;]/button[@class=&quot;btn btn-default&quot;]/span[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>568976a1-ac4f-46fd-9afb-50ad2cf4c2e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bulkSms']/div/div/div[2]/div/div/div[5]/form/fieldset/div[3]/div/div/table/tbody/tr[2]/td/button/span</value>
      <webElementGuid>57eb95f9-d693-4a2a-b0a3-2c5a031f0c53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PM'])[1]/following::span[1]</value>
      <webElementGuid>08621966-1ae1-4424-a91c-60377c90d7ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AM'])[1]/following::span[1]</value>
      <webElementGuid>682319bd-68bb-4608-90b0-3d16dfa18c2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[1]/preceding::span[1]</value>
      <webElementGuid>69d30cd8-8ad6-4598-b985-ba3149ff78a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AM'])[2]/preceding::span[3]</value>
      <webElementGuid>4c7a2579-6514-47a8-aa0e-cdcbe86dc6e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='02']/parent::*</value>
      <webElementGuid>f07a1553-97bd-4b31-970a-08357a016968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/button/span</value>
      <webElementGuid>205a36b1-db4e-4bb5-9c28-bd991342a998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '02' or . = '02')]</value>
      <webElementGuid>3f1e6b12-02f3-4967-8bb2-641120e42646</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
