<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_24</name>
   <tag></tag>
   <elementGuidId>e973500d-069e-46a0-bee1-af638d552cb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bulkSms']/div/div/div[2]/div/div/div[5]/form/fieldset/div[2]/div/div/table/tbody/tr[4]/td[6]/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-default.btn-info.btn-today > span.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>39917214-6b4c-4f5a-b6e2-41bbfe377400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'text-muted': el.muted}</value>
      <webElementGuid>bfc642c7-31e2-4557-9d34-7cb5d8be4ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind</name>
      <type>Main</type>
      <value>el.label</value>
      <webElementGuid>8ba93862-b7f8-4eb6-b0c9-2e3d855ead40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>4b18808e-eddd-4168-8928-8daf6b416451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>77f256f7-7974-4436-a563-ebfccf905e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bulkSms&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body no-padding modal-bulk-sms&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;schedule-block&quot;]/form[@class=&quot;ng-invalid ng-invalid-required ng-valid-maxlength ng-invalid-date ng-invalid-min ng-invalid-max ng-dirty ng-valid-parse&quot;]/fieldset[@class=&quot;ng-scope&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-10 col-lg-10 calendar-icon&quot;]/div[@class=&quot;dropdown-menu datepicker ng-scope am-fade bottom-right datepicker-mode-0&quot;]/table[1]/tbody[1]/tr[@class=&quot;ng-scope&quot;]/td[@class=&quot;text-center ng-scope&quot;]/button[@class=&quot;btn btn-default btn-info btn-today&quot;]/span[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>69610905-debd-4571-9c95-6252f19c1b6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bulkSms']/div/div/div[2]/div/div/div[5]/form/fieldset/div[2]/div/div/table/tbody/tr[4]/td[6]/button/span</value>
      <webElementGuid>6b3517fe-f5fd-4263-a51c-f7622c05ac1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[1]/following::span[27]</value>
      <webElementGuid>ee8afe96-11ce-4ec6-b7cf-915886fc0abd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fri'])[1]/following::span[27]</value>
      <webElementGuid>61e6bec0-3994-434d-803d-e38da89d5a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/preceding::span[16]</value>
      <webElementGuid>2c200581-20ce-413e-8997-92de0a300acf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='24']/parent::*</value>
      <webElementGuid>159705b0-0eb1-4e09-afe1-32b18681779a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[6]/button/span</value>
      <webElementGuid>79216acc-d8d1-4114-8c6e-14cb20d8fa36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '24' or . = '24')]</value>
      <webElementGuid>c234c29e-636e-45e5-85dc-9ababf83be7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
