<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__form-control custom-control ng-pr_8b4879</name>
   <tag></tag>
   <elementGuidId>e89cecc9-48f3-4c85-a722-17010394a76c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bulkSms']/div/div/div[2]/div/div/div[5]/form/fieldset/div/div/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea.form-control.custom-control.ng-pristine.ng-untouched.ng-invalid.ng-invalid-required.ng-valid-maxlength.ng-animate.ng-pristine-remove.ng-invalid-remove.ng-invalid-required-remove.ng-dirty-add.ng-valid-parse-add.ng-valid-add.ng-valid-required-add</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>7a2738e8-6d5a-4cde-a298-384510110a86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>schedule.body</value>
      <webElementGuid>2d84f69e-51cb-4543-846e-35ec1a1717eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type your message</value>
      <webElementGuid>a0767c92-c894-4ffb-bfea-cf3f196b13a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>353123b5-1a79-4f38-9cbb-8d4215637485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control custom-control ng-pristine ng-untouched ng-invalid ng-invalid-required ng-valid-maxlength ng-animate ng-pristine-remove ng-invalid-remove ng-invalid-required-remove ng-dirty-add ng-valid-parse-add ng-valid-add ng-valid-required-add</value>
      <webElementGuid>1958cb1a-f685-4268-b151-99f75a4369a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>ae613651-93fc-49a9-8cb8-ec0b669742bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bulkSms&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body no-padding modal-bulk-sms&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;schedule-block&quot;]/form[@class=&quot;ng-pristine ng-invalid ng-invalid-required ng-valid-maxlength ng-invalid-date ng-invalid-min ng-invalid-max ng-animate ng-pristine-remove ng-dirty-add ng-valid-parse-add&quot;]/fieldset[@class=&quot;ng-scope&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-10&quot;]/textarea[@class=&quot;form-control custom-control ng-pristine ng-untouched ng-invalid ng-invalid-required ng-valid-maxlength ng-animate ng-pristine-remove ng-invalid-remove ng-invalid-required-remove ng-dirty-add ng-valid-parse-add ng-valid-add ng-valid-required-add&quot;]</value>
      <webElementGuid>1f5bc7c7-d2d7-43a7-a71b-3a7fbf54ce58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bulkSms']/div/div/div[2]/div/div/div[5]/form/fieldset/div/div/textarea</value>
      <webElementGuid>627ee4c8-19c4-494c-8c00-b06f906442a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/textarea</value>
      <webElementGuid>c6d796b7-8590-4680-b8bf-d1f1f8c38fb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Type your message']</value>
      <webElementGuid>cd53ae36-d004-46d3-9448-d772d19d29e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
