<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>emailBodyLocator</name>
   <tag></tag>
   <elementGuidId>731d3f85-f41d-41e2-b6a5-3fff11536c3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.ng-pristine.ng-touched.ng-valid.ta-bind</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='txtEditor']/div[2]/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
