<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_All Candidates_fa fa-search</name>
   <tag></tag>
   <elementGuidId>c2b0ced7-e5ca-46a6-99e7-b5817c7b2937</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='contentMainDiv']/div[2]/div/div[3]/div[3]/div/div/div[2]/div/div[2]/filters-action/div/button[2]/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.filter-ico.search.btn.btn-secondary.btn-orange.bulk-orange-btn.ng-scope > span.ng-scope > i.fa.fa-search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b7d4168e-1342-45cb-b7da-4cf8e6ae3b5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-search</value>
      <webElementGuid>370b02c5-50fc-458b-b58e-54c5e385d1eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentMainDiv&quot;)/div[@class=&quot;container-main ptop5 ml ng-scope&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;manage-leads-shadow ng-scope&quot;]/div[@class=&quot;mtop5 ml captured-leads-wrapper ng-scope&quot;]/div[@class=&quot;col-lg-7 col-md-7 all-candidate-full&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;page-filter&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6 text-right talent-leads&quot;]/filters-action[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;filter_links_widget filter_links_widget_all_jobs&quot;]/button[@class=&quot;filter-ico search btn btn-secondary btn-orange bulk-orange-btn ng-scope&quot;]/span[@class=&quot;ng-scope&quot;]/i[@class=&quot;fa fa-search&quot;]</value>
      <webElementGuid>8501d68a-8297-40ca-9e5b-c6249b042ccc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentMainDiv']/div[2]/div/div[3]/div[3]/div/div/div[2]/div/div[2]/filters-action/div/button[2]/span/i</value>
      <webElementGuid>40f7f28e-496d-47e0-8163-fc30bf19b47b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//filters-action/div/button[2]/span/i</value>
      <webElementGuid>a2094ab6-b76f-42b7-950b-1473e6b38660</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
