<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Contacted</name>
   <tag></tag>
   <elementGuidId>54972d3d-957d-4b2d-a84a-876ff294bd7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//aside[@id='searchFilters']/div/filters/div/form/div[5]/oi-multiselect/div[2]/ul/li[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.multiselect-dropdown-optgroup-option.ng-binding.ng-scope.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5561276c-caec-4179-b7ff-38c17778ee45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>multiselect-dropdown-optgroup-option ng-binding ng-scope active</value>
      <webElementGuid>6c0aa30c-3c40-4f93-9ff0-330ab52c6a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-repeat</name>
      <type>Main</type>
      <value>option in options</value>
      <webElementGuid>5054b3f7-84e4-4c4f-8f43-66e7134ff10d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'active': selectorPosition === groupPos[group] + $index}</value>
      <webElementGuid>247c4f85-3db1-4948-ba53-fdfef7d0e75a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>addItem(option)</value>
      <webElementGuid>0ad3699f-0991-41bf-b160-f50dd276d213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-mouseenter</name>
      <type>Main</type>
      <value>setSelection(groupPos[group] + $index)</value>
      <webElementGuid>cc497f0a-ffa0-476b-aa34-cce7ef86e690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind-html</name>
      <type>Main</type>
      <value>getDropdownLabel(option)</value>
      <webElementGuid>3a995c32-cd2d-4044-b70f-89843fbe3a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contacted</value>
      <webElementGuid>e3543199-1bb3-4c75-bc7a-81c055eb335d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchFilters&quot;)/div[@class=&quot;sidebar-contents&quot;]/filters[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;ng-scope&quot;]/form[@class=&quot;ng-scope ng-invalid ng-invalid-required ng-dirty ng-valid-parse&quot;]/div[@class=&quot;form-group&quot;]/oi-multiselect[@class=&quot;ng-untouched ng-isolate-scope ng-dirty ng-valid-parse ng-invalid ng-invalid-required&quot;]/div[@class=&quot;multiselect-dropdown&quot;]/ul[@class=&quot;multiselect-dropdown-optgroup ng-scope&quot;]/li[@class=&quot;multiselect-dropdown-optgroup-option ng-binding ng-scope active&quot;]</value>
      <webElementGuid>9f33e7c3-a657-4fe7-95c7-448769760c4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='searchFilters']/div/filters/div/form/div[5]/oi-multiselect/div[2]/ul/li[3]</value>
      <webElementGuid>64d9ff53-f79e-4d82-9152-89ad968d81a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Awaiting interview'])[1]/following::li[1]</value>
      <webElementGuid>b8f02172-8b43-418a-8cad-05bc3963e8b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Already in database'])[1]/following::li[2]</value>
      <webElementGuid>5da071d0-52d3-4376-bf8e-6e1bb2407b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hired'])[1]/preceding::li[1]</value>
      <webElementGuid>458b7cf2-fb00-4c37-8eab-0c8728a9b269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interviewed'])[1]/preceding::li[2]</value>
      <webElementGuid>49a57a62-1817-4059-970b-02bee2c7cb50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Contacted']/parent::*</value>
      <webElementGuid>1fc964e0-cf92-41e6-a877-3bb05ee6b46e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[3]</value>
      <webElementGuid>398c4525-02bf-44f2-8b12-9e7231e51e5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Contacted' or . = 'Contacted')]</value>
      <webElementGuid>cb916af3-0ffb-4e47-9240-c7c74745583a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
