<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchLocatorOnMTP</name>
   <tag></tag>
   <elementGuidId>7418f8e3-6008-4b65-b4da-2305a77b41f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span[data-title='Search']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
