<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchLocator</name>
   <tag></tag>
   <elementGuidId>b253ca62-303d-4d60-9af6-8262a3290f5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-search.btn-block > i.fa.fa-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//aside[@id='searchFilters']/div/filters/div/form/div[10]/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>59f0769f-d457-47ad-966c-65967143a366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-search</value>
      <webElementGuid>a8c381fb-ec8a-4295-b112-f0ca7522f293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchFilters&quot;)/div[@class=&quot;sidebar-contents&quot;]/filters[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;ng-scope&quot;]/form[@class=&quot;ng-scope ng-invalid ng-invalid-required ng-dirty ng-valid-parse&quot;]/div[@class=&quot;search-buttons save-filter lead-choose-filters-btn&quot;]/button[@class=&quot;btn btn-search btn-block&quot;]/i[@class=&quot;fa fa-search&quot;]</value>
      <webElementGuid>308f820b-3664-4536-87aa-e59569b0954c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='searchFilters']/div/filters/div/form/div[10]/button/i</value>
      <webElementGuid>c44fbba8-4cad-4533-a0ea-b74005460a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/button/i</value>
      <webElementGuid>ded37f25-9515-43c5-bbfc-a1a3717e685f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
