<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>statusOFTheCandidateOnMTP</name>
   <tag></tag>
   <elementGuidId>94761f8d-d651-4f79-856e-ef07068265dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-pen</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn-append-to-body']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ff239a36-f7f1-450b-983d-57a4de8c175f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-pen</value>
      <webElementGuid>29764a39-622a-4781-83fd-29f2dcdf209e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-append-to-body&quot;)/span[@class=&quot;lead-details-status&quot;]/i[@class=&quot;fas fa-pen&quot;]</value>
      <webElementGuid>af58e46f-c672-49b0-a674-234dc9951912</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='btn-append-to-body']/span/i</value>
      <webElementGuid>4ddd0b89-0fad-41cc-a064-65675a90d0fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span/i</value>
      <webElementGuid>cc51c2e8-788b-4ff3-b1dc-9e5f3bc41f4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
