<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ThanksLocatorAfterFillingTheQuestionnareForm</name>
   <tag></tag>
   <elementGuidId>80011acd-4786-4ee0-b625-361ca7c732e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span[ng-bind-html='vm.selectedPage.content.style.thanksText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
