<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_httpsmobile-recruit.comregister</name>
   <tag></tag>
   <elementGuidId>29317baa-d68c-4b2a-87f2-3b57d5e396a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='thanksModel']/div/div/div/div/div/div/div/div/center/span/p/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ng-pristine.ng-untouched.ng-valid.ta-bind > p > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>914378e0-3ae9-4e03-bf25-1e3ba69b8521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://mobile-recruit.com/register?q=PwWLJFbX</value>
      <webElementGuid>6b8ab83f-2c3f-469f-9c6c-f58c8a8addf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>389b7e68-e075-447b-b80a-927fe4ad4463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>https://mobile-recruit.com/register</value>
      <webElementGuid>74f4a8fe-51ec-4156-85d4-2c614e9968b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;thanksModel&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body-lg&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;panel-body margin-sml&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;form-group&quot;]/center[1]/span[@class=&quot;ng-pristine ng-untouched ng-valid ta-bind&quot;]/p[1]/a[1]</value>
      <webElementGuid>aa39d973-8191-4b9b-9096-faea84cd4c33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='thanksModel']/div/div/div/div/div/div/div/div/center/span/p/a</value>
      <webElementGuid>783f19e4-d932-463f-ba97-9e68f1c3cc12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'https://mobile-recruit.com/register')]</value>
      <webElementGuid>717bda06-9a7e-44e3-b0fc-f98a31142616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='m/p/0xM4EEVVV'])[1]/following::a[2]</value>
      <webElementGuid>80847244-14fa-4ac8-9e03-22b8d921cdfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connect Now'])[1]/following::a[3]</value>
      <webElementGuid>84ecdb0f-f673-46a1-9aa1-10f2e9c0ac62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/preceding::a[1]</value>
      <webElementGuid>43b245c4-84cb-4bb3-ad47-0809668abac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WhatsApp'])[1]/preceding::a[2]</value>
      <webElementGuid>26c045a4-4eae-4c64-8e7f-d79bc33f6bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='https://mobile-recruit.com/register']/parent::*</value>
      <webElementGuid>d3252654-bcc8-432a-a1ad-ba65138570b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://mobile-recruit.com/register?q=PwWLJFbX')]</value>
      <webElementGuid>38d7b985-cf26-4368-9d0f-c7b714c70bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/p/a</value>
      <webElementGuid>b5da67e0-e237-4584-b3b4-ba80be67d46a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://mobile-recruit.com/register?q=PwWLJFbX' and (text() = 'https://mobile-recruit.com/register' or . = 'https://mobile-recruit.com/register')]</value>
      <webElementGuid>69993742-385e-4fc0-afd5-2b4f8a3e74bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
