<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Mobile Number_selected-flag</name>
   <tag></tag>
   <elementGuidId>e8d29440-f9d2-4cb0-8d5a-cce6b57f7b43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div[2]/form/fieldset/div/div/div/fieldset/div[4]/div/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.selected-flag</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>782fcc22-bcba-4ff3-9323-f26365d7790c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selected-flag</value>
      <webElementGuid>096f8a40-d4c4-4e9b-b542-227bc523efec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5b9f7463-d238-400b-9679-9a8eed5da6a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Mexico (México): +52</value>
      <webElementGuid>255673b5-7be2-4fc5-acfb-683cdf2c1d71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;microsite-min-height&quot;]/div[@class=&quot;col-sm-12&quot;]/form[@class=&quot;capture-form ng-valid ng-valid-pattern ng-valid-minlength ng-valid-maxlength ng-valid-flag-changed ng-valid-ng-intl-tel-input ng-dirty ng-valid-parse&quot;]/fieldset[1]/div[@class=&quot;innerLabel fg-form ng-scope&quot;]/div[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;fg-form-fields&quot;]/fieldset[1]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;fg-field-inner form-group ng-isolate-scope fg-field-required&quot;]/div[@class=&quot;col-9&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;intl-tel-input allow-dropdown&quot;]/div[@class=&quot;flag-container&quot;]/div[@class=&quot;selected-flag&quot;]</value>
      <webElementGuid>55de94b2-1968-4b15-b5fe-6269eda37617</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/form/fieldset/div/div/div/fieldset/div[4]/div/div/div/div/div/div</value>
      <webElementGuid>b1fb8785-2610-402c-b010-63492f97c977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile Number'])[1]/following::div[5]</value>
      <webElementGuid>c045342c-e38d-48c1-9e6b-4f9a5039bc78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::div[10]</value>
      <webElementGuid>777b7303-f786-4aac-ba15-cfa4ca1f3a1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Argentina'])[1]/preceding::div[5]</value>
      <webElementGuid>033320f7-59c2-48d4-9d46-4f42b305e039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brazil (Brasil)'])[1]/preceding::div[7]</value>
      <webElementGuid>83808d10-c3e1-4381-b111-ed3cf7a8fa0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div</value>
      <webElementGuid>6434f25d-c492-4937-970d-9f547adfbffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'Mexico (México): +52']</value>
      <webElementGuid>48b67cc2-1fdd-4abb-940c-4fb9501d9a14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
