<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_United States_Mobile Number_id1900</name>
   <tag></tag>
   <elementGuidId>d1c7e776-ef7f-4606-ae62-a5774fc61281</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id1900']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id1900</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1bdfa6a-5280-476e-8dff-e14c36c7cf8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Mobile Number_id1900</value>
      <webElementGuid>644b2b7a-0391-4d30-8889-4c99a88371c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-initial-country</name>
      <type>Main</type>
      <value>mx</value>
      <webElementGuid>6847f89b-27d1-443f-93f8-87a36c52f72a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control captureFormPhoneNumber ng-pristine ng-untouched ng-valid ng-scope ng-valid-flag-changed ng-valid-ng-intl-tel-input ng-animate ng-pristine-remove ng-valid-remove ng-valid-ng-intl-tel-input-remove ng-dirty-add ng-valid-parse-add ng-invalid-add ng-invalid-ng-intl-tel-input-add</value>
      <webElementGuid>6526b3bd-813a-4fdc-a06a-5760d115a0f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>question</name>
      <type>Main</type>
      <value>Mobile Number</value>
      <webElementGuid>f9efdb1c-afcf-4816-bcd9-bf10c683d5fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>56e2b90d-7c13-4320-9c14-ea1127712939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id1900</value>
      <webElementGuid>507a3cbe-484a-4528-8ab5-f6bbc927cd01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>form.data[field.schema.name]</value>
      <webElementGuid>787a3cf7-3d97-48d0-acaf-7395885c3490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>b136fbce-e681-4b6f-a8d3-b5de5f0d39f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>form.data[field.schema.name]</value>
      <webElementGuid>e3cae965-c04a-4bdb-99e5-31f8ed153122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>field-schema</name>
      <type>Main</type>
      <value>{&quot;type&quot;:&quot;phone&quot;,&quot;name&quot;:&quot;phone&quot;,&quot;displayName&quot;:&quot;Mobile Number&quot;,&quot;validation&quot;:{&quot;required&quot;:true,&quot;messages&quot;:{}},&quot;code&quot;:&quot;&quot;,&quot;isPrimary&quot;:true,&quot;lang&quot;:&quot;en&quot;,&quot;validationMessage&quot;:&quot;is invalid&quot;,&quot;accountCountryCode&quot;:&quot;mx&quot;}</value>
      <webElementGuid>b9ea5b4f-5f3b-44e8-88b9-e7490d97d2f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>aa1a5886-7ce7-47e1-80ef-54153c765a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>081234 56789</value>
      <webElementGuid>a14cdaa7-21a7-48ab-a6e7-6bc2c3c3dbaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id1900&quot;)</value>
      <webElementGuid>b9738565-2aed-4b5f-9b2f-939b2ac9de61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id1900']</value>
      <webElementGuid>120acbd8-5891-40ce-b626-d11fbb38d4dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/form/fieldset/div/div/div/fieldset/div[4]/div/div/div/div/input</value>
      <webElementGuid>5daeb0d7-f177-45fd-b12a-06f27349e3f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/input</value>
      <webElementGuid>b181ab5c-84c3-48d4-8bdf-c7b0b7f2c300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Mobile Number_id1900' and @type = 'text' and @id = 'id1900' and @placeholder = '081234 56789']</value>
      <webElementGuid>94d344a5-d3ee-4b32-a65a-6ec92cbdbeb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
