<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Do you have any degree , Choose one_t_dab10f</name>
   <tag></tag>
   <elementGuidId>45aac193-73e0-424b-b12b-d3580e9d72ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.terms-check.ng-pristine.ng-untouched.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>283bed0d-a29d-4132-91b5-dd154c44c07d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>476c5d26-1e97-44b8-90c1-2634e587df2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>vm.clicked</value>
      <webElementGuid>808635b9-91dc-4115-b141-9322bb7bdc8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>terms-check ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>c26f5e3b-1bc9-46a4-8b33-d5804f1456c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;microsite-min-height&quot;]/div[@class=&quot;col-sm-12&quot;]/form[@class=&quot;capture-form ng-valid-pattern ng-valid-minlength ng-valid-maxlength ng-valid-flag-changed ng-dirty ng-valid-parse ng-valid ng-valid-ng-intl-tel-input&quot;]/div[@class=&quot;mtop5 ng-scope&quot;]/span[@class=&quot;terms-capture&quot;]/input[@class=&quot;terms-check ng-pristine ng-untouched ng-valid&quot;]</value>
      <webElementGuid>fb019b3e-65d3-42d2-84ec-5e4c6517112c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='checkbox']</value>
      <webElementGuid>ef1a5557-285c-447f-b857-ccdde9569ce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/form/div/span/input</value>
      <webElementGuid>5e690af3-7e3e-416f-ad01-7d8ecabd8a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>d08c56cb-1d0f-43ac-9c06-f2d3bbad2d7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>b6fccfc2-3ee0-4e97-a3b3-fbfbe145230d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
