<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_id1899</name>
   <tag></tag>
   <elementGuidId>4c3db152-dbc3-4d8b-954a-203f3c68eb5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id1899']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id1899</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3d754e9a-e746-44d9-b101-e24b6f6ac688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>question</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>fa21f027-4737-4e6c-9af7-e1ca4ea65379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-valid ng-scope ng-valid-pattern ng-valid-minlength ng-valid-maxlength</value>
      <webElementGuid>feabebb9-1ed1-4ac5-b814-6e34005a2b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e9b06ef9-4c1e-4307-af0b-ab3c6c8c76ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id1899</value>
      <webElementGuid>fcf3c852-1c7e-4385-9c2e-8956062c661f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>f8676d9e-8673-4c62-83ce-9920595108ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>form.data[field.schema.name]</value>
      <webElementGuid>4127ff06-ae76-4843-8c8c-78934d8914e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model-options</name>
      <type>Main</type>
      <value>{ updateOn: 'blur' }</value>
      <webElementGuid>28b3ca37-769e-4530-92ca-4ec7cbef7bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-pattern</name>
      <type>Main</type>
      <value>/^[_a-zA-Z0-9!\#\$%&amp;'\*\+\/=\?\^_`\{\|}~-]+(\.[_a-zA-Z0-9!\#\$%&amp;'\*\+\/=\?\^_`\{\|}~-]+)*@[A-Za-z0-9]+[A-Za-z0-9-\+]*(\.[A-Za-z0-9-\+]+)*(\.[A-Za-z\+]{2,4})((\s)*;(\s)*[_a-zA-Z0-9\+]+(\.[_a-zA-Z0-9\+]+)*@[A-Za-z0-9-\+]+(\.[A-Za-z0-9-\+]+)*(\.[A-Za-z\+]{2,4}))*$/</value>
      <webElementGuid>98d7b5a3-bba8-4753-ac38-f0f017e21a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>isDisabled(field.schema) || fieldSchema.disabled</value>
      <webElementGuid>e5602027-3198-47e7-81bb-b2f25935d05f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id1899&quot;)</value>
      <webElementGuid>c372b032-9085-4371-b8d0-59b4b9a0e379</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id1899']</value>
      <webElementGuid>8fa7ef15-3415-49a7-9f34-f0578a950a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/form/fieldset/div/div/div/fieldset/div[3]/div/div/div/input</value>
      <webElementGuid>3e73eb98-4a13-4345-b0ad-e3531ab9dbd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>213b577a-dd01-4219-8dcd-e3107edfd036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'id1899']</value>
      <webElementGuid>e17e4431-e609-41aa-8a14-dc304940a5d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
