<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_India ()91</name>
   <tag></tag>
   <elementGuidId>b73d7031-9f9f-4093-9ffb-6ea6b57559f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div[2]/form/fieldset/div/div/div/fieldset/div[4]/div/div/div/div/div/ul/li[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.country.highlight</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>01b6d1a8-c760-4236-bbf8-5bd34cda7fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>country highlight</value>
      <webElementGuid>cfe4349c-7b72-4d2a-b3b9-a27670444715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dial-code</name>
      <type>Main</type>
      <value>91</value>
      <webElementGuid>46fe9fb8-458b-444a-93bf-d2020f9bb8ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-country-code</name>
      <type>Main</type>
      <value>in</value>
      <webElementGuid>a4838e5c-1e2b-48d9-8af5-b1f3fcf72b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>India (भारत)+91</value>
      <webElementGuid>2831a535-29fa-4a26-b4e2-78d3f0d67d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;microsite-min-height&quot;]/div[@class=&quot;col-sm-12&quot;]/form[@class=&quot;capture-form ng-valid ng-valid-pattern ng-valid-minlength ng-valid-maxlength ng-valid-flag-changed ng-valid-ng-intl-tel-input ng-dirty ng-valid-parse&quot;]/fieldset[1]/div[@class=&quot;innerLabel fg-form ng-scope&quot;]/div[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;fg-form-fields&quot;]/fieldset[1]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;fg-field-inner form-group ng-isolate-scope fg-field-required&quot;]/div[@class=&quot;col-9&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;intl-tel-input allow-dropdown&quot;]/div[@class=&quot;flag-container&quot;]/ul[@class=&quot;country-list dropup&quot;]/li[@class=&quot;country highlight&quot;]</value>
      <webElementGuid>0bb4d7f5-5483-4dda-a73c-9cf18d20c0bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/form/fieldset/div/div/div/fieldset/div[4]/div/div/div/div/div/ul/li[7]</value>
      <webElementGuid>a694ed6a-0f05-48c1-87b6-1da79c65f07a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Germany (Deutschland)'])[1]/following::li[1]</value>
      <webElementGuid>8df75ad8-1761-49cb-a464-3ff6c313aa87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='France'])[1]/following::li[2]</value>
      <webElementGuid>260373d9-83a0-4036-9e68-c57c24dee824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Italy (Italia)'])[1]/preceding::li[1]</value>
      <webElementGuid>643e82a3-9f20-4a87-a268-486e9f0fa936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]</value>
      <webElementGuid>9f149c37-9b3b-4e59-83b9-65afb944abbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'India (भारत)+91' or . = 'India (भारत)+91')]</value>
      <webElementGuid>083c9751-508e-402c-b17e-929eb5061887</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
