<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Launch New Job</name>
   <tag></tag>
   <elementGuidId>e9b1b815-2fca-45a1-bb25-64a4aa6a7cd7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bs-example-navbar-collapse-1']/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.dropdown.ng-scope > a.dropdown-toggle.js-activated.disabled</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d390d2b2-c22b-4a68-b211-887183588f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>ea402256-8a4b-4349-8bfd-0a7cf665ceb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>dropdownHover</value>
      <webElementGuid>e1d4618b-8c71-461b-ad9e-d39ae4136f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Launch New Job</value>
      <webElementGuid>d20208c2-7b82-4b00-95bc-0a3f1193ff2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>197be850-c770-4a9f-bb15-4db290df2f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ui-sref-opts</name>
      <type>Main</type>
      <value>{reload: true}</value>
      <webElementGuid>55a93e4f-16e0-4462-b018-3b0becc69bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle js-activated disabled</value>
      <webElementGuid>36feab8d-c298-43a4-96c7-5af52b2454a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ui-sref</name>
      <type>Main</type>
      <value>campaignWizard.details({isNew : true,isBack:false, campaignId:null})</value>
      <webElementGuid>3e29a372-8fd7-4025-a04e-6f4209b52d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/campaignWizard/details?isNew=true&amp;isBack=false</value>
      <webElementGuid>156bd4da-fb54-4d33-aa1d-4e9ab1effdce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Launch New Job </value>
      <webElementGuid>d7fbf8e1-1fd6-4d20-a05f-09bac0437836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-example-navbar-collapse-1&quot;)/ul[@class=&quot;nav navbar-nav active-menu&quot;]/li[@class=&quot;dropdown ng-scope&quot;]/a[@class=&quot;dropdown-toggle js-activated disabled&quot;]</value>
      <webElementGuid>2f1a6086-39b9-4e48-a155-b3ad8a012216</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bs-example-navbar-collapse-1']/ul/li[3]/a</value>
      <webElementGuid>a2f95b02-c23e-47ae-9289-cfee1daa6d50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Jobs'])[1]/following::a[1]</value>
      <webElementGuid>e8ff56b2-7d1b-48da-b7a5-09d35929fc73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::a[2]</value>
      <webElementGuid>a67c3ccc-8766-4b2e-ba12-f70b99128dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Support'])[1]/preceding::a[1]</value>
      <webElementGuid>4cc41ead-dfc2-4353-afb2-5f146067ff92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/campaignWizard/details?isNew=true&amp;isBack=false')]</value>
      <webElementGuid>36168bb9-8828-48fc-b56f-2913946eef5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[3]/a</value>
      <webElementGuid>30de2d7f-b036-4426-937f-e0ca1655ceab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Launch New Job' and @href = '/campaignWizard/details?isNew=true&amp;isBack=false' and (text() = '  Launch New Job ' or . = '  Launch New Job ')]</value>
      <webElementGuid>42cbcd09-5d08-4512-9560-92811398a945</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
