<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>descriptionInputBox</name>
   <tag></tag>
   <elementGuidId>c278a675-c0f0-4bbe-8456-253739ae41fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.placeholder-text</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
