<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_password</name>
   <tag></tag>
   <elementGuidId>1716af3b-cd93-466a-86e4-5614e072015b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;password&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b89f93f3-7f6e-4458-abf9-1c9b6c1b4196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>64eba9b9-25c5-464a-a82f-f1f99e844d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>3d1fc9c7-fd94-4e9a-a4ac-f524775bfc75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>1b4ebed9-2dce-4758-ad6e-ae49da2ee79a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-invalid ng-invalid-required ng-animate ng-pristine-remove ng-invalid-remove ng-invalid-required-remove ng-dirty-add ng-valid-parse-add ng-valid-add ng-valid-required-add</value>
      <webElementGuid>e14e4030-dded-4e5a-8eaf-beca712499b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>4e3b2c6d-dc81-42f9-99ae-a4b563466685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentMainDiv&quot;)/section[@class=&quot;container login-form ng-scope&quot;]/div[@class=&quot;login-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;hpanel&quot;]/div[@class=&quot;panel-body&quot;]/form[@class=&quot;ng-invalid ng-invalid-required ng-dirty ng-valid-email ng-animate ng-invalid-remove ng-invalid-required-remove ng-valid-parse-add ng-valid-add ng-valid-required-add&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control ng-pristine ng-untouched ng-invalid ng-invalid-required ng-animate ng-pristine-remove ng-invalid-remove ng-invalid-required-remove ng-dirty-add ng-valid-parse-add ng-valid-add ng-valid-required-add&quot;]</value>
      <webElementGuid>c4e93ba2-a2d2-4cc9-ae9c-851bffd620f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='password']</value>
      <webElementGuid>ca5448b8-a200-4da7-b9bd-77e66135b970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentMainDiv']/section/div/div/div/div/div/form/div[3]/input</value>
      <webElementGuid>fb28786b-a8d2-485c-8a5e-c85c6a8a1a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>3ce725c6-66d3-4a79-bd50-809853d707f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'password' and @placeholder = 'Password']</value>
      <webElementGuid>07333d6f-6e22-4242-8937-3632bda03287</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
