<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__primary-0_1</name>
   <tag></tag>
   <elementGuidId>1af5da53-7730-4bb3-bcc8-d62de454f7d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ch-a-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ch-a-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5ac4ffe8-4fbd-4fa5-8dfa-ebc4c4c792e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f3809371-9d32-4275-b727-85508e918219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ae2c71f3-e7e9-40d2-ba66-9f44c8a4c499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ch-a-0</value>
      <webElementGuid>344a8130-c0ad-4197-a15a-2a07c6e15daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>$ctrl.onRadioClick($index,$item,$event.target.checked, 'ALTERNATE')</value>
      <webElementGuid>c8589dc6-1d41-4a98-8575-ef35f1dd4daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$item.isPrimary</value>
      <webElementGuid>d9bfc3c6-dfc6-48dc-bc73-8618ed74cd3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>primary-0</value>
      <webElementGuid>2c6f2254-fee9-4e5c-aa78-42f0f65271c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>256efb3d-9ab6-48b7-ab56-c79fbf2976da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ch-a-0&quot;)</value>
      <webElementGuid>93a6a38c-e12c-4058-be8a-0cf9a06bc881</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ch-a-0']</value>
      <webElementGuid>d8ee9f59-c810-417a-85fe-54cd87d7cda4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentMainDiv']/div[2]/div/div[4]/form/div/div/div[2]/div[3]/div/div/div/div[7]/div[5]/div/div/div/div/span/span/span/span[2]/div/input</value>
      <webElementGuid>717466c6-36bf-4831-a917-824812f0c2d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/span/span/span/span[2]/div/input</value>
      <webElementGuid>bbf14408-f79c-4a64-9433-1a1f28ee719a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'ch-a-0' and @name = 'primary-0']</value>
      <webElementGuid>664ba4bf-7e92-46b0-b6fa-0f3d8af2212c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
