<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select-- Accouting  Finance Admini_f866b9</name>
   <tag></tag>
   <elementGuidId>529ef060-b6c3-490d-95c6-12654c3d4841</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='campaignFamilyId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;campaignFamilyId&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>19222dd1-b436-445d-842c-86013149da3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>campaignFamilyId</value>
      <webElementGuid>a7b57846-5810-4ad6-915f-21823b4ae9cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>$ctrl.getFunctionByID($ctrl.campaign.familyId, $ctrl.campaignForm)</value>
      <webElementGuid>aac129e6-11dd-4ad9-bcce-700ff319662e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$ctrl.campaign.familyId</value>
      <webElementGuid>7330fda9-25eb-40da-8471-b2f94d28cf95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-invalid ng-invalid-required</value>
      <webElementGuid>4ddc7fcb-41ca-435d-925e-498c7dcc0c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> --Select-- Accouting &amp; Finance Administrative Arts, Entertainment &amp; Publishing Banking &amp; Loans Computer &amp; Information Technology Construction &amp; Facilities Customer Service Education &amp; Training Engineering &amp; Architecture Government &amp; Military Jobs Healthcare Jobs Hospitality &amp; Restaurant Human Resource Insurance Law Enforement Legal Manufacturing &amp; Mechanical Marketing, Advertising &amp; PR Non-Profit &amp; Volunteer Jobs Pharmacist &amp; Biotech Real Estate Retail Sales Telecommunications Transportation &amp; Logistics Upper Management &amp; Consulting </value>
      <webElementGuid>87b144ff-2619-4b99-a57d-b690c7b7e627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentMainDiv&quot;)/div[@class=&quot;container-main ptop10 ng-scope&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;fadeIn ng-scope&quot;]/form[@class=&quot;mnone ng-scope ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-ta-min-text ng-valid-min ng-dirty ng-valid-parse ng-valid-is-exists&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;wizard-area mobile-campaign-wizard&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;col-md-10 col-lg-7 request-campaign&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-6&quot;]/select[@class=&quot;form-control ng-pristine ng-untouched ng-invalid ng-invalid-required&quot;]</value>
      <webElementGuid>744a79c6-73fe-4a9a-8c2b-d48523228418</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='campaignFamilyId']</value>
      <webElementGuid>c75480fb-299f-430b-a300-1a419b0e05e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentMainDiv']/div[2]/div/div[4]/form/div/div/div[2]/div[3]/div/div/div/div[3]/div/select</value>
      <webElementGuid>ebc7b40d-2d4a-46e3-b3dd-a1f51af36ef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::select[1]</value>
      <webElementGuid>56d91ccb-c34d-4ae7-beab-e0a555478466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/preceding::select[1]</value>
      <webElementGuid>61b70735-99f8-499e-8543-c9017e7b91ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>d3004a0c-bd2b-4114-a943-a3a5c36467b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'campaignFamilyId' and (text() = ' --Select-- Accouting &amp; Finance Administrative Arts, Entertainment &amp; Publishing Banking &amp; Loans Computer &amp; Information Technology Construction &amp; Facilities Customer Service Education &amp; Training Engineering &amp; Architecture Government &amp; Military Jobs Healthcare Jobs Hospitality &amp; Restaurant Human Resource Insurance Law Enforement Legal Manufacturing &amp; Mechanical Marketing, Advertising &amp; PR Non-Profit &amp; Volunteer Jobs Pharmacist &amp; Biotech Real Estate Retail Sales Telecommunications Transportation &amp; Logistics Upper Management &amp; Consulting ' or . = ' --Select-- Accouting &amp; Finance Administrative Arts, Entertainment &amp; Publishing Banking &amp; Loans Computer &amp; Information Technology Construction &amp; Facilities Customer Service Education &amp; Training Engineering &amp; Architecture Government &amp; Military Jobs Healthcare Jobs Hospitality &amp; Restaurant Human Resource Insurance Law Enforement Legal Manufacturing &amp; Mechanical Marketing, Advertising &amp; PR Non-Profit &amp; Volunteer Jobs Pharmacist &amp; Biotech Real Estate Retail Sales Telecommunications Transportation &amp; Logistics Upper Management &amp; Consulting ')]</value>
      <webElementGuid>a93d4425-e7ce-4983-ae71-586a6ecb9f7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
