<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sendInterviewInviteEmail</name>
   <tag></tag>
   <elementGuidId>9f973d49-7ea2-4b06-8e5d-44a5964c1f71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name='email']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
