<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Thank you for completing the pre-qualif_a215ac</name>
   <tag></tag>
   <elementGuidId>ac3a3ccf-be42-44ec-a024-d65246b76862</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#taTextElement5245746048836966</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='taTextElement5245746048836966']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0b0a910a-391b-4e65-b14a-6fd4f7d4654b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>taTextElement5245746048836966</value>
      <webElementGuid>7c83b1b4-aae6-4e6e-97ff-b2ed5ed95052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d0854c0b-4845-4dcf-aa1e-5613571447d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ta-bind</name>
      <type>Main</type>
      <value>ta-bind</value>
      <webElementGuid>54248cd0-8a8e-4043-965a-1414f8cf93a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>html</value>
      <webElementGuid>2001a225-9d27-4c0f-aaac-0ecc0520ed11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Add Job description or copy and paste from a similar job posting</value>
      <webElementGuid>d55e1412-1e1f-48fb-918d-70aa4c95eff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-valid ta-bind ng-dirty ng-valid-parse</value>
      <webElementGuid>b93164ce-9558-4029-9c13-93137bb7df03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thank you for completing the pre-qualification form. We will be in touch soon with next steps.Thank you for completing the pre-qualification form. We will be in touch soon with next steps.Thank you for completing the pre-qualification form. We will be in touch soon with next steps.Thank you for completing the pre-qualification form. We will be in touch soon with next steps.</value>
      <webElementGuid>cd0e96ac-8522-49ff-b6b7-8695f431c3d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;taTextElement5245746048836966&quot;)</value>
      <webElementGuid>7a440e9e-ebac-41d1-95e5-f7d877bbb98b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='taTextElement5245746048836966']</value>
      <webElementGuid>ca37c7e2-d24b-4701-814b-b43a58336c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentMainDiv']/div[2]/div/div[4]/form/div/div/div[2]/div[3]/div/div/div/div[6]/div/text-angular/div[2]/div[3]</value>
      <webElementGuid>0772f91f-10df-4eb1-a069-323fda909c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter minimum 200 characters.'])[1]/preceding::div[1]</value>
      <webElementGuid>90f78afa-6403-4c07-a340-c1e2449c8b54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter job description.'])[1]/preceding::div[1]</value>
      <webElementGuid>7472fe14-68dc-4bba-adca-dc14c3d525ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//text-angular/div[2]/div[3]</value>
      <webElementGuid>5b2262af-a3e4-4dad-a53c-6c676c69ab6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'taTextElement5245746048836966' and @placeholder = 'Add Job description or copy and paste from a similar job posting' and (text() = 'Thank you for completing the pre-qualification form. We will be in touch soon with next steps.Thank you for completing the pre-qualification form. We will be in touch soon with next steps.Thank you for completing the pre-qualification form. We will be in touch soon with next steps.Thank you for completing the pre-qualification form. We will be in touch soon with next steps.' or . = 'Thank you for completing the pre-qualification form. We will be in touch soon with next steps.Thank you for completing the pre-qualification form. We will be in touch soon with next steps.Thank you for completing the pre-qualification form. We will be in touch soon with next steps.Thank you for completing the pre-qualification form. We will be in touch soon with next steps.')]</value>
      <webElementGuid>b578e028-b14b-49f2-bd67-050dc0d8da00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
