<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_myName is khanmyName is khan</name>
   <tag></tag>
   <elementGuidId>045a9170-2f8f-4bc6-86f1-e2be6ac47956</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='taTextElement9257071897684586']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#taTextElement9257071897684586</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ba44f558-4192-4bdb-bbaa-3fe952792c85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>taTextElement9257071897684586</value>
      <webElementGuid>8bc9776d-91ee-43d7-9769-438b125f1c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9dcbb56f-1e8c-4bc5-b0e5-9df243ef5ea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ta-bind</name>
      <type>Main</type>
      <value>ta-bind</value>
      <webElementGuid>5408fc82-22d5-4853-9582-731f53bcc2eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>html</value>
      <webElementGuid>ebdaba93-87e1-4fc5-99ea-be7550091716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Add Job description or copy and paste from a similar job posting</value>
      <webElementGuid>29d47a87-6d2c-488b-8921-66d1ddc9a898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-valid ta-bind ng-dirty ng-valid-parse</value>
      <webElementGuid>684cb961-8732-42a8-9baf-58409c0b271b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>myName is khanmyName is khan </value>
      <webElementGuid>21a1300d-2049-48de-97bb-eef218da89b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;taTextElement9257071897684586&quot;)</value>
      <webElementGuid>40aedb0f-66b0-4018-b5e3-558c90f6a04d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='taTextElement9257071897684586']</value>
      <webElementGuid>975c9fce-aabc-40ab-ba04-709fcbbce739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentMainDiv']/div[2]/div/div[4]/form/div/div/div[2]/div[3]/div/div/div/div[6]/div/text-angular/div[2]/div[3]</value>
      <webElementGuid>0aaf9405-d69f-4de5-b6c2-e773ef344d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter minimum 200 characters.'])[1]/preceding::div[1]</value>
      <webElementGuid>43b51802-5e7b-4059-ac23-4161957507b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//text-angular/div[2]/div[3]</value>
      <webElementGuid>814474bd-4271-4a3b-b3b0-9a2f59e030f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'taTextElement9257071897684586' and @placeholder = 'Add Job description or copy and paste from a similar job posting' and (text() = 'myName is khanmyName is khan ' or . = 'myName is khanmyName is khan ')]</value>
      <webElementGuid>425cfbea-b6bc-46aa-aeac-5043fe6d5bf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
