<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__primary-0</name>
   <tag></tag>
   <elementGuidId>f2ead0a7-f94b-477f-ba4b-a79024b7de45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ch-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ch-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f27f838d-d496-40b0-a231-e28f1d00c4ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a82b54cc-066b-49ad-82c7-9327ae7fea39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f88e9797-0e85-4fd2-971b-a637f9a651f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ch-0</value>
      <webElementGuid>ec80f088-6977-4491-9182-1ed1b777dc24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>$ctrl.onRadioClick($index,$item,$event.target.checked, 'MANDATE')</value>
      <webElementGuid>0de3de59-f6b6-466b-96ec-041e560fc072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$item.isPrimary</value>
      <webElementGuid>cc7c04a8-8499-4aae-aee9-b1f7b0f8151b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>primary-0</value>
      <webElementGuid>6f2d6f01-369c-4a47-bde5-81cdd74720c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>f7748e1e-c4da-4eff-be3c-d931e3560e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ch-0&quot;)</value>
      <webElementGuid>ce9b18c1-a134-4dd4-93f7-501874e6138a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ch-0']</value>
      <webElementGuid>fda4e498-506a-401e-88b0-d43d30b6b627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-ch-0']/input</value>
      <webElementGuid>92a72d64-29a0-4afe-b8d9-8edf6ede0954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/input</value>
      <webElementGuid>0ad013de-2b02-403a-92c3-6e41af710169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'ch-0' and @name = 'primary-0']</value>
      <webElementGuid>268ac001-64f5-402d-a967-02ab7eab9241</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
