<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select-- Admin Administration BA b_360e72</name>
   <tag></tag>
   <elementGuidId>193a35f6-af29-4ee8-bd9a-e72b2e011a3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;campaignDepartmentId&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='campaignDepartmentId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4a38415b-9b97-4d74-8e17-7dd22a443553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>$ctrl.isJobReqEnabled</value>
      <webElementGuid>9733e753-81f5-4892-9fd3-d5dd2e818f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>campaignDepartmentId</value>
      <webElementGuid>af0de2a1-93b9-4f88-9d50-73f2c460f6d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$ctrl.campaign.department.id</value>
      <webElementGuid>56e6e597-80d9-4771-8632-1b3234dbb069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-invalid ng-invalid-required</value>
      <webElementGuid>111229d5-46dc-4e5a-ac09-d63110b3328d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>d9e2d113-4b7b-49f5-8d00-75a4a6b166b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> --Select-- Admin Administration BA beboIndia beboMX bebonetweb BTES Cafeteria Committee Construction Database Development DevOps Finance and Accounts Head Technical Operation HR Human Resources ISO QMS IT IT and Network Lead System Architect Marketing Maternity Online Marketing Production_Dummy PSO Purchase and Procurement Dept QA Research and Development_Dummy Resource pool Sr. Data Scientist Level 1 Sr. Data Scientist Level 2 Technical Technical Support Test Dept. MX Web </value>
      <webElementGuid>fca25c95-45a6-4dbc-8e09-4046ac124a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentMainDiv&quot;)/div[@class=&quot;container-main ptop10 ng-scope&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;fadeIn ng-scope&quot;]/form[@class=&quot;mnone ng-scope ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-min ng-dirty ng-valid-parse ng-valid-is-exists ng-valid-ta-min-text&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;wizard-area mobile-campaign-wizard&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;col-md-10 col-lg-7 request-campaign&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-6&quot;]/select[@class=&quot;form-control ng-pristine ng-untouched ng-invalid ng-invalid-required&quot;]</value>
      <webElementGuid>f9804f09-d633-4ee2-b0a9-4980ef8fbfe5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='campaignDepartmentId']</value>
      <webElementGuid>ef217dc8-504d-43f0-9204-17552204c338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentMainDiv']/div[2]/div/div[4]/form/div/div/div[2]/div[4]/div/div/div/div/div/div/select</value>
      <webElementGuid>c965858d-94ac-44b6-a4af-b7891786fd15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[15]/following::select[1]</value>
      <webElementGuid>16a4bd91-05fc-4889-9719-dd47b0669c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[16]/preceding::select[1]</value>
      <webElementGuid>21284f2a-d70b-4703-a2ce-2bea2e747786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div/select</value>
      <webElementGuid>981705d7-eaf5-436c-b1f5-4a7c0af1484e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'campaignDepartmentId' and (text() = ' --Select-- Admin Administration BA beboIndia beboMX bebonetweb BTES Cafeteria Committee Construction Database Development DevOps Finance and Accounts Head Technical Operation HR Human Resources ISO QMS IT IT and Network Lead System Architect Marketing Maternity Online Marketing Production_Dummy PSO Purchase and Procurement Dept QA Research and Development_Dummy Resource pool Sr. Data Scientist Level 1 Sr. Data Scientist Level 2 Technical Technical Support Test Dept. MX Web ' or . = ' --Select-- Admin Administration BA beboIndia beboMX bebonetweb BTES Cafeteria Committee Construction Database Development DevOps Finance and Accounts Head Technical Operation HR Human Resources ISO QMS IT IT and Network Lead System Architect Marketing Maternity Online Marketing Production_Dummy PSO Purchase and Procurement Dept QA Research and Development_Dummy Resource pool Sr. Data Scientist Level 1 Sr. Data Scientist Level 2 Technical Technical Support Test Dept. MX Web ')]</value>
      <webElementGuid>40b1e73c-76b0-482c-9810-503679270688</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
