<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select-- Academic Counselor Accoun_986933</name>
   <tag></tag>
   <elementGuidId>ff95f476-8d10-49e4-aa17-d92e3852ae16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='campaignDesignationId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;campaignDesignationId&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9da486d5-2941-4f03-a200-116904ab46c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>$ctrl.isJobReqEnabled</value>
      <webElementGuid>b03f55db-4e9d-4bb4-a27b-821ecef0507a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>campaignDesignationId</value>
      <webElementGuid>1e1a4705-8d87-4be8-b9cb-20dd2fd3be34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$ctrl.campaign.designation.id</value>
      <webElementGuid>0c1ad38c-8068-4596-b19f-883b000ef777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-invalid ng-invalid-required</value>
      <webElementGuid>bc77a3c8-927c-412e-a15a-ff3d4bc73be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>937f6068-e6bd-4b43-ae61-c2a62934328c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> --Select-- Academic Counselor Account Manager Accounts Assistant Administration and Operations Manager Administrative Officer Administrator BTES Artificial Intelligence Engineer Assistant Admin Assistant Manager Admin Assistant Manager Facilities and MEP Assistant Manager Finance Assistant Manager HR Assistant Manager Liasoning and Events Assistant Manager Purchase and Store Assistant Manager Recruitment Assistant Training Manager Associate Counselor cum coordinator Associate Data Scientist Associate Data Scientist Level 1 Associate Data Scientist Level 2 Associate Desktop Engineer Associate Director L1 Associate Director L2 Associate Executive HR Associate Hardware and Desktop Engineer Associate Hardware Engineer Associate Manager  Facilities and MEP Associate Manager Finance Associate Manager Purchase and Stores Associate Manager Security and Safety Associate Marketing Executive Associate Network Engineer Associate Product Designer Level 1 Associate Product Designer Level 2 Associate Recruiter Associate Software Architect Associate Software Architect  Level 2 Associate Software Architect Level 1 Associate Software Architect UX Level 1 Associate Software Architect UX Level 2 Associate Software Engineer Associate Software Engineer Data Base Associate System Architect Level 1 Associate System Architect Level 2 Associate System Engineer Associate Team Lead Associate Team Lead Data Base Associate Team Lead Digital Marketing Level 1 Associate Team Lead Digital Marketing Level 2 Associate Team Lead Level 1 Associate Team Lead Level 2 Associate Web Designer Asst. Trainer Business Analyst Campaign and Content Manager Center Head CEO College Trainee Communication and Soft Skill Trainer Content Writer Counselor Customer Success Manager Data Engineer Data Scientist Desktop Lead Desktop Lead Level 1 Desktop Lead Level 2 Desktop Support Engineer Digital Marketing Executive Digital Marketing Specialist Director Level 1 and Head Of Compliance Director QA and Compliance Level 1 Director QA and Compliance Level 2 Director QA L1 and Head of Compliance Director QA L2 and Head of Compliance Director QA Level 1 Director QA Level 2 Dot net Trainer Dummy Electrical Engineer Electrical incharge Executive Admin Executive Admin Operations Executive Finance Executive HR Facility incharge Front End Designer Front End Developer Front Office Executive Hardware and Desktop Engineer Hardware and Desktop Lead Hardware and Networking Executive cum Trainer Hardware Engineer Hardware Lead Level 1 Hardware Lead Level 2 Head Finance and Operations Head of Sales Head Technical Operations Intern Java cum Android Trainer Jr  Marketing Executive Lead System Architect Lead Trainer Linux Administrator Manager CMT and IT Support Manager DB Level 1 Manager Dev Manager Dev and Support Manager Dev Level 1 Manager Dev Level 2 Manager Finance Manager Finance and Accounts Manager HR Manager IT and Security Operations Manager Liasioning and Event Manager QA Level 1 Manager QA Level 2 Manager UI/UX and Digital Marketing level 1 Marketing Executive Microsoft System Adminstrator Mobile Architect   Team Lead Level 2 Mobile Architect   TL Mobile Architect and Team Lead Module Lead Module Lead Content Level 1 Module Lead Content Level 2 Module Lead Digital Marketing Level 1 Module Lead Level 1 Module Lead Level 2 Module Lead UI Level 1 Module Lead UI Level 2 Module Level Digital Marketing Level 2 Network Engineer PHP Trainer Principal Engineer Principal Engineer UI UX Level 1 Principal Engineer UI UX Level 2 Principal Software Engineer Principal Software Engineer Level 1 Principal Software Engineer Level 2 Principal Systems Engineer  Level 1 Principal Systems Engineer  Level 2 Principle Engineer UI Level 1 Principle Engineer UI Level 2 Principle Engineer UX Level 1 Principle Engineer UX Level 2 Purchase and Admin Executive QA Lead BTES QA Manager L1 cum Senior Architect QA Manager L2 cum Senior Architect Recruiter SDET Trainee Security Executive Security Incharge SEM Specialist SEM Specialist Level 2 Senior Business Analyst Senior Content Writer Level 1 Senior Content Writer Level 2 Senior Hardware and Desktop Engineer Senior Hardware Engineer Senior HR Manager Senior Manager Finance and Operations Senior Manager IT operation and Security Senior Marketing Executive Senior UI designer SEO Executive SEO Specialist SEO Specialist Level 2 Site Supervisor Software Architect Software Architect Level 1 Software Architect Level 2 Software Engineer Software Engineer Automation Software Engineer Data Base Software Engineer Devops Software Engineer Performance Software Engineer SDET Sr Designer Front end and UI Level 1 Sr Designer Front end and UI Level 2 Sr Desktop Support Engineer Sr Manager Dev Sr Microsoft Admin Sr System Administrator Sr UI Designer Level 1 Sr UI Designer Level 2 Sr Web Designer Sr. Data Scientist Sr. Data Scientist Level 1 Sr. Data Scientist Level 2 Sr. Dev Manager Level 1 Sr. Dev Manager Level 2 Sr. Executive Admin Sr. Executive Admin Operations Sr. Executive Admin Operations BTES Sr. Executive Finance Sr. Executive HR Sr. Executive HR Level 1 Sr. Executive HR Level 2 Sr. Executive Security and Safety Sr. HR Analyst Sr. Linux Admin Sr. Manager Sr. Manager IT and Security Operations Sr. Manager Level 2 Sr. Mobile Architect   Team Lead Sr. Network Engineer Sr. Purchase and Admin Executive Sr. QA Manager L2 cum Senior Architect Sr. QA Manager Level 1 Sr. QA Manager Level 2 Sr. Recruiter Sr. Recruiter Level 1 Sr. Recruiter Level 2 Sr. Software Architect Level 1 Sr. Software Engineer Sr. Software Engineer Data Base Sr. Software Engineer Database Level 1 Sr. Software Engineer Database Level 2 Sr. Software Engineer Level 1 Sr. Software Engineer Level 2 Sr. System Administrator Sr. System and Network Engineer Sr. System Architect Sr. System Engineer Sr. Technical Support Engineer Sr. Technical Support Engineer Level 2 Sr. Trainer Sr. Web Designer Sr. Web Designer Level 1 Sr. Web Designer Level 2 Student coordinator System and Network Engineer System Architect System Architect Level 1 System Architect Level 2 System Engineer System Engineer Linux System Security Engineer Team Lead Team Lead and Automation Architect Team lead cum Data Scientist Level 2 Team Lead Dot Net Team Lead JAVA Team Lead Level 1 Team Lead Level 2 Team Lead PHP Team Lead Security and IT Operations Team Lead SQA Technical Support Engineer Technical Trainer Trainee Trainer Training Coordinator Web Designer Web Designer Ui Ux </value>
      <webElementGuid>bc91f8cd-755d-4d79-870b-f645575167ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentMainDiv&quot;)/div[@class=&quot;container-main ptop10 ng-scope&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;fadeIn ng-scope&quot;]/form[@class=&quot;mnone ng-scope ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-min ng-dirty ng-valid-parse ng-valid-is-exists ng-valid-ta-min-text&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;wizard-area mobile-campaign-wizard&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;col-md-10 col-lg-7 request-campaign&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-6&quot;]/select[@class=&quot;form-control ng-pristine ng-untouched ng-invalid ng-invalid-required&quot;]</value>
      <webElementGuid>eb9de953-2385-49b6-880d-96848956fec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3a505c45-67f1-48c7-be5b-c163a46532c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>$ctrl.isJobReqEnabled</value>
      <webElementGuid>4da4d7ad-1d08-4962-bc46-f79a3f8f2b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>campaignDesignationId</value>
      <webElementGuid>dc34849a-3391-4679-9229-6a1db1fd9ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$ctrl.campaign.designation.id</value>
      <webElementGuid>22aa3c99-6f1e-4170-b42a-81c664fd0839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-invalid ng-invalid-required</value>
      <webElementGuid>83e47915-3b9a-4857-9cab-454d92e4ca84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>5eeff5dc-8e92-4dcd-aad7-fe38d3809d1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> --Select-- Academic Counselor Account Manager Accounts Assistant Administration and Operations Manager Administrative Officer Administrator BTES Artificial Intelligence Engineer Assistant Admin Assistant Manager Admin Assistant Manager Facilities and MEP Assistant Manager Finance Assistant Manager HR Assistant Manager Liasoning and Events Assistant Manager Purchase and Store Assistant Manager Recruitment Assistant Training Manager Associate Counselor cum coordinator Associate Data Scientist Associate Data Scientist Level 1 Associate Data Scientist Level 2 Associate Desktop Engineer Associate Director L1 Associate Director L2 Associate Executive HR Associate Hardware and Desktop Engineer Associate Hardware Engineer Associate Manager  Facilities and MEP Associate Manager Finance Associate Manager Purchase and Stores Associate Manager Security and Safety Associate Marketing Executive Associate Network Engineer Associate Product Designer Level 1 Associate Product Designer Level 2 Associate Recruiter Associate Software Architect Associate Software Architect  Level 2 Associate Software Architect Level 1 Associate Software Architect UX Level 1 Associate Software Architect UX Level 2 Associate Software Engineer Associate Software Engineer Data Base Associate System Architect Level 1 Associate System Architect Level 2 Associate System Engineer Associate Team Lead Associate Team Lead Data Base Associate Team Lead Digital Marketing Level 1 Associate Team Lead Digital Marketing Level 2 Associate Team Lead Level 1 Associate Team Lead Level 2 Associate Web Designer Asst. Trainer Business Analyst Campaign and Content Manager Center Head CEO College Trainee Communication and Soft Skill Trainer Content Writer Counselor Customer Success Manager Data Engineer Data Scientist Desktop Lead Desktop Lead Level 1 Desktop Lead Level 2 Desktop Support Engineer Digital Marketing Executive Digital Marketing Specialist Director Level 1 and Head Of Compliance Director QA and Compliance Level 1 Director QA and Compliance Level 2 Director QA L1 and Head of Compliance Director QA L2 and Head of Compliance Director QA Level 1 Director QA Level 2 Dot net Trainer Dummy Electrical Engineer Electrical incharge Executive Admin Executive Admin Operations Executive Finance Executive HR Facility incharge Front End Designer Front End Developer Front Office Executive Hardware and Desktop Engineer Hardware and Desktop Lead Hardware and Networking Executive cum Trainer Hardware Engineer Hardware Lead Level 1 Hardware Lead Level 2 Head Finance and Operations Head of Sales Head Technical Operations Intern Java cum Android Trainer Jr  Marketing Executive Lead System Architect Lead Trainer Linux Administrator Manager CMT and IT Support Manager DB Level 1 Manager Dev Manager Dev and Support Manager Dev Level 1 Manager Dev Level 2 Manager Finance Manager Finance and Accounts Manager HR Manager IT and Security Operations Manager Liasioning and Event Manager QA Level 1 Manager QA Level 2 Manager UI/UX and Digital Marketing level 1 Marketing Executive Microsoft System Adminstrator Mobile Architect   Team Lead Level 2 Mobile Architect   TL Mobile Architect and Team Lead Module Lead Module Lead Content Level 1 Module Lead Content Level 2 Module Lead Digital Marketing Level 1 Module Lead Level 1 Module Lead Level 2 Module Lead UI Level 1 Module Lead UI Level 2 Module Level Digital Marketing Level 2 Network Engineer PHP Trainer Principal Engineer Principal Engineer UI UX Level 1 Principal Engineer UI UX Level 2 Principal Software Engineer Principal Software Engineer Level 1 Principal Software Engineer Level 2 Principal Systems Engineer  Level 1 Principal Systems Engineer  Level 2 Principle Engineer UI Level 1 Principle Engineer UI Level 2 Principle Engineer UX Level 1 Principle Engineer UX Level 2 Purchase and Admin Executive QA Lead BTES QA Manager L1 cum Senior Architect QA Manager L2 cum Senior Architect Recruiter SDET Trainee Security Executive Security Incharge SEM Specialist SEM Specialist Level 2 Senior Business Analyst Senior Content Writer Level 1 Senior Content Writer Level 2 Senior Hardware and Desktop Engineer Senior Hardware Engineer Senior HR Manager Senior Manager Finance and Operations Senior Manager IT operation and Security Senior Marketing Executive Senior UI designer SEO Executive SEO Specialist SEO Specialist Level 2 Site Supervisor Software Architect Software Architect Level 1 Software Architect Level 2 Software Engineer Software Engineer Automation Software Engineer Data Base Software Engineer Devops Software Engineer Performance Software Engineer SDET Sr Designer Front end and UI Level 1 Sr Designer Front end and UI Level 2 Sr Desktop Support Engineer Sr Manager Dev Sr Microsoft Admin Sr System Administrator Sr UI Designer Level 1 Sr UI Designer Level 2 Sr Web Designer Sr. Data Scientist Sr. Data Scientist Level 1 Sr. Data Scientist Level 2 Sr. Dev Manager Level 1 Sr. Dev Manager Level 2 Sr. Executive Admin Sr. Executive Admin Operations Sr. Executive Admin Operations BTES Sr. Executive Finance Sr. Executive HR Sr. Executive HR Level 1 Sr. Executive HR Level 2 Sr. Executive Security and Safety Sr. HR Analyst Sr. Linux Admin Sr. Manager Sr. Manager IT and Security Operations Sr. Manager Level 2 Sr. Mobile Architect   Team Lead Sr. Network Engineer Sr. Purchase and Admin Executive Sr. QA Manager L2 cum Senior Architect Sr. QA Manager Level 1 Sr. QA Manager Level 2 Sr. Recruiter Sr. Recruiter Level 1 Sr. Recruiter Level 2 Sr. Software Architect Level 1 Sr. Software Engineer Sr. Software Engineer Data Base Sr. Software Engineer Database Level 1 Sr. Software Engineer Database Level 2 Sr. Software Engineer Level 1 Sr. Software Engineer Level 2 Sr. System Administrator Sr. System and Network Engineer Sr. System Architect Sr. System Engineer Sr. Technical Support Engineer Sr. Technical Support Engineer Level 2 Sr. Trainer Sr. Web Designer Sr. Web Designer Level 1 Sr. Web Designer Level 2 Student coordinator System and Network Engineer System Architect System Architect Level 1 System Architect Level 2 System Engineer System Engineer Linux System Security Engineer Team Lead Team Lead and Automation Architect Team lead cum Data Scientist Level 2 Team Lead Dot Net Team Lead JAVA Team Lead Level 1 Team Lead Level 2 Team Lead PHP Team Lead Security and IT Operations Team Lead SQA Technical Support Engineer Technical Trainer Trainee Trainer Training Coordinator Web Designer Web Designer Ui Ux </value>
      <webElementGuid>c0e1319e-bb08-4407-86d6-aeafc7677761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentMainDiv&quot;)/div[@class=&quot;container-main ptop10 ng-scope&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;fadeIn ng-scope&quot;]/form[@class=&quot;mnone ng-scope ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-min ng-dirty ng-valid-parse ng-valid-is-exists ng-valid-ta-min-text&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;wizard-area mobile-campaign-wizard&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;col-md-10 col-lg-7 request-campaign&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-6&quot;]/select[@class=&quot;form-control ng-pristine ng-untouched ng-invalid ng-invalid-required&quot;]</value>
      <webElementGuid>0216d109-efbd-4197-9b52-fd7716411d51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='campaignDesignationId']</value>
      <webElementGuid>aec2cd30-d5ec-42f3-a17b-cf304ce1c52e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentMainDiv']/div[2]/div/div[4]/form/div/div/div[2]/div[4]/div/div/div/div/div[2]/div/select</value>
      <webElementGuid>003963ff-015b-4ef6-9e73-ec1fa907c59b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[16]/following::select[1]</value>
      <webElementGuid>721e3aef-8d5f-404c-b7c1-add7cac3a028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[17]/preceding::select[1]</value>
      <webElementGuid>eeea3f9d-4b21-402a-aecc-b8b120d4f6b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div[2]/div/select</value>
      <webElementGuid>b20f008a-d54d-4306-bef0-96696dacf395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'campaignDesignationId' and (text() = ' --Select-- Academic Counselor Account Manager Accounts Assistant Administration and Operations Manager Administrative Officer Administrator BTES Artificial Intelligence Engineer Assistant Admin Assistant Manager Admin Assistant Manager Facilities and MEP Assistant Manager Finance Assistant Manager HR Assistant Manager Liasoning and Events Assistant Manager Purchase and Store Assistant Manager Recruitment Assistant Training Manager Associate Counselor cum coordinator Associate Data Scientist Associate Data Scientist Level 1 Associate Data Scientist Level 2 Associate Desktop Engineer Associate Director L1 Associate Director L2 Associate Executive HR Associate Hardware and Desktop Engineer Associate Hardware Engineer Associate Manager  Facilities and MEP Associate Manager Finance Associate Manager Purchase and Stores Associate Manager Security and Safety Associate Marketing Executive Associate Network Engineer Associate Product Designer Level 1 Associate Product Designer Level 2 Associate Recruiter Associate Software Architect Associate Software Architect  Level 2 Associate Software Architect Level 1 Associate Software Architect UX Level 1 Associate Software Architect UX Level 2 Associate Software Engineer Associate Software Engineer Data Base Associate System Architect Level 1 Associate System Architect Level 2 Associate System Engineer Associate Team Lead Associate Team Lead Data Base Associate Team Lead Digital Marketing Level 1 Associate Team Lead Digital Marketing Level 2 Associate Team Lead Level 1 Associate Team Lead Level 2 Associate Web Designer Asst. Trainer Business Analyst Campaign and Content Manager Center Head CEO College Trainee Communication and Soft Skill Trainer Content Writer Counselor Customer Success Manager Data Engineer Data Scientist Desktop Lead Desktop Lead Level 1 Desktop Lead Level 2 Desktop Support Engineer Digital Marketing Executive Digital Marketing Specialist Director Level 1 and Head Of Compliance Director QA and Compliance Level 1 Director QA and Compliance Level 2 Director QA L1 and Head of Compliance Director QA L2 and Head of Compliance Director QA Level 1 Director QA Level 2 Dot net Trainer Dummy Electrical Engineer Electrical incharge Executive Admin Executive Admin Operations Executive Finance Executive HR Facility incharge Front End Designer Front End Developer Front Office Executive Hardware and Desktop Engineer Hardware and Desktop Lead Hardware and Networking Executive cum Trainer Hardware Engineer Hardware Lead Level 1 Hardware Lead Level 2 Head Finance and Operations Head of Sales Head Technical Operations Intern Java cum Android Trainer Jr  Marketing Executive Lead System Architect Lead Trainer Linux Administrator Manager CMT and IT Support Manager DB Level 1 Manager Dev Manager Dev and Support Manager Dev Level 1 Manager Dev Level 2 Manager Finance Manager Finance and Accounts Manager HR Manager IT and Security Operations Manager Liasioning and Event Manager QA Level 1 Manager QA Level 2 Manager UI/UX and Digital Marketing level 1 Marketing Executive Microsoft System Adminstrator Mobile Architect   Team Lead Level 2 Mobile Architect   TL Mobile Architect and Team Lead Module Lead Module Lead Content Level 1 Module Lead Content Level 2 Module Lead Digital Marketing Level 1 Module Lead Level 1 Module Lead Level 2 Module Lead UI Level 1 Module Lead UI Level 2 Module Level Digital Marketing Level 2 Network Engineer PHP Trainer Principal Engineer Principal Engineer UI UX Level 1 Principal Engineer UI UX Level 2 Principal Software Engineer Principal Software Engineer Level 1 Principal Software Engineer Level 2 Principal Systems Engineer  Level 1 Principal Systems Engineer  Level 2 Principle Engineer UI Level 1 Principle Engineer UI Level 2 Principle Engineer UX Level 1 Principle Engineer UX Level 2 Purchase and Admin Executive QA Lead BTES QA Manager L1 cum Senior Architect QA Manager L2 cum Senior Architect Recruiter SDET Trainee Security Executive Security Incharge SEM Specialist SEM Specialist Level 2 Senior Business Analyst Senior Content Writer Level 1 Senior Content Writer Level 2 Senior Hardware and Desktop Engineer Senior Hardware Engineer Senior HR Manager Senior Manager Finance and Operations Senior Manager IT operation and Security Senior Marketing Executive Senior UI designer SEO Executive SEO Specialist SEO Specialist Level 2 Site Supervisor Software Architect Software Architect Level 1 Software Architect Level 2 Software Engineer Software Engineer Automation Software Engineer Data Base Software Engineer Devops Software Engineer Performance Software Engineer SDET Sr Designer Front end and UI Level 1 Sr Designer Front end and UI Level 2 Sr Desktop Support Engineer Sr Manager Dev Sr Microsoft Admin Sr System Administrator Sr UI Designer Level 1 Sr UI Designer Level 2 Sr Web Designer Sr. Data Scientist Sr. Data Scientist Level 1 Sr. Data Scientist Level 2 Sr. Dev Manager Level 1 Sr. Dev Manager Level 2 Sr. Executive Admin Sr. Executive Admin Operations Sr. Executive Admin Operations BTES Sr. Executive Finance Sr. Executive HR Sr. Executive HR Level 1 Sr. Executive HR Level 2 Sr. Executive Security and Safety Sr. HR Analyst Sr. Linux Admin Sr. Manager Sr. Manager IT and Security Operations Sr. Manager Level 2 Sr. Mobile Architect   Team Lead Sr. Network Engineer Sr. Purchase and Admin Executive Sr. QA Manager L2 cum Senior Architect Sr. QA Manager Level 1 Sr. QA Manager Level 2 Sr. Recruiter Sr. Recruiter Level 1 Sr. Recruiter Level 2 Sr. Software Architect Level 1 Sr. Software Engineer Sr. Software Engineer Data Base Sr. Software Engineer Database Level 1 Sr. Software Engineer Database Level 2 Sr. Software Engineer Level 1 Sr. Software Engineer Level 2 Sr. System Administrator Sr. System and Network Engineer Sr. System Architect Sr. System Engineer Sr. Technical Support Engineer Sr. Technical Support Engineer Level 2 Sr. Trainer Sr. Web Designer Sr. Web Designer Level 1 Sr. Web Designer Level 2 Student coordinator System and Network Engineer System Architect System Architect Level 1 System Architect Level 2 System Engineer System Engineer Linux System Security Engineer Team Lead Team Lead and Automation Architect Team lead cum Data Scientist Level 2 Team Lead Dot Net Team Lead JAVA Team Lead Level 1 Team Lead Level 2 Team Lead PHP Team Lead Security and IT Operations Team Lead SQA Technical Support Engineer Technical Trainer Trainee Trainer Training Coordinator Web Designer Web Designer Ui Ux ' or . = ' --Select-- Academic Counselor Account Manager Accounts Assistant Administration and Operations Manager Administrative Officer Administrator BTES Artificial Intelligence Engineer Assistant Admin Assistant Manager Admin Assistant Manager Facilities and MEP Assistant Manager Finance Assistant Manager HR Assistant Manager Liasoning and Events Assistant Manager Purchase and Store Assistant Manager Recruitment Assistant Training Manager Associate Counselor cum coordinator Associate Data Scientist Associate Data Scientist Level 1 Associate Data Scientist Level 2 Associate Desktop Engineer Associate Director L1 Associate Director L2 Associate Executive HR Associate Hardware and Desktop Engineer Associate Hardware Engineer Associate Manager  Facilities and MEP Associate Manager Finance Associate Manager Purchase and Stores Associate Manager Security and Safety Associate Marketing Executive Associate Network Engineer Associate Product Designer Level 1 Associate Product Designer Level 2 Associate Recruiter Associate Software Architect Associate Software Architect  Level 2 Associate Software Architect Level 1 Associate Software Architect UX Level 1 Associate Software Architect UX Level 2 Associate Software Engineer Associate Software Engineer Data Base Associate System Architect Level 1 Associate System Architect Level 2 Associate System Engineer Associate Team Lead Associate Team Lead Data Base Associate Team Lead Digital Marketing Level 1 Associate Team Lead Digital Marketing Level 2 Associate Team Lead Level 1 Associate Team Lead Level 2 Associate Web Designer Asst. Trainer Business Analyst Campaign and Content Manager Center Head CEO College Trainee Communication and Soft Skill Trainer Content Writer Counselor Customer Success Manager Data Engineer Data Scientist Desktop Lead Desktop Lead Level 1 Desktop Lead Level 2 Desktop Support Engineer Digital Marketing Executive Digital Marketing Specialist Director Level 1 and Head Of Compliance Director QA and Compliance Level 1 Director QA and Compliance Level 2 Director QA L1 and Head of Compliance Director QA L2 and Head of Compliance Director QA Level 1 Director QA Level 2 Dot net Trainer Dummy Electrical Engineer Electrical incharge Executive Admin Executive Admin Operations Executive Finance Executive HR Facility incharge Front End Designer Front End Developer Front Office Executive Hardware and Desktop Engineer Hardware and Desktop Lead Hardware and Networking Executive cum Trainer Hardware Engineer Hardware Lead Level 1 Hardware Lead Level 2 Head Finance and Operations Head of Sales Head Technical Operations Intern Java cum Android Trainer Jr  Marketing Executive Lead System Architect Lead Trainer Linux Administrator Manager CMT and IT Support Manager DB Level 1 Manager Dev Manager Dev and Support Manager Dev Level 1 Manager Dev Level 2 Manager Finance Manager Finance and Accounts Manager HR Manager IT and Security Operations Manager Liasioning and Event Manager QA Level 1 Manager QA Level 2 Manager UI/UX and Digital Marketing level 1 Marketing Executive Microsoft System Adminstrator Mobile Architect   Team Lead Level 2 Mobile Architect   TL Mobile Architect and Team Lead Module Lead Module Lead Content Level 1 Module Lead Content Level 2 Module Lead Digital Marketing Level 1 Module Lead Level 1 Module Lead Level 2 Module Lead UI Level 1 Module Lead UI Level 2 Module Level Digital Marketing Level 2 Network Engineer PHP Trainer Principal Engineer Principal Engineer UI UX Level 1 Principal Engineer UI UX Level 2 Principal Software Engineer Principal Software Engineer Level 1 Principal Software Engineer Level 2 Principal Systems Engineer  Level 1 Principal Systems Engineer  Level 2 Principle Engineer UI Level 1 Principle Engineer UI Level 2 Principle Engineer UX Level 1 Principle Engineer UX Level 2 Purchase and Admin Executive QA Lead BTES QA Manager L1 cum Senior Architect QA Manager L2 cum Senior Architect Recruiter SDET Trainee Security Executive Security Incharge SEM Specialist SEM Specialist Level 2 Senior Business Analyst Senior Content Writer Level 1 Senior Content Writer Level 2 Senior Hardware and Desktop Engineer Senior Hardware Engineer Senior HR Manager Senior Manager Finance and Operations Senior Manager IT operation and Security Senior Marketing Executive Senior UI designer SEO Executive SEO Specialist SEO Specialist Level 2 Site Supervisor Software Architect Software Architect Level 1 Software Architect Level 2 Software Engineer Software Engineer Automation Software Engineer Data Base Software Engineer Devops Software Engineer Performance Software Engineer SDET Sr Designer Front end and UI Level 1 Sr Designer Front end and UI Level 2 Sr Desktop Support Engineer Sr Manager Dev Sr Microsoft Admin Sr System Administrator Sr UI Designer Level 1 Sr UI Designer Level 2 Sr Web Designer Sr. Data Scientist Sr. Data Scientist Level 1 Sr. Data Scientist Level 2 Sr. Dev Manager Level 1 Sr. Dev Manager Level 2 Sr. Executive Admin Sr. Executive Admin Operations Sr. Executive Admin Operations BTES Sr. Executive Finance Sr. Executive HR Sr. Executive HR Level 1 Sr. Executive HR Level 2 Sr. Executive Security and Safety Sr. HR Analyst Sr. Linux Admin Sr. Manager Sr. Manager IT and Security Operations Sr. Manager Level 2 Sr. Mobile Architect   Team Lead Sr. Network Engineer Sr. Purchase and Admin Executive Sr. QA Manager L2 cum Senior Architect Sr. QA Manager Level 1 Sr. QA Manager Level 2 Sr. Recruiter Sr. Recruiter Level 1 Sr. Recruiter Level 2 Sr. Software Architect Level 1 Sr. Software Engineer Sr. Software Engineer Data Base Sr. Software Engineer Database Level 1 Sr. Software Engineer Database Level 2 Sr. Software Engineer Level 1 Sr. Software Engineer Level 2 Sr. System Administrator Sr. System and Network Engineer Sr. System Architect Sr. System Engineer Sr. Technical Support Engineer Sr. Technical Support Engineer Level 2 Sr. Trainer Sr. Web Designer Sr. Web Designer Level 1 Sr. Web Designer Level 2 Student coordinator System and Network Engineer System Architect System Architect Level 1 System Architect Level 2 System Engineer System Engineer Linux System Security Engineer Team Lead Team Lead and Automation Architect Team lead cum Data Scientist Level 2 Team Lead Dot Net Team Lead JAVA Team Lead Level 1 Team Lead Level 2 Team Lead PHP Team Lead Security and IT Operations Team Lead SQA Technical Support Engineer Technical Trainer Trainee Trainer Training Coordinator Web Designer Web Designer Ui Ux ')]</value>
      <webElementGuid>282fb081-6393-4b13-a5ac-329865d1cc61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
