<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select-- Accountant Accounting Ass_05db36</name>
   <tag></tag>
   <elementGuidId>eb2c66da-9488-4462-aaac-fa9d51be6e9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;campaignFunctionId&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='campaignFunctionId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>41c7cc78-2695-444a-92a2-868853925f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>isFunctionResponseReceived || $ctrl.campaign.familyId == undefined </value>
      <webElementGuid>a1a6968b-56c1-4238-93e0-7fcdf8ccfb26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>campaignFunctionId</value>
      <webElementGuid>651d5f62-8020-43ec-a837-2625102a94a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$ctrl.campaign.functionID</value>
      <webElementGuid>f5e0d5bc-ff52-42b3-90f8-2f42dfc2dbc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-invalid ng-invalid-required</value>
      <webElementGuid>6a0e5fe4-4464-4500-b188-acd189dab9a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> --Select-- Accountant Accounting Assistant Bookkeeper Budget Analyst CNA Controller Credit Manager Finance Manager Financial Advisor Financial Analyst Internal Auditor Quantitative Analyst Tax Accountant Treasury Analyst VP Director of Finance </value>
      <webElementGuid>e3ff31ac-6373-48c8-b65b-2cb16c269230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentMainDiv&quot;)/div[@class=&quot;container-main ptop10 ng-scope&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;fadeIn ng-scope&quot;]/form[@class=&quot;mnone ng-scope ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-ta-min-text ng-valid-min ng-dirty ng-valid-parse ng-valid-is-exists&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;wizard-area mobile-campaign-wizard&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;col-md-10 col-lg-7 request-campaign&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-6&quot;]/select[@class=&quot;form-control ng-pristine ng-untouched ng-invalid ng-invalid-required&quot;]</value>
      <webElementGuid>926f9a80-fa9b-4b29-9c7f-f5a3c9791842</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='campaignFunctionId']</value>
      <webElementGuid>0c5dcfc7-4e41-475a-84b3-ba2d8cb87bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentMainDiv']/div[2]/div/div[4]/form/div/div/div[2]/div[3]/div/div/div/div[4]/div/select</value>
      <webElementGuid>845853c0-065a-496b-8a3f-320e87d5ae95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::select[1]</value>
      <webElementGuid>253fb284-0112-480b-8da6-f6c0cada12db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/preceding::select[1]</value>
      <webElementGuid>78157f7f-55dd-4cdf-8550-59c63bc7d801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/select</value>
      <webElementGuid>b5433e15-95ac-438e-9fe0-ebfd2a7d24c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'campaignFunctionId' and (text() = ' --Select-- Accountant Accounting Assistant Bookkeeper Budget Analyst CNA Controller Credit Manager Finance Manager Financial Advisor Financial Analyst Internal Auditor Quantitative Analyst Tax Accountant Treasury Analyst VP Director of Finance ' or . = ' --Select-- Accountant Accounting Assistant Bookkeeper Budget Analyst CNA Controller Credit Manager Finance Manager Financial Advisor Financial Analyst Internal Auditor Quantitative Analyst Tax Accountant Treasury Analyst VP Director of Finance ')]</value>
      <webElementGuid>fc1bcacf-9913-4249-b5ec-3cbb0cb41332</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
