<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Kafka</name>
   <tag></tag>
   <elementGuidId>90cf8f30-51dc-4bf5-bfae-7093562d1afa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-select-choices-row-3-6']/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-select-choices-row-3-6 > span.ui-select-choices-row-inner > span.ng-binding.ng-scope</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8d18b61b-fec3-432c-8b11-714583afe5a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding ng-scope</value>
      <webElementGuid>3ac47692-e8bc-4d6d-813b-1025e5a97968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Kafka </value>
      <webElementGuid>e7dcb65d-8e11-4f14-a96d-f861d5a95e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-select-choices-row-3-6&quot;)/span[@class=&quot;ui-select-choices-row-inner&quot;]/span[@class=&quot;ng-binding ng-scope&quot;]</value>
      <webElementGuid>b85e0471-dfd8-4a0f-bafc-a78ace6b1f67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-select-choices-row-3-6']/span/span</value>
      <webElementGuid>faa8ec00-1978-416b-aee7-20480906dc90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenkins'])[1]/following::span[2]</value>
      <webElementGuid>2c3ca248-6506-44c2-9d7a-c7e102a43100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kubernetes'])[1]/following::span[4]</value>
      <webElementGuid>ff6d5482-00e4-4ca5-bc50-1d7961cffb2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Workflow rules'])[1]/preceding::span[1]</value>
      <webElementGuid>59ac9d03-537b-4d45-9544-2c6f337dbaf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project Management Tools like JIRA, TFS, Rally Etc.'])[1]/preceding::span[3]</value>
      <webElementGuid>dedab661-d183-47c1-884a-f414fb8abb92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kafka']/parent::*</value>
      <webElementGuid>ac2fce6f-49b6-4c1e-ac5f-4f273a05d373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/span/span</value>
      <webElementGuid>415e499d-af2a-4e0c-ae6e-21eaea0250b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Kafka ' or . = ' Kafka ')]</value>
      <webElementGuid>59ec9559-da67-4013-add7-302a49b49950</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
