<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__MICROSITE_WELCOME_MESSAGE</name>
   <tag></tag>
   <elementGuidId>eef0c053-a48f-4ae2-b428-40d0496fd33a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;MICROSITE_WELCOME_MESSAGE&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='MICROSITE_WELCOME_MESSAGE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>5bf9454b-9619-4d35-a589-6bbc83125441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MICROSITE_WELCOME_MESSAGE</value>
      <webElementGuid>6606b92c-d3dd-434b-ba4d-60c52ac72c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'has-error': !$msgTmpltCtrl.templates[settingCode.VALUE].content &amp;&amp; $msgTmpltCtrl.isListLoaded}</value>
      <webElementGuid>850104b0-6fb0-40a1-ae47-141bc5214305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>$msgTmpltCtrl.templates[settingCode.VALUE]</value>
      <webElementGuid>915f7c79-ea43-416f-b94c-e23d24584224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please enter a message.</value>
      <webElementGuid>69c9f273-01ca-4820-b595-88bf03bae587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>$msgTmpltCtrl.setEditWelcomeMessage()</value>
      <webElementGuid>9793478f-f451-473b-98d0-ec884b7e5917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$msgTmpltCtrl.templates[settingCode.VALUE].content</value>
      <webElementGuid>dd7f047a-cdf2-402e-b505-cd651eea74f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-valid-required</value>
      <webElementGuid>a2c6b597-1b55-44dd-ace4-7dc731a404bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentMainDiv&quot;)/div[@class=&quot;container-main ptop10 ng-scope&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;fadeIn ng-scope&quot;]/form[@class=&quot;mnone ng-scope ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-ta-min-text ng-valid-min ng-dirty ng-valid-parse ng-valid-is-exists&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;wizard-area mobile-campaign-wizard&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;panel-body&quot;]/message-template-settings[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;col-md-10 col-lg-7 messageTemplate campaignWizard&quot;]/div[@class=&quot;form-group overflow-visible ng-scope&quot;]/div[1]/div[@class=&quot;col-sm-6 text-left&quot;]/textarea[@class=&quot;ng-pristine ng-untouched ng-valid ng-valid-required&quot;]</value>
      <webElementGuid>1fc0713b-1419-4cd5-9ae6-fb15a3e347e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='MICROSITE_WELCOME_MESSAGE']</value>
      <webElementGuid>46f37211-7732-4c38-afad-24976925f5f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentMainDiv']/div[2]/div/div[4]/form/div/div/div[2]/div[2]/div/div/message-template-settings/div/div[2]/div/div/textarea</value>
      <webElementGuid>d4be5f19-59e0-4a45-9691-d2e8f3f26c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>c4adb536-935e-48f4-98a3-cc4aca58e9a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'MICROSITE_WELCOME_MESSAGE' and @placeholder = 'Please enter a message.']</value>
      <webElementGuid>3fb7589e-5812-44ee-9c75-f1f2065447a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
