<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_On-Boarding</name>
   <tag></tag>
   <elementGuidId>2192f6be-df1a-4398-8c82-a47bfbba3bf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='altra']/ul/li[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9b8a6fe8-9ed2-4b49-8f8f-a6c3da1bfcc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab-item</value>
      <webElementGuid>68c76081-8f63-440c-92a1-d66edb00aa4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>vm.getOnboardingDetails('ONBOARD_REFRESH', 1)</value>
      <webElementGuid>94f307a7-8fd5-48b6-b99c-0f08f167ff13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>5724b440-000c-461f-9942-a0ccde3c3ab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#onboarding</value>
      <webElementGuid>569a591c-3eee-4c8f-85c8-91d43c035dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tab</name>
      <type>Main</type>
      <value>ONBOARDING_TAB</value>
      <webElementGuid>47ed2dbf-d83f-4a1d-a521-8f370b2e6008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  On-Boarding </value>
      <webElementGuid>0ffe86c8-7a19-46d7-b3b0-412eccb93eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;altra&quot;)/ul[@class=&quot;nav nav-tabs&quot;]/li[5]/a[@class=&quot;tab-item&quot;]</value>
      <webElementGuid>b825c7bc-09c7-4c31-9018-e910e4a1d0f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='altra']/ul/li[5]/a</value>
      <webElementGuid>c6e8018f-6eb0-42f7-9150-42cec3fdbff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Signing'])[1]/preceding::a[1]</value>
      <webElementGuid>b44cb8d6-fb46-4991-9a7d-265378cfe8b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Document by Name or Label'])[1]/preceding::a[2]</value>
      <webElementGuid>b682b639-bffb-4db4-8524-34d69f972a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='On-Boarding']/parent::*</value>
      <webElementGuid>4f718413-82a1-46eb-8fde-8995c695616d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#onboarding')]</value>
      <webElementGuid>653cd6a1-ed64-4228-8e1c-46a0657e5276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li[5]/a</value>
      <webElementGuid>8e28c7db-629d-42db-bed0-fb8858d6490c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#onboarding' and (text() = '  On-Boarding ' or . = '  On-Boarding ')]</value>
      <webElementGuid>b19fcf32-6ca5-49dd-b6e8-7080ca984d06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
