<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_2_rotate0</name>
   <tag></tag>
   <elementGuidId>1768f3db-38e0-4a79-85a3-db20438c4e6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>canvas.rotate0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='viewObBoardDocument']/div/div/div[2]/div/ng-pdf/canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>8b4b630c-3e90-421c-8241-532ec58d2820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rotate0</value>
      <webElementGuid>8c840517-505e-44a8-b387-778656664530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>612</value>
      <webElementGuid>39f5a016-33de-41be-a075-82eef752ca2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>792</value>
      <webElementGuid>d8231549-6c68-4170-a66e-174f8a1b4958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;viewObBoardDocument&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body padding-top-none&quot;]/div[@class=&quot;file-container ng-scope&quot;]/ng-pdf[@class=&quot;ng-binding&quot;]/canvas[@class=&quot;rotate0&quot;]</value>
      <webElementGuid>c649eb23-e57e-488c-a585-fcf1f4730c36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='viewObBoardDocument']/div/div/div[2]/div/ng-pdf/canvas</value>
      <webElementGuid>6bdc2158-b2e1-49c0-9205-ee4b1876e374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>9c3cd804-d766-469d-afeb-b17e022d5fa0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
