<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Signed</name>
   <tag></tag>
   <elementGuidId>3d279dd2-1b06-48a1-898b-14fafc04118f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.ng-scope > td.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='collapse1']/div/div/div[5]/div/table/tbody/tr/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>011dd9dd-6563-446a-b513-f349eea45d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>da7dae1f-c759-46c8-9178-3c0f6582930f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Signed </value>
      <webElementGuid>25c9ed11-78a7-4c4d-b172-a80a1afec80e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapse1&quot;)/div[@class=&quot;panel-body&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/table[@class=&quot;table table-striped&quot;]/tbody[1]/tr[@class=&quot;ng-scope&quot;]/td[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>3fdd0fb3-3ef9-4cf6-88f2-ff40fe99b63e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapse1']/div/div/div[5]/div/table/tbody/tr/td[2]</value>
      <webElementGuid>6e583ed8-1b36-498c-b835-74292c537ce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DocumentGCQtG'])[1]/following::td[1]</value>
      <webElementGuid>79b9fd56-41e0-4255-9dc3-b7e51a375187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[2]/following::td[2]</value>
      <webElementGuid>2039c127-82a7-4d8c-9936-01fd7d9f0850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Signed']/parent::*</value>
      <webElementGuid>67e1f2f8-0866-4502-aee2-ad79f9ae137e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/table/tbody/tr/td[2]</value>
      <webElementGuid>68c69230-7e69-47bf-8bbc-fc1b4acc09df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Signed ' or . = 'Signed ')]</value>
      <webElementGuid>7118cb49-5cee-4632-894b-1eef31e3d3f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
