<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_View</name>
   <tag></tag>
   <elementGuidId>1b0adc08-494a-418f-ae97-1181bff25e25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>ng-star-inserted</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[class='ng-star-inserted']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5ca1fd42-164a-44c7-bebe-69f51bc1896b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>247138d4-9ab0-451c-81b5-4e99d6726558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View</value>
      <webElementGuid>631be381-6246-4e90-95b1-fef964c8ef3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-accordion-child-0&quot;)/div[@class=&quot;mat-expansion-panel-body&quot;]/div[@class=&quot;doc-list ng-star-inserted&quot;]/ul[1]/li[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;doc-list-item&quot;]/div[@class=&quot;doc-footer&quot;]/button[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>fc140e2c-a353-4171-8c90-775f3e8c8f3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-accordion-child-0']/div/div/ul/li/div/div[3]/button</value>
      <webElementGuid>4f1ebc30-9dbf-4610-8527-aa9e059857b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Received'])[1]/following::button[1]</value>
      <webElementGuid>7345b910-88c7-41af-bdb6-28433ce272db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DocumentGCQtG'])[1]/following::button[1]</value>
      <webElementGuid>62b239c0-b0d3-4840-b442-67b226e7ff40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Verification'])[1]/preceding::button[1]</value>
      <webElementGuid>d36024a6-fe5f-40d7-b233-83732073f3b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2022 Mobile Talent. All Rights Reserved.'])[1]/preceding::button[1]</value>
      <webElementGuid>07dafa69-6992-47f3-975d-5bf36de938aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View']/parent::*</value>
      <webElementGuid>f9b421ee-1ec4-4684-8ed5-4c8708258ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div[3]/button</value>
      <webElementGuid>4a1cb77f-db22-4f1c-8537-0fd51bf15d16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'View' or . = 'View')]</value>
      <webElementGuid>403df57f-7408-46a9-8adf-2e53cef58a50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
