<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_concat(id(, , signature-pad, , ))_si_5e9dd4</name>
   <tag></tag>
   <elementGuidId>6caeaf97-b902-48c1-9498-7fe42498a97e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signature-pad</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='signature-pad']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>17896471-0452-434f-ad55-d6eee41b9d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>signature-pad</value>
      <webElementGuid>c5565987-3618-48ef-a89b-a3840c48ea48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>13b95162-417b-4ddb-8885-b9ca97ab6859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signature-pad</value>
      <webElementGuid>40b88d11-9401-4068-8ce7-8cc19b16ea22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>1417319d-4624-4708-a4e8-a795b2dff6ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signature-pad&quot;)</value>
      <webElementGuid>ea8bc758-0e39-4131-9250-f767a4e22833</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='signature-pad']</value>
      <webElementGuid>f514884f-f3d5-4b48-9370-5f02b3ffd8f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/signature-pad-dialog/mat-dialog-content/div/canvas</value>
      <webElementGuid>e5b6a54a-7238-4a9a-9f5c-d6d558b1e5c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-content/div/canvas</value>
      <webElementGuid>c66b358a-5630-49d0-9c02-2f81fd6c4078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'signature-pad']</value>
      <webElementGuid>03856832-f1b4-49d7-be26-0920693b1f0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
