<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Auto_Software_EnggineerykQF</name>
   <tag></tag>
   <elementGuidId>adde9889-b5b2-429e-9329-8d7f2c5500be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='campaign_3961']/td[3]/div/span[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.link-text.link-color-black.ng-binding.ng-click-active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>89e31460-eea1-4efd-b30b-df60edc33b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vm.openCampaignInfoDialog(campaign.campaignId,vm)</value>
      <webElementGuid>8c0f97f7-e6fc-46ee-9ba7-4894c29d6e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>1b338334-31e8-4fe5-bae8-cea866e7b5fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link-text link-color-black ng-binding ng-click-active</value>
      <webElementGuid>39f7f45a-7993-4715-93e9-c7887874e251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#myModal</value>
      <webElementGuid>da9e0b23-0d6e-41cb-a480-d4c4952a2f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Auto_Software_EnggineerykQF</value>
      <webElementGuid>ff078419-3e91-4ace-9731-8bb0ff1f6a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;campaign_3961&quot;)/td[@class=&quot;icon-move&quot;]/div[@class=&quot;campTitle&quot;]/span[@class=&quot;move-icon-dec&quot;]/a[@class=&quot;link-text link-color-black ng-binding ng-click-active&quot;]</value>
      <webElementGuid>8687b428-2162-4bf5-ba75-d4c0a056283d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='campaign_3961']/td[3]/div/span[2]/a</value>
      <webElementGuid>adcfc132-8f16-4829-a332-7a5016dba537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Auto_Software_EnggineerykQF')]</value>
      <webElementGuid>d56d5410-b4ef-4206-a24b-84c97d910f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JOB_3961'])[1]/following::a[1]</value>
      <webElementGuid>6929835e-188a-4b7e-93c6-5111f647d72b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable'])[1]/following::a[10]</value>
      <webElementGuid>1a858c0b-6c38-4734-ad34-ed11593a49e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Boost'])[2]/preceding::a[1]</value>
      <webElementGuid>04306687-d0b5-445f-b3d3-b10e4e9d3ddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable'])[2]/preceding::a[2]</value>
      <webElementGuid>e91bff42-7784-4a6e-89e0-239ea696613d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Auto_Software_EnggineerykQF']/parent::*</value>
      <webElementGuid>a1fa8f5a-ef72-490b-85a9-db79af780258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[49]</value>
      <webElementGuid>9d3fab27-b564-440e-b8de-afdd13bb4ee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/div/span[2]/a</value>
      <webElementGuid>599375d8-ffc1-45f2-892a-58a89557fd4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Auto_Software_EnggineerykQF' or . = 'Auto_Software_EnggineerykQF')]</value>
      <webElementGuid>f793a792-f745-4569-b0e3-1f2f61de64cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
