<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Contains all the recruitingjobs created b_22939d</name>
   <tag></tag>
   <elementGuidId>b27671a0-8291-4630-aa41-81cfed40274e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='contentMainDiv']/div[2]/div/div/div/div/div[2]/filters-action/div/button[2]/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.filter-ico.search.btn.btn-secondary.btn-orange.bulk-orange-btn.ng-scope > span.ng-scope > i.fa.fa-search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>867e0308-bac6-4967-9a9a-42b8de554d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-search</value>
      <webElementGuid>9b313fd3-af80-43bd-bc9b-9f35b1296299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentMainDiv&quot;)/div[@class=&quot;container-main ptop10 ng-scope&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;inner-banner&quot;]/div[@class=&quot;col-md-6 pull-right page-filter my-mobile-campaign-filters mtop10&quot;]/filters-action[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;filter_links_widget filter_links_widget_all_jobs&quot;]/button[@class=&quot;filter-ico search btn btn-secondary btn-orange bulk-orange-btn ng-scope&quot;]/span[@class=&quot;ng-scope&quot;]/i[@class=&quot;fa fa-search&quot;]</value>
      <webElementGuid>a4ffea14-d36b-4d26-ad09-7e5d640b2418</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentMainDiv']/div[2]/div/div/div/div/div[2]/filters-action/div/button[2]/span/i</value>
      <webElementGuid>f49e2800-6b84-47f5-af12-267769f379a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span/i</value>
      <webElementGuid>6d6cb81b-daf7-4776-907c-852918d0955b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
