<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Enabled_fa-clipboard-list fa-lg fas icon-_170eb9</name>
   <tag></tag>
   <elementGuidId>d3a06334-3976-41aa-8221-0ce556d388a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='campaign_3952']/td[13]/div/span[6]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa-clipboard-list.fa-lg.fas.icon-grey.ng-scope</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b55b1098-b322-4bb9-9f68-5e73b8374541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa-clipboard-list fa-lg fas icon-grey ng-scope</value>
      <webElementGuid>e59cc65d-e384-4f70-a237-5764aebd858a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>d1b55895-4cd3-4897-9e22-c6714348e5df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Survey</value>
      <webElementGuid>d6d83b1b-3562-487c-a102-9fecbf94350e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-animation</name>
      <type>Main</type>
      <value>am-flip-x</value>
      <webElementGuid>7fee1efd-2914-440f-bbd0-cec3e2e567fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;campaign_3952&quot;)/td[@class=&quot;text-center action-icons-space ng-scope&quot;]/div[@class=&quot;btn-group&quot;]/span[6]/a[@class=&quot;link-color-black&quot;]/i[@class=&quot;fa-clipboard-list fa-lg fas icon-grey ng-scope&quot;]</value>
      <webElementGuid>17e9b8b6-148f-47f2-8738-29cf4f9ce5a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='campaign_3952']/td[13]/div/span[6]/a/i</value>
      <webElementGuid>e532f1ea-9954-4eed-9f1b-71e0a406dbc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[6]/a/i</value>
      <webElementGuid>44cc88ac-061a-452d-ae94-668f98ffd155</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
