<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select microsite_form-control ui-sele_1cb159</name>
   <tag></tag>
   <elementGuidId>123b1e9c-b370-43aa-b354-cf1b55acbf3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='search'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.ui-select-search.ng-pristine.ng-untouched.ng-valid.ng-animate.ng-pristine-remove.ng-dirty-add.ng-valid-parse-add</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fbfa27d0-c214-4363-9735-d5453cfc105b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>5d139e12-142e-40a9-8df2-537a98a3173c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9bb7d2ed-0e87-417e-b78d-0dabc21c8485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f4633ad3-dcc6-40c7-841a-36a3f42d0fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>87c483d3-525a-4380-824d-a9915f349b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select box</value>
      <webElementGuid>0bbe0019-9fa8-4d6a-9918-042c0a73fd1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>ui-select-choices-2</value>
      <webElementGuid>f9d2cf43-e565-4670-88a7-92478663b6fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ui-select-search ng-pristine ng-untouched ng-valid ng-animate ng-pristine-remove ng-dirty-add ng-valid-parse-add</value>
      <webElementGuid>ddba9c1d-f183-4bf3-b6b3-8ef5b4cc8eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{ 'ui-select-search-hidden' : !$select.searchEnabled }</value>
      <webElementGuid>d4a406ea-3c61-4093-a4b5-0a96bcb0cd4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select microsite</value>
      <webElementGuid>5df52c6f-47c2-48d1-a9fc-50aa999a1e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$select.search</value>
      <webElementGuid>64ec66d8-edb5-4afb-b360-ef7cd18d4e4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>$select.open</value>
      <webElementGuid>0b83df7a-04ca-4728-9598-17607c86276f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;assignSurveyPopup&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content overflow-visible&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;link-survey ui-select-container ui-select-bootstrap dropdown open ng-valid ng-valid-required&quot;]/input[@class=&quot;form-control ui-select-search ng-pristine ng-untouched ng-valid ng-animate ng-pristine-remove ng-dirty-add ng-valid-parse-add&quot;]</value>
      <webElementGuid>f0d1eeae-6145-4c77-8b6c-76634460413c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='search'])[3]</value>
      <webElementGuid>9673fd3b-67f9-489f-8269-29005c7cf5be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='assignSurveyPopup']/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>9da71319-46f6-43c8-9bb9-96d56fd42bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>26220981-bf8b-45ba-b9fd-c219a9b498e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @placeholder = 'Select microsite']</value>
      <webElementGuid>58ec8e10-5cd8-4e2a-965e-d712e24182af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
