<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_id5238</name>
   <tag></tag>
   <elementGuidId>292b2d7c-8259-48aa-90a0-411e6f346d11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[question='Email']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>510d264e-b35d-4e50-a425-dac2a1282fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>question</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>bb5cb04b-39a5-41bb-ba1a-823306029d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-valid ng-scope ng-valid-pattern ng-valid-minlength ng-valid-maxlength</value>
      <webElementGuid>0a1c2186-d754-49ec-af0a-9213bfbfd232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8456f932-4748-4424-91e7-ee396c66a377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id5238</value>
      <webElementGuid>4efc6c6e-6f69-45da-8bc6-8060a2a6364d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>90b0911f-4b64-4973-8929-c9b7815f828e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>form.data[field.schema.name]</value>
      <webElementGuid>8d89f7fa-3012-40e2-b136-0176a558f0cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model-options</name>
      <type>Main</type>
      <value>{ updateOn: 'blur' }</value>
      <webElementGuid>6e0f6251-8cd0-4235-886d-828a43b472f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-pattern</name>
      <type>Main</type>
      <value>/^[_a-zA-Z0-9!\#\$%&amp;'\*\+\/=\?\^_`\{\|}~-]+(\.[_a-zA-Z0-9!\#\$%&amp;'\*\+\/=\?\^_`\{\|}~-]+)*@[A-Za-z0-9]+[A-Za-z0-9-\+]*(\.[A-Za-z0-9-\+]+)*(\.[A-Za-z\+]{2,4})((\s)*;(\s)*[_a-zA-Z0-9\+]+(\.[_a-zA-Z0-9\+]+)*@[A-Za-z0-9-\+]+(\.[A-Za-z0-9-\+]+)*(\.[A-Za-z\+]{2,4}))*$/</value>
      <webElementGuid>67a7d42e-3b88-4a29-ab70-91d0ad6a5bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>isDisabled(field.schema) || fieldSchema.disabled</value>
      <webElementGuid>9e1df871-1489-49a1-936d-aaaca67bf3ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id5238&quot;)</value>
      <webElementGuid>7102f37d-0a38-404f-bf8a-5897a915ee14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id5238']</value>
      <webElementGuid>a3c1d079-4603-46fe-9d95-a7bee99574e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/form/fieldset/div/div/div/fieldset/div[3]/div/div/div/input</value>
      <webElementGuid>80e520d0-9969-4558-8e64-035d140432d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>567372ee-1a6c-4274-b4b8-ca8036ac7cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'id5238']</value>
      <webElementGuid>1bfd8775-6c7c-4853-a236-541af398c03b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
