<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Do you have any experience_terms-chec_a5a9ad</name>
   <tag></tag>
   <elementGuidId>70143dcc-0da2-4430-9e1c-faca7efc1f62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.terms-check.ng-pristine.ng-untouched.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb46e815-b689-4c1a-b4ac-dc5db5860234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>30664dc1-63d6-4c41-ad4c-0d296df12df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>vm.clicked</value>
      <webElementGuid>e6265776-5a43-4ca8-97bc-7a58e110fd39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>terms-check ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>be7cbbe8-b546-4bea-8d4f-7cc20f1eef85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;microsite-min-height&quot;]/div[@class=&quot;col-sm-12&quot;]/form[@class=&quot;capture-form ng-valid-pattern ng-valid-minlength ng-valid-maxlength ng-valid-flag-changed ng-dirty ng-valid-parse ng-valid ng-valid-ng-intl-tel-input&quot;]/div[@class=&quot;mtop5 ng-scope&quot;]/span[@class=&quot;terms-capture&quot;]/input[@class=&quot;terms-check ng-pristine ng-untouched ng-valid&quot;]</value>
      <webElementGuid>951fb786-ba2c-4680-925b-bb730db1ec6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='checkbox']</value>
      <webElementGuid>09b2a0ad-7fb4-429d-895f-5db9d4962ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/form/div/span/input</value>
      <webElementGuid>e632ba14-f195-40eb-b10e-ae1d9c72df65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>82f701f5-d71c-4889-8efc-ed021ff2ea36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>85716b17-b1c5-41f2-b9d8-af86e8d39aab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
