<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name_id5236</name>
   <tag></tag>
   <elementGuidId>2ea85d04-0558-4c53-ac8b-871b3bfb28fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[question='First Name']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id5236']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ab02531-6075-44fe-91d8-b3c58c9963ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>question</name>
      <type>Main</type>
      <value>First Name</value>
      <webElementGuid>4f4229a6-beba-4404-a89e-a0745c280167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-valid ng-scope ng-valid-pattern ng-valid-minlength ng-valid-maxlength</value>
      <webElementGuid>152821db-de16-499a-82ae-235164a6d08e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>70557daa-601a-4b26-909e-7c39ff4504a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id5236</value>
      <webElementGuid>1057ba87-6456-4e3e-9ed4-3e6456636b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>ce7fa1e5-05f4-4129-bfa6-667209fef09c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>form.data[field.schema.name]</value>
      <webElementGuid>30dc4869-ec84-43bd-a402-0e27cdd0652b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>isDisabled(field.schema) || fieldSchema.disabled</value>
      <webElementGuid>56fcff72-f7fb-4add-8804-f6808e988a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id5236&quot;)</value>
      <webElementGuid>3a78469e-3515-4a5d-8143-64b05e37e1f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id5236']</value>
      <webElementGuid>31560113-4c12-452f-ad5b-d6c74dcebc0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/form/fieldset/div/div/div/fieldset/div/div/div/div/input</value>
      <webElementGuid>d417aebd-87b5-4228-be0a-9b2f0923987c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f8e3c7ae-ef2a-4d0c-8b7c-6634ca4c0bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'id5236']</value>
      <webElementGuid>0df8f506-d2b4-4faa-bdf9-af704da6131d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
