<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Do you have any experience</name>
   <tag></tag>
   <elementGuidId>b7f5c799-9bf3-4cd2-8444-cc8cb0650030</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>div:nth-of-type(6) > .fg-field-inner.fg-field-required.form-group.ng-isolate-scope select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>56053e5a-d736-4080-a6d5-e95fa8ca6b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>!field.schema.nolabel</value>
      <webElementGuid>c70f73f4-e728-45e4-a985-cad93f3d3594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-3 control-label ng-binding ng-scope</value>
      <webElementGuid>b25c33a2-f0ce-434f-bbea-0879e289027d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>id5241</value>
      <webElementGuid>5a9950b0-9c00-4f14-9ec1-2b76bf725a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Do you have any experience</value>
      <webElementGuid>cf6669fc-e726-48c2-a4ef-b05a7784d832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;microsite-min-height&quot;]/div[@class=&quot;col-sm-12&quot;]/form[@class=&quot;capture-form ng-valid-pattern ng-valid-minlength ng-valid-maxlength ng-valid-flag-changed ng-dirty ng-valid-parse ng-valid ng-valid-ng-intl-tel-input&quot;]/fieldset[1]/div[@class=&quot;innerLabel fg-form ng-scope&quot;]/div[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;fg-form-fields&quot;]/fieldset[1]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;fg-field-inner form-group ng-isolate-scope fg-field-required&quot;]/label[@class=&quot;col-3 control-label ng-binding ng-scope&quot;]</value>
      <webElementGuid>08faadab-2d81-4b0d-a233-947d1b332c51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/form/fieldset/div/div/div/fieldset/div[6]/div/label</value>
      <webElementGuid>ba811c31-b175-4e6b-adc3-8882268e83e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do you have any degree , Choose one'])[1]/following::label[1]</value>
      <webElementGuid>822179d4-a544-4b7c-ae40-2f996be791d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms &amp; Conditions'])[1]/preceding::label[1]</value>
      <webElementGuid>501f857e-02e6-4a6b-8f04-a1131e1f56f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To communicate using WhatsApp, click on the WhatsApp button after completing the form'])[1]/preceding::label[2]</value>
      <webElementGuid>92e81694-0b04-4813-873d-44fa40464a4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Do you have any experience']/parent::*</value>
      <webElementGuid>b352b333-ea10-448b-b147-bee930b435a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/label</value>
      <webElementGuid>e6b87a8e-ca1a-47c1-a1bc-235203a1268c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Do you have any experience' or . = 'Do you have any experience')]</value>
      <webElementGuid>c76ebc27-800f-4c51-b05c-b68255f911db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
