<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mobileNumber</name>
   <tag></tag>
   <elementGuidId>c83db3e8-00b4-4c22-b70a-6f5da5861c9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[question='Mobile Number']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'Mobile Number_id5239' and @type = 'text' and @id = 'id5239' and @placeholder = '081234 56789']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id5239']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c79a6409-a379-4003-826b-ab571230436c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Mobile Number_id5239</value>
      <webElementGuid>f6cba644-9fb6-48eb-bd53-0eab8fd9f79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-initial-country</name>
      <type>Main</type>
      <value>mx</value>
      <webElementGuid>2ea822a3-ff32-49d8-bd53-f52dbb380fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control captureFormPhoneNumber ng-pristine ng-untouched ng-valid ng-scope ng-valid-flag-changed ng-valid-ng-intl-tel-input</value>
      <webElementGuid>3ca77552-cd28-49b1-b0bd-7a0d7e4fe035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>question</name>
      <type>Main</type>
      <value>Mobile Number</value>
      <webElementGuid>ffeab4a5-729e-4769-8c15-ab13595f8dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>617d7070-5c63-49a0-bc4b-ef818ca59aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id5239</value>
      <webElementGuid>c56bb088-23ed-44a2-acde-168a4295d3fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>form.data[field.schema.name]</value>
      <webElementGuid>317d2493-3f4d-4f08-8627-b372a0bdff2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>96045bb9-4dc0-430f-9f99-d322b7488e07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>form.data[field.schema.name]</value>
      <webElementGuid>efa2347a-4c59-4297-8b4e-b473e7b81f22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>field-schema</name>
      <type>Main</type>
      <value>{&quot;type&quot;:&quot;phone&quot;,&quot;name&quot;:&quot;phone&quot;,&quot;displayName&quot;:&quot;Mobile Number&quot;,&quot;validation&quot;:{&quot;required&quot;:true,&quot;messages&quot;:{}},&quot;code&quot;:&quot;&quot;,&quot;isPrimary&quot;:true,&quot;lang&quot;:&quot;en&quot;,&quot;validationMessage&quot;:&quot;is invalid&quot;,&quot;accountCountryCode&quot;:&quot;mx&quot;}</value>
      <webElementGuid>786888e1-c2e4-41c4-9203-71be95ba0d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>84306fc5-fee9-4e40-9b3d-7c487385caa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>081234 56789</value>
      <webElementGuid>e80f8eb3-0cac-4337-b97b-69ce86cdbe9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id5239&quot;)</value>
      <webElementGuid>d5b891ca-da3d-4010-ad20-c02bab8a5ebf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id5239']</value>
      <webElementGuid>1a9f80c1-da77-4313-86c2-147206228a63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/form/fieldset/div/div/div/fieldset/div[4]/div/div/div/div/input</value>
      <webElementGuid>d1485bad-f07d-49eb-95ad-63b821e96c26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/input</value>
      <webElementGuid>1909bbe4-d9f9-4ce8-9c15-045b81132760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Mobile Number_id5239' and @type = 'text' and @id = 'id5239' and @placeholder = '081234 56789']</value>
      <webElementGuid>53bc7fb2-dbfd-4726-a5c0-89fe80291cd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
