<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_OptionsBtechMCA</name>
   <tag></tag>
   <elementGuidId>3f15cb27-ea58-4bbc-873e-cbba960560fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(6) > .fg-field-inner.fg-field-required.form-group.ng-isolate-scope select</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id5240']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>00235260-2b23-4086-b6fe-e42104c88abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>question</name>
      <type>Main</type>
      <value>Do you have any degree , Choose one</value>
      <webElementGuid>d9df677e-686b-44b4-b792-6dee47025992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-valid ng-scope ng-touched</value>
      <webElementGuid>5faf5ba0-0323-4562-9ada-18d31bf389ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id5240</value>
      <webElementGuid>637c7f8d-1f65-4975-bfc6-cff0b42ba889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>form.data[field.schema.name]</value>
      <webElementGuid>c6b10636-83c7-4da4-810b-a105b6ea342c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>d7f08786-cc6c-463a-ba86-6ed393c00525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OptionsBtechMCA</value>
      <webElementGuid>e828aa9d-7c1a-423b-ac8d-56acd53cbb76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id5240&quot;)</value>
      <webElementGuid>e1755b8e-e2f1-411f-8321-a6f5d3ac94c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id5240']</value>
      <webElementGuid>9c84f57c-69fb-422e-9a59-21e7ad79b44f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/form/fieldset/div/div/div/fieldset/div[5]/div/div/div/select</value>
      <webElementGuid>c84e2a4d-8c11-4657-95d9-70f269d75ad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do you have any degree , Choose one'])[1]/following::select[1]</value>
      <webElementGuid>8e2e81e0-b9b7-4ef6-965f-c7cf7868cfd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do you have any experience'])[1]/preceding::select[1]</value>
      <webElementGuid>82e346fc-57e5-4606-a7e7-6cba1cfe2ebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms &amp; Conditions'])[1]/preceding::select[2]</value>
      <webElementGuid>0877d3d3-41cc-4e4a-be85-b928b40c0b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>6be7a3e8-9597-42b3-845d-1a839296f66d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'id5240' and (text() = 'OptionsBtechMCA' or . = 'OptionsBtechMCA')]</value>
      <webElementGuid>5a723f61-8a2a-4543-a7b2-00c26503b053</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
