<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_OptionYESNO</name>
   <tag></tag>
   <elementGuidId>7905b78f-1432-4838-b592-7ad4447d098c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(5) > .fg-field-inner.fg-field-required.form-group.ng-isolate-scope select</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id5241']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b7b0db1b-1718-4702-920e-3c15df114345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>question</name>
      <type>Main</type>
      <value>Do you have any experience</value>
      <webElementGuid>f3a20367-ac5c-45fd-8a88-5daa23c686e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-valid ng-scope</value>
      <webElementGuid>5e64d163-66da-487c-a6a9-bb8a1d81f851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id5241</value>
      <webElementGuid>8836eb26-5176-4595-8f76-e3c1cac9b28f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>form.data[field.schema.name]</value>
      <webElementGuid>1992eb6d-5a64-406a-ae3c-c5a64242a96f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>0f535841-ccb1-4024-8f68-e1728eee2db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OptionYESNO</value>
      <webElementGuid>e1530833-3b4d-4381-b0fa-73fab6798dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id5241&quot;)</value>
      <webElementGuid>3046e8a3-0bbd-4fc5-9449-a3fafb413de9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id5241']</value>
      <webElementGuid>249e6475-ed8a-4508-a541-7ec524b88390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/form/fieldset/div/div/div/fieldset/div[6]/div/div/div/select</value>
      <webElementGuid>b622ab6e-0c1d-4c67-8702-348c00322c6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do you have any experience'])[1]/following::select[1]</value>
      <webElementGuid>c930f927-7d30-477e-8edb-14610c914e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do you have any degree , Choose one'])[1]/following::select[2]</value>
      <webElementGuid>9a08b4bf-0733-4cbc-9e4c-ce137927c803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms &amp; Conditions'])[1]/preceding::select[1]</value>
      <webElementGuid>73080c2c-9b30-4fa9-8d4f-68278e8b1c0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To communicate using WhatsApp, click on the WhatsApp button after completing the form'])[1]/preceding::select[1]</value>
      <webElementGuid>74610363-8c39-4d27-b7d4-5652a24ae63f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/select</value>
      <webElementGuid>fd8c3904-bcb3-458d-86f7-dfdf0661fd26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'id5241' and (text() = 'OptionYESNO' or . = 'OptionYESNO')]</value>
      <webElementGuid>1dd6f757-7fe6-4b8f-ad59-0e7397ca7416</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
