<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>termsAndConditions</name>
   <tag></tag>
   <elementGuidId>dbf857cb-9f85-4773-8158-47fb955e19ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[type='checkbox']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
