<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>accountName</name>
   <tag></tag>
   <elementGuidId>2df780d6-8283-4717-b3d7-850477dcff02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.account.ng-binding</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
