<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next</name>
   <tag></tag>
   <elementGuidId>0e77f2a2-6ebb-41e9-bc32-df201baa08b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-black.ng-scope</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>db695243-be87-408b-a9cb-879e5a656795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>vm.accountScreen != 'Update'</value>
      <webElementGuid>63dd76b2-d00a-488e-9658-474892cfe247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>(vm.accountForm.$invalid) || (vm.contactValidationForm.$invalid &amp;&amp; !vm.accountDetailsForm.isChecked) || (!vm.accountDetailsForm.attachment.dataURL &amp;&amp; !vm.accountDetailsForm.logo)</value>
      <webElementGuid>52c6e27a-c984-4c53-903b-ac63d65d0a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vm.setAccountDetails(vm.accountDetailsForm)</value>
      <webElementGuid>1ec4cf1c-f371-4d27-bf11-d9c0994e7c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-black ng-scope</value>
      <webElementGuid>d1816921-5cb4-4de3-aa07-dc1ff417a6de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>230868b8-7840-47f6-88a5-48cdedd15fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Next  </value>
      <webElementGuid>2f12cf30-9809-4edf-baba-63d908667b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step1&quot;)/div[@class=&quot;margin-lg col-md-12 mtop15&quot;]/button[@class=&quot;btn btn-black ng-scope&quot;]</value>
      <webElementGuid>78900181-9cc9-4a67-851b-cc4a0f30ece2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>1b0caf51-d638-4420-90a4-e5b2d16ac123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step1']/div[3]/button</value>
      <webElementGuid>cb41f92e-0fb7-42d7-bf62-ed1e66c4c5fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter new address'])[1]/following::button[1]</value>
      <webElementGuid>192fda00-eb27-4870-8aff-691e7b278585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use account address'])[1]/following::button[1]</value>
      <webElementGuid>93b76002-d286-42f0-9d34-745df015e880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[16]/preceding::button[1]</value>
      <webElementGuid>e24bb367-29c9-4bf3-ab58-0d676572bfe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div[3]/button</value>
      <webElementGuid>e813319c-667d-44b0-a9bf-4c0e8fdc96b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = ' Next  ' or . = ' Next  ')]</value>
      <webElementGuid>d31d6802-7145-4e19-ae93-28be1c47d6b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
