<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__contactEmail</name>
   <tag></tag>
   <elementGuidId>74d91c98-2b1d-4076-8c1d-87a85a2bafc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='contactEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;contactEmail&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41cd526b-6141-45f5-80c6-a94db601cbde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contactEmail</value>
      <webElementGuid>94911399-7efd-4680-a490-0a624d4cc556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>vm.accountDetailsForm.contactDTO.email</value>
      <webElementGuid>378d51b1-519f-4573-a95b-f435024c8eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-invalid ng-invalid-required ng-valid-pattern</value>
      <webElementGuid>e7939572-1695-48b3-b499-764d3e035c85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>25bff53a-0087-43d0-8a03-875f2125ff57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Email</value>
      <webElementGuid>ee016110-3631-4e71-bf8b-9cf5d75e543f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-pattern</name>
      <type>Main</type>
      <value>/^[_a-zA-Z0-9!\#\$%&amp;'\*\+\/=\?\^_`\{\|}~-]+(\.[_a-zA-Z0-9!\#\$%&amp;'\*\+\/=\?\^_`\{\|}~-]+)*@[A-Za-z0-9]+[A-Za-z0-9-\+]*(\.[A-Za-z0-9-\+]+)*(\.[A-Za-z\+]{2,4})((\s)*;(\s)*[_a-zA-Z0-9\+]+(\.[_a-zA-Z0-9\+]+)*@[A-Za-z0-9-\+]+(\.[A-Za-z0-9-\+]+)*(\.[A-Za-z\+]{2,4}))*$/</value>
      <webElementGuid>1e0dd5e9-ba7d-4389-9cf1-22aa5606d23c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step1&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/form[@class=&quot;ng-invalid ng-invalid-required ng-dirty ng-valid-parse ng-valid-exists ng-valid-ng-intl-tel-input ng-valid-pattern&quot;]/div[@class=&quot;row mot-country-code&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;col-lg-6&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-7&quot;]/input[@class=&quot;form-control ng-pristine ng-untouched ng-invalid ng-invalid-required ng-valid-pattern&quot;]</value>
      <webElementGuid>af354fe0-ee99-4103-b2af-93009cbc36ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='contactEmail']</value>
      <webElementGuid>77524dd9-e294-4357-a0a4-91d2216c1721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step1']/div/div/div[2]/div/form/div[18]/div/div/div/div/input</value>
      <webElementGuid>6005ef69-5e5e-4b32-8321-3f89a8c645cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[14]/following::input[1]</value>
      <webElementGuid>ce5bd025-8762-492a-b132-4226db990516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[15]/preceding::input[1]</value>
      <webElementGuid>6843ad96-fd84-494d-aa60-ca6939ad358b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/div/div/div/div/input</value>
      <webElementGuid>c08da747-b589-445e-b57f-a49834c06bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'contactEmail' and @type = 'text' and @placeholder = 'Enter Email']</value>
      <webElementGuid>fadb886a-f6cd-45bf-af05-31ed93258d2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
