<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>overrideChcekBox</name>
   <tag></tag>
   <elementGuidId>10d83107-57a1-4526-be4e-16ed6cd80d51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input#overwriteLocation</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
