<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select-- PunjabAndaman And nicobar_78b03e</name>
   <tag></tag>
   <elementGuidId>05c2c92f-0c48-4ed5-b63f-be513e66bd2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='vm.accountDetailsForm.contactDTO.stateId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;vm.accountDetailsForm.contactDTO.stateId&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fe4fd429-9171-46ec-857f-e4c80fcc5185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>vm.isStateResponseReceived</value>
      <webElementGuid>20610e75-04f5-4ea5-8f72-acb7be252218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vm.accountDetailsForm.contactDTO.stateId</value>
      <webElementGuid>fee95ae8-ff97-449c-9c73-773f45678913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>vm.accountDetailsForm.contactDTO.stateId</value>
      <webElementGuid>e0f2ad89-d06b-4f10-83a7-c0982b201cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-invalid ng-invalid-required</value>
      <webElementGuid>aeb24b26-a46f-45e6-bfd9-da34f042bac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>state.id as state.label for state in vm.stateData.states</value>
      <webElementGuid>2ec00bd8-967c-4a27-8ecd-19bd5fcfe016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select-- PunjabAndaman And nicobar islandsAndhra PradeshArunachal PradeshAssamBiharChandigarhChhattisgarhDadra And nagar haveliDaman And diuGoaGujaratHaryanaHimachal PradeshJammu And kashmirJharkhandKarnatakaKeralaLakshadweepMadhya PradeshMaharashtraManipurMeghalayaMizoramNagalandOrissaPuducherryRajasthanSikkimTamil NaduTelanganaTripuraUttar PradeshUttarakhandWest Bengal</value>
      <webElementGuid>d3ef3de7-b198-4b25-af1d-f08e0fd0c89f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step1&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/form[@class=&quot;ng-invalid ng-invalid-required ng-dirty ng-valid-parse ng-valid-exists ng-valid-ng-intl-tel-input ng-valid-pattern&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-6&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-8&quot;]/select[@class=&quot;form-control ng-pristine ng-untouched ng-invalid ng-invalid-required&quot;]</value>
      <webElementGuid>ac7bc628-4942-4133-9944-32b34f7e0562</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='vm.accountDetailsForm.contactDTO.stateId']</value>
      <webElementGuid>5219370e-32c7-41e6-94c6-901456136f4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step1']/div/div/div[2]/div/form/div[8]/div[2]/div/div/select</value>
      <webElementGuid>ce1181f3-e92a-403a-b4cd-8c2d0db9cc76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::select[1]</value>
      <webElementGuid>5a7430a4-09da-40da-ad41-b7add87b7b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State is required.'])[1]/preceding::select[1]</value>
      <webElementGuid>54d4de46-b005-4a77-8d13-69718244cc24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>5b0f4279-3a0f-42f4-80cf-1c4a5bc9197f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'vm.accountDetailsForm.contactDTO.stateId' and (text() = '--Select-- PunjabAndaman And nicobar islandsAndhra PradeshArunachal PradeshAssamBiharChandigarhChhattisgarhDadra And nagar haveliDaman And diuGoaGujaratHaryanaHimachal PradeshJammu And kashmirJharkhandKarnatakaKeralaLakshadweepMadhya PradeshMaharashtraManipurMeghalayaMizoramNagalandOrissaPuducherryRajasthanSikkimTamil NaduTelanganaTripuraUttar PradeshUttarakhandWest Bengal' or . = '--Select-- PunjabAndaman And nicobar islandsAndhra PradeshArunachal PradeshAssamBiharChandigarhChhattisgarhDadra And nagar haveliDaman And diuGoaGujaratHaryanaHimachal PradeshJammu And kashmirJharkhandKarnatakaKeralaLakshadweepMadhya PradeshMaharashtraManipurMeghalayaMizoramNagalandOrissaPuducherryRajasthanSikkimTamil NaduTelanganaTripuraUttar PradeshUttarakhandWest Bengal')]</value>
      <webElementGuid>62c64511-06a9-4726-80b9-82196444143b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
