<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>uploadButtonManageLocation</name>
   <tag></tag>
   <elementGuidId>07143aea-c326-4dd4-b677-8ef3e9b5dd8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.btn.btn-yellow.lead-uplaod-btn.ng-scope</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
