<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>descriptionHiringEvent</name>
   <tag></tag>
   <elementGuidId>f6a5612e-4fa1-4f78-8090-54c9098029d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.placeholder-text</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
