<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Add page_fa fa-plus icon-grey</name>
   <tag></tag>
   <elementGuidId>853833a1-ae75-4fe4-af2d-4b9409512a36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-plus.icon-grey</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='contentMainDiv']/create-template/div[2]/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/div[2]/div/span/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2209e80f-0e49-42f7-bfe7-cb37e90bfb5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus icon-grey</value>
      <webElementGuid>7f6960fb-7388-45f8-bc7e-1b9a204c718c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentMainDiv&quot;)/create-template[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;container-main canvas&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;margin-sm&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;microsite-main mtop&quot;]/div[@class=&quot;col-lg-2 sidebar col-lg-2-canvas&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 padding-short&quot;]/div[@class=&quot;panel-default margin-none&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;map-list ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;angular-ui-tree-handle&quot;]/span[@class=&quot;ng-scope&quot;]/a[@class=&quot;link-text link-color-black&quot;]/i[@class=&quot;fa fa-plus icon-grey&quot;]</value>
      <webElementGuid>49102da5-dc75-4ac7-a943-ad187a7276bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>fcb5335a-fbda-458d-ac79-b436f5b5615b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus icon-grey</value>
      <webElementGuid>d580e82e-bc0c-4fa4-9169-3b40375f2d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentMainDiv&quot;)/create-template[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;container-main canvas&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;margin-sm&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;microsite-main mtop&quot;]/div[@class=&quot;col-lg-2 sidebar col-lg-2-canvas&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 padding-short&quot;]/div[@class=&quot;panel-default margin-none&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;map-list ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;angular-ui-tree-handle&quot;]/span[@class=&quot;ng-scope&quot;]/a[@class=&quot;link-text link-color-black&quot;]/i[@class=&quot;fa fa-plus icon-grey&quot;]</value>
      <webElementGuid>af7e55b4-e02f-47d1-be17-489d36dca557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>4aad6f4f-9e9b-4a20-90a6-380c54de4513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus icon-grey</value>
      <webElementGuid>ea10a62d-862e-4aec-8cdb-c29f34e317ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentMainDiv&quot;)/create-template[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;container-main canvas&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;margin-sm&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;microsite-main mtop&quot;]/div[@class=&quot;col-lg-2 sidebar col-lg-2-canvas&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 padding-short&quot;]/div[@class=&quot;panel-default margin-none&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;map-list ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;angular-ui-tree-handle&quot;]/span[@class=&quot;ng-scope&quot;]/a[@class=&quot;link-text link-color-black&quot;]/i[@class=&quot;fa fa-plus icon-grey&quot;]</value>
      <webElementGuid>4461419a-f7af-4063-b926-9d883de95093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ceb18113-7da1-4d1c-8a0e-9a69dd78d8fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus icon-grey</value>
      <webElementGuid>5474cf27-18ba-49d2-a9e0-838075314a9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentMainDiv&quot;)/create-template[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;container-main canvas&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;margin-sm&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;microsite-main mtop&quot;]/div[@class=&quot;col-lg-2 sidebar col-lg-2-canvas&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 padding-short&quot;]/div[@class=&quot;panel-default margin-none&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;map-list ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;angular-ui-tree-handle&quot;]/span[@class=&quot;ng-scope&quot;]/a[@class=&quot;link-text link-color-black&quot;]/i[@class=&quot;fa fa-plus icon-grey&quot;]</value>
      <webElementGuid>5cb8e75d-d9bb-4cdd-961d-e0ab897151a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3f5784ac-9e71-4458-a236-8fcbb359c3e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus icon-grey</value>
      <webElementGuid>3ebda21c-b9fa-4ccd-9afe-0097fd043643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentMainDiv&quot;)/create-template[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;container-main canvas&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;margin-sm&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;microsite-main mtop&quot;]/div[@class=&quot;col-lg-2 sidebar col-lg-2-canvas&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 padding-short&quot;]/div[@class=&quot;panel-default margin-none&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;map-list ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;angular-ui-tree-handle&quot;]/span[@class=&quot;ng-scope&quot;]/a[@class=&quot;link-text link-color-black&quot;]/i[@class=&quot;fa fa-plus icon-grey&quot;]</value>
      <webElementGuid>a429087f-fa0a-4406-a6ce-a8e1f26b9e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>27dca728-a283-4b34-bbb2-aceaad1080e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus icon-grey</value>
      <webElementGuid>8e8a67db-5d81-4665-ad1a-901614aaa094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentMainDiv&quot;)/create-template[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;container-main canvas&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;margin-sm&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;microsite-main mtop&quot;]/div[@class=&quot;col-lg-2 sidebar col-lg-2-canvas&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 padding-short&quot;]/div[@class=&quot;panel-default margin-none&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;map-list ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;angular-ui-tree-handle&quot;]/span[@class=&quot;ng-scope&quot;]/a[@class=&quot;link-text link-color-black&quot;]/i[@class=&quot;fa fa-plus icon-grey&quot;]</value>
      <webElementGuid>15521ec2-1569-42a5-8f80-888e7f08c482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>f4f83a67-0fa7-4cc0-98bd-1a2c19ae9d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus icon-grey</value>
      <webElementGuid>00fef24d-aed9-4673-a322-8cc4831acd33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentMainDiv&quot;)/create-template[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;container-main canvas&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;margin-sm&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;microsite-main mtop&quot;]/div[@class=&quot;col-lg-2 sidebar col-lg-2-canvas&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 padding-short&quot;]/div[@class=&quot;panel-default margin-none&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;map-list ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;angular-ui-tree-handle&quot;]/span[@class=&quot;ng-scope&quot;]/a[@class=&quot;link-text link-color-black&quot;]/i[@class=&quot;fa fa-plus icon-grey&quot;]</value>
      <webElementGuid>2a15ee8b-d43e-41c6-82fb-2e04667d458c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c14e4907-8b5f-43b2-9da0-bd6e3273a565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus icon-grey</value>
      <webElementGuid>9a3cf776-6005-4cd9-adf6-0abc2b5eafda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentMainDiv&quot;)/create-template[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;container-main canvas&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;margin-sm&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;microsite-main mtop&quot;]/div[@class=&quot;col-lg-2 sidebar col-lg-2-canvas&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 padding-short&quot;]/div[@class=&quot;panel-default margin-none&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;map-list ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;angular-ui-tree-handle&quot;]/span[@class=&quot;ng-scope&quot;]/a[@class=&quot;link-text link-color-black&quot;]/i[@class=&quot;fa fa-plus icon-grey&quot;]</value>
      <webElementGuid>5465386b-c9e9-4641-a0d7-b788e9ff57f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentMainDiv']/create-template/div[2]/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/div[2]/div/span/a/i</value>
      <webElementGuid>053787e0-d5ca-458e-80ca-b8c09f7290cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add page'])[1]/i[1]</value>
      <webElementGuid>4da61c70-1dfb-443f-961d-694e4ab516a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location Selector Form'])[1]/following::i[1]</value>
      <webElementGuid>98151c89-1279-457c-bb3a-707ed0f167b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Content'])[1]/preceding::i[1]</value>
      <webElementGuid>2e91f8f1-9ee4-4440-80ac-268dcc20736f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blank Canvas'])[1]/preceding::i[1]</value>
      <webElementGuid>15a30635-e608-4925-8df5-3c404052127f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/a/i</value>
      <webElementGuid>8287f389-83c0-4729-87d4-602676c13f68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
