<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>7c5312cf-aef5-43af-bc21-22b239b523bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Capture Form&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modalToAddPage']/div/div/div[2]/form/div[3]/label/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f2538b52-3316-42c7-a1e7-850ea7cf6b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images/capture-form-ico.png</value>
      <webElementGuid>1445d6df-ad25-471a-b906-580e031696ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Capture Form</value>
      <webElementGuid>2032e59f-4f33-46e7-892a-fb1aeaa6fca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentMainDiv&quot;)/create-template[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;container-main canvas&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;margin-sm&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;microsite-main mtop&quot;]/div[@class=&quot;col-lg-2 sidebar col-lg-2-canvas&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 padding-short&quot;]/div[@class=&quot;panel-default margin-none&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;map-list ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@id=&quot;modalToAddPage&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body padding-none&quot;]/form[@class=&quot;form-blank-d ng-valid ng-valid-maxlength ng-dirty ng-valid-parse&quot;]/div[@class=&quot;col-md-6 blank-canvas-half&quot;]/label[@class=&quot;fl&quot;]/a[@class=&quot;add-pages-btn float-right&quot;]/img[1]</value>
      <webElementGuid>1e0926fb-0dab-4e2d-b97c-f60af41540ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8cbfef0b-e52d-4a08-99e2-2c8aa83401a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images/capture-form-ico.png</value>
      <webElementGuid>0065309f-8bcb-46ae-b4aa-ca9ecbe957c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Capture Form</value>
      <webElementGuid>f47fdcf1-bc4f-4c58-8d95-10b2af0649a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentMainDiv&quot;)/create-template[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;container-main canvas&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;margin-sm&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;microsite-main mtop&quot;]/div[@class=&quot;col-lg-2 sidebar col-lg-2-canvas&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 padding-short&quot;]/div[@class=&quot;panel-default margin-none&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;map-list ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@id=&quot;modalToAddPage&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body padding-none&quot;]/form[@class=&quot;form-blank-d ng-valid ng-valid-maxlength ng-dirty ng-valid-parse&quot;]/div[@class=&quot;col-md-6 blank-canvas-half&quot;]/label[@class=&quot;fl&quot;]/a[@class=&quot;add-pages-btn float-right&quot;]/img[1]</value>
      <webElementGuid>237bcb07-bd82-40bd-ae6c-d7afb2b7e924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7fd3e275-7a61-48a9-9fa3-62caa0e1408d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images/capture-form-ico.png</value>
      <webElementGuid>d2024a40-a2a4-4b7b-89ab-83aeb5029fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Capture Form</value>
      <webElementGuid>0486bfae-9f0a-4e86-ba60-8f59c0ac6395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentMainDiv&quot;)/create-template[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;container-main canvas&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;margin-sm&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;microsite-main mtop&quot;]/div[@class=&quot;col-lg-2 sidebar col-lg-2-canvas&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 padding-short&quot;]/div[@class=&quot;panel-default margin-none&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;map-list ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@id=&quot;modalToAddPage&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body padding-none&quot;]/form[@class=&quot;form-blank-d ng-valid ng-valid-maxlength ng-dirty ng-valid-parse&quot;]/div[@class=&quot;col-md-6 blank-canvas-half&quot;]/label[@class=&quot;fl&quot;]/a[@class=&quot;add-pages-btn float-right&quot;]/img[1]</value>
      <webElementGuid>0eaf5f8d-3554-47ae-8250-6cb83d319bbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalToAddPage']/div/div/div[2]/form/div[3]/label/a/img</value>
      <webElementGuid>388499b6-a900-44f3-ba17-48eda9c99a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Capture Form']</value>
      <webElementGuid>a924206e-5464-4eaa-b0f0-b0aefebc56b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/a/img</value>
      <webElementGuid>0e3f5d65-ed6e-443b-93eb-65f85d3a7eac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../images/capture-form-ico.png' and @alt = 'Capture Form']</value>
      <webElementGuid>0ace345a-47f9-4c2c-92df-89d76a9e1f57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Landing Page'])[1]/following::img[1]</value>
      <webElementGuid>a5f666d6-b2bd-495b-9524-9011a31a9710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter Page Name'])[1]/following::img[2]</value>
      <webElementGuid>4be39b8d-707c-4036-8925-9e50367d9461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture Form'])[1]/preceding::img[1]</value>
      <webElementGuid>e7b915b3-01fe-4491-9586-82ba662d056f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Questionnaire Form'])[1]/preceding::img[2]</value>
      <webElementGuid>1e98e81b-4c37-4d50-b2d1-463046546065</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
