<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Score_form-control numeric-include-ne_41ab90</name>
   <tag></tag>
   <elementGuidId>c78cbd3f-9dce-4b32-9fb6-0746555a451d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[30]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.numeric-include-negative.ng-pristine.ng-untouched.ng-valid.ng-isolate-scope</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[29]</value>
      <webElementGuid>f048a15d-cf22-4754-9356-2b2088dd4f23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseFields']/div/div/div/div/div/div/div/form/div/div/div/div/fieldset/div/div[5]/div[2]/div/div[3]/div/div/div/div/div/div/div[2]/div/div/div[2]/table/tbody/tr/td[3]/input</value>
      <webElementGuid>21eb6a52-7ec8-4b05-a601-aac4f03a4aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>ff3b954a-e69d-47ce-a401-a3283713c48a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>4b7663a6-8e36-4777-bc60-65ec69862646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[36]</value>
      <webElementGuid>ea759ff6-746b-4a1b-95d8-1ff638d612f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseFields']/div/div/div/div/div/div/div/form/div/div/div/div/fieldset/div/div[6]/div[2]/div/div[3]/div/div/div/div/div/div/div[2]/div/div/div[2]/table/tbody/tr/td[3]/input</value>
      <webElementGuid>962ac61a-232f-4dee-920b-8c00dccb6cab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div[3]/div/div/div/div/div/div/div[2]/div/div/div[2]/table/tbody/tr/td[3]/input</value>
      <webElementGuid>8c8725e8-96b3-4a4b-a2ed-1030f099034f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
