<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Score_optionValue</name>
   <tag></tag>
   <elementGuidId>55dbf796-fb74-4f0f-ab0d-9c9e6ed8860b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'optionValue']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(1)  input[name='optionValue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='optionValue']</value>
      <webElementGuid>0e4e5b10-873c-4727-8955-91918a7e5d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseFields']/div/div/div/div/div/div/div/form/div/div/div/div/fieldset/div/div[5]/div[2]/div/div[3]/div/div/div/div/div/div/div[2]/div/div/div[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>85a06efb-4df2-4e06-bc92-553b71e92843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>ceed83d0-2950-40c8-943b-0ee633b5289f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'optionValue']</value>
      <webElementGuid>079e0c31-4ca8-4e7d-9384-b7a4b7577026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='optionValue'])[3]</value>
      <webElementGuid>c8a61915-c25c-4485-b49e-6f74906b4b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseFields']/div/div/div/div/div/div/div/form/div/div/div/div/fieldset/div/div[6]/div[2]/div/div[3]/div/div/div/div/div/div/div[2]/div/div/div[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>42aff1cb-bf12-476a-9950-17366cb88cfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div[3]/div/div/div/div/div/div/div[2]/div/div/div[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>fabf1199-5ca2-4590-90cd-a160140437a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
