<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Score_optionValue</name>
   <tag></tag>
   <elementGuidId>55dbf796-fb74-4f0f-ab0d-9c9e6ed8860b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;optionValue&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='optionValue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e7b4198-7217-4e56-b0a8-ee508e3548ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2561ea5b-52e7-4d09-a332-9a80f826b9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>optionValue</value>
      <webElementGuid>35eb4e03-4610-4b0d-b835-a778b71255b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>option.value</value>
      <webElementGuid>374034f9-09e1-4abd-b34e-e4f7013271a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ca061f93-bc50-4d45-98fe-00731f5543d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-valid ng-valid-required</value>
      <webElementGuid>d8ffdb0d-76af-4ecc-b6ec-92e992d3af1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>8948c752-3dae-4735-8f43-80ab2ebd5919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapseFields&quot;)/div[@class=&quot;panel-body bg-grey&quot;]/div[@class=&quot;needs-some-more-space ng-isolate-scope&quot;]/div[@class=&quot;fg-tabs tabbable&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;fg-tabs-pane&quot;]/div[@class=&quot;ng-scope&quot;]/form[@class=&quot;form-horizontal ng-valid ng-scope ng-valid-pattern ng-valid-minlength ng-valid-maxlength ng-valid-flag-changed ng-valid-ng-intl-tel-input ng-valid-unique ng-dirty ng-valid-required ng-valid-parse&quot;]/div[@class=&quot;fg-edit row form-group pos-rel ng-valid ng-isolate-scope ng-valid-pattern ng-valid-minlength ng-valid-maxlength ng-valid-flag-changed ng-valid-ng-intl-tel-input ng-valid-unique ng-dirty ng-valid-required ng-valid-parse&quot;]/div[@class=&quot;col-sm-8&quot;]/div[@class=&quot;fg-form&quot;]/div[@class=&quot;fg-edit-canvas&quot;]/fieldset[1]/div[@class=&quot;fg-edit-canvas-area&quot;]/div[@class=&quot;ng-scope&quot;]/div[2]/div[@class=&quot;fg-field fg-field-selectlist fg-edit-canvas-field&quot;]/div[@class=&quot;fg-field-properties-container ng-isolate-scope visible&quot;]/div[@class=&quot;fg-field-properties&quot;]/div[@class=&quot;ng-valid ng-valid-unique ng-valid-required ng-dirty ng-valid-parse&quot;]/div[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;fg-tabs tabbable&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;fg-tabs-pane&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/table[@class=&quot;table-field-options ng-scope&quot;]/tbody[1]/tr[@class=&quot;ng-pristine ng-valid ng-scope ng-valid-required&quot;]/td[2]/input[@class=&quot;form-control ng-pristine ng-untouched ng-valid ng-valid-required&quot;]</value>
      <webElementGuid>26642b47-c003-439e-91ac-00335c2c7c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb6c6b81-701e-42c6-ac7c-092b02fb7491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>11e6c4f6-0d24-4cd3-b813-e23a3f6c8e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>optionValue</value>
      <webElementGuid>e29d6a53-7a9c-45d3-b08d-10684d75c98c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>option.value</value>
      <webElementGuid>4e91ba95-67b0-4d3f-8f5c-e0962b6f9f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b6fe2ec0-fc9a-46fe-87d1-b53d8aa8107c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-valid ng-valid-required</value>
      <webElementGuid>01423a33-91fc-4cbe-8090-0cc7200eba99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>27869436-0119-4e57-969f-dd5fb90aa7c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapseFields&quot;)/div[@class=&quot;panel-body bg-grey&quot;]/div[@class=&quot;needs-some-more-space ng-isolate-scope&quot;]/div[@class=&quot;fg-tabs tabbable&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;fg-tabs-pane&quot;]/div[@class=&quot;ng-scope&quot;]/form[@class=&quot;form-horizontal ng-valid ng-scope ng-valid-pattern ng-valid-minlength ng-valid-maxlength ng-valid-flag-changed ng-valid-ng-intl-tel-input ng-valid-unique ng-dirty ng-valid-required ng-valid-parse&quot;]/div[@class=&quot;fg-edit row form-group pos-rel ng-valid ng-isolate-scope ng-valid-pattern ng-valid-minlength ng-valid-maxlength ng-valid-flag-changed ng-valid-ng-intl-tel-input ng-valid-unique ng-dirty ng-valid-required ng-valid-parse&quot;]/div[@class=&quot;col-sm-8&quot;]/div[@class=&quot;fg-form&quot;]/div[@class=&quot;fg-edit-canvas&quot;]/fieldset[1]/div[@class=&quot;fg-edit-canvas-area&quot;]/div[@class=&quot;ng-scope&quot;]/div[2]/div[@class=&quot;fg-field fg-field-selectlist fg-edit-canvas-field&quot;]/div[@class=&quot;fg-field-properties-container ng-isolate-scope visible&quot;]/div[@class=&quot;fg-field-properties&quot;]/div[@class=&quot;ng-valid ng-valid-unique ng-valid-required ng-dirty ng-valid-parse&quot;]/div[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;fg-tabs tabbable&quot;]/div[@class=&quot;tab-content&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;fg-tabs-pane&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/table[@class=&quot;table-field-options ng-scope&quot;]/tbody[1]/tr[@class=&quot;ng-pristine ng-valid ng-scope ng-valid-required&quot;]/td[2]/input[@class=&quot;form-control ng-pristine ng-untouched ng-valid ng-valid-required&quot;]</value>
      <webElementGuid>02a4e430-994d-423a-8c21-966ce0edaad0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='optionValue']</value>
      <webElementGuid>a6874dd4-7cfc-4a3b-bd05-f6c973986ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseFields']/div/div/div/div/div/div/div/form/div/div/div/div/fieldset/div/div[5]/div[2]/div/div[3]/div/div/div/div/div/div/div[2]/div/div/div[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>57fc8d7e-1fd7-40b3-8479-687e899ed3a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>79db271c-b7c0-43b7-8ead-a47f0bf1faa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'optionValue']</value>
      <webElementGuid>a5e13d82-956e-49aa-8402-ae9f5d2527ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='optionValue'])[3]</value>
      <webElementGuid>1d5854cf-4a80-4a93-a1d1-61c93027c06a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseFields']/div/div/div/div/div/div/div/form/div/div/div/div/fieldset/div/div[6]/div[2]/div/div[3]/div/div/div/div/div/div/div[2]/div/div/div[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>ea0ac95f-9c1e-4679-a8d4-54a7a807cb9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div[3]/div/div/div/div/div/div/div[2]/div/div/div[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>986c9f68-60f3-49ea-a0f6-1ae2115b445e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
