<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Management of Companies and Enterprises</name>
   <tag></tag>
   <elementGuidId>d4b07e86-af70-4f94-b823-cae1e3ec54a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.multiselect-dropdown-optgroup-option.ng-binding.ng-scope.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='contentMainDiv']/create-template/div[2]/div/div[2]/div/div/div/nav/form/div/ul/li[2]/div/oi-multiselect/div[2]/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>f2a94cb5-cd3b-4dd0-a2e6-a4248562cf9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>multiselect-dropdown-optgroup-option ng-binding ng-scope active</value>
      <webElementGuid>93b7c9e7-7eaf-430d-9801-8dd3236d6e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-repeat</name>
      <type>Main</type>
      <value>option in options</value>
      <webElementGuid>bc939e76-4da1-48b9-84f4-f726322881db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'active': selectorPosition === groupPos[group] + $index}</value>
      <webElementGuid>9fd7ca11-b7ed-48e2-8986-3f7e2d4d56c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>addItem(option)</value>
      <webElementGuid>5e9082b6-d25e-4bea-9eb2-70a0d6278db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-mouseenter</name>
      <type>Main</type>
      <value>setSelection(groupPos[group] + $index)</value>
      <webElementGuid>08cba6a3-5c58-4e60-8802-610be8c97097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind-html</name>
      <type>Main</type>
      <value>getDropdownLabel(option)</value>
      <webElementGuid>ed358e74-298d-4f2b-9d79-5acb8709b283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Management of Companies and Enterprises</value>
      <webElementGuid>da59899e-a7e0-4443-a9ce-37e5da9c45e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentMainDiv&quot;)/create-template[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;container-main canvas&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;margin-sm&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;row&quot;]/nav[@class=&quot;navbar navbar-default microsite-nav&quot;]/form[@class=&quot;canvas-form-m ng-invalid ng-invalid-required ng-valid-maxlength ng-dirty ng-valid-parse&quot;]/div[@class=&quot;canvas-nav template-canvas&quot;]/ul[@class=&quot;nav navbar-nav&quot;]/li[@class=&quot;template job-industry&quot;]/div[@class=&quot;col-sm-12&quot;]/oi-multiselect[@class=&quot;ng-pristine ng-untouched ng-isolate-scope ng-invalid ng-invalid-required&quot;]/div[@class=&quot;multiselect-dropdown&quot;]/ul[@class=&quot;multiselect-dropdown-optgroup ng-scope&quot;]/li[@class=&quot;multiselect-dropdown-optgroup-option ng-binding ng-scope active&quot;]</value>
      <webElementGuid>b6497bdf-408e-4143-827f-67047781e362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>0f90ae99-6deb-45c8-a126-680a6dc8886b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>multiselect-dropdown-optgroup-option ng-binding ng-scope active</value>
      <webElementGuid>7f1a9e15-f040-4863-8f8e-ee009e8a0472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-repeat</name>
      <type>Main</type>
      <value>option in options</value>
      <webElementGuid>5cc0f15f-fbc0-402a-a715-16ecc966212d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'active': selectorPosition === groupPos[group] + $index}</value>
      <webElementGuid>fade99bd-3814-44ce-a3e3-c603222bd3a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>addItem(option)</value>
      <webElementGuid>5308e861-1661-4c7b-974c-5d2ad619bae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-mouseenter</name>
      <type>Main</type>
      <value>setSelection(groupPos[group] + $index)</value>
      <webElementGuid>ff0c1bbb-76a5-421d-b5b1-408492733a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind-html</name>
      <type>Main</type>
      <value>getDropdownLabel(option)</value>
      <webElementGuid>a8105570-debd-4aff-8155-464c4d641a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Management of Companies and Enterprises</value>
      <webElementGuid>56bbd431-3a09-4a2a-a201-82528deb4018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentMainDiv&quot;)/create-template[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;container-main canvas&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;margin-sm&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;row&quot;]/nav[@class=&quot;navbar navbar-default microsite-nav&quot;]/form[@class=&quot;canvas-form-m ng-invalid ng-invalid-required ng-valid-maxlength ng-dirty ng-valid-parse&quot;]/div[@class=&quot;canvas-nav template-canvas&quot;]/ul[@class=&quot;nav navbar-nav&quot;]/li[@class=&quot;template job-industry&quot;]/div[@class=&quot;col-sm-12&quot;]/oi-multiselect[@class=&quot;ng-pristine ng-untouched ng-isolate-scope ng-invalid ng-invalid-required&quot;]/div[@class=&quot;multiselect-dropdown&quot;]/ul[@class=&quot;multiselect-dropdown-optgroup ng-scope&quot;]/li[@class=&quot;multiselect-dropdown-optgroup-option ng-binding ng-scope active&quot;]</value>
      <webElementGuid>5f01c39c-9ae1-4522-921d-a48639039204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2ba8b083-3bcc-4aa3-9f77-271e912ac86a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>multiselect-dropdown-optgroup-option ng-binding ng-scope active</value>
      <webElementGuid>3edab476-c238-437a-9cdb-ba2ef0e4f78c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-repeat</name>
      <type>Main</type>
      <value>option in options</value>
      <webElementGuid>0f76fc07-00f2-419a-8317-f34d55150262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'active': selectorPosition === groupPos[group] + $index}</value>
      <webElementGuid>bc48e7a3-bf80-4d5f-ad35-d2ed91fa083e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>addItem(option)</value>
      <webElementGuid>983dbd6b-4705-4433-ab03-a17229190161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-mouseenter</name>
      <type>Main</type>
      <value>setSelection(groupPos[group] + $index)</value>
      <webElementGuid>501160b3-ef92-4d3c-9365-77db4e4ac920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind-html</name>
      <type>Main</type>
      <value>getDropdownLabel(option)</value>
      <webElementGuid>70e0bd66-b46d-4f26-8715-ed8aee231a7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Management of Companies and Enterprises</value>
      <webElementGuid>dbde12fa-21aa-4c3a-97a7-6b5b9b247d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentMainDiv&quot;)/create-template[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;container-main canvas&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;margin-sm&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;row&quot;]/nav[@class=&quot;navbar navbar-default microsite-nav&quot;]/form[@class=&quot;canvas-form-m ng-invalid ng-invalid-required ng-valid-maxlength ng-dirty ng-valid-parse&quot;]/div[@class=&quot;canvas-nav template-canvas&quot;]/ul[@class=&quot;nav navbar-nav&quot;]/li[@class=&quot;template job-industry&quot;]/div[@class=&quot;col-sm-12&quot;]/oi-multiselect[@class=&quot;ng-pristine ng-untouched ng-isolate-scope ng-invalid ng-invalid-required&quot;]/div[@class=&quot;multiselect-dropdown&quot;]/ul[@class=&quot;multiselect-dropdown-optgroup ng-scope&quot;]/li[@class=&quot;multiselect-dropdown-optgroup-option ng-binding ng-scope active&quot;]</value>
      <webElementGuid>307b9ade-29a3-47cb-9490-d215ac040b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>1aabacbe-f1c4-4846-9058-b891613da4b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>multiselect-dropdown-optgroup-option ng-binding ng-scope active</value>
      <webElementGuid>d38b67b7-6228-4787-9797-b3c4765082a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-repeat</name>
      <type>Main</type>
      <value>option in options</value>
      <webElementGuid>b4248c8a-2e9a-4d01-9b8f-91be9846a324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'active': selectorPosition === groupPos[group] + $index}</value>
      <webElementGuid>154d7fb3-cb26-48e8-8e52-384f07ad2ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>addItem(option)</value>
      <webElementGuid>23881a1d-46aa-4305-a218-8e422a04b4e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-mouseenter</name>
      <type>Main</type>
      <value>setSelection(groupPos[group] + $index)</value>
      <webElementGuid>d1d9d06a-bc0e-4161-8d21-9fe16bee64bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind-html</name>
      <type>Main</type>
      <value>getDropdownLabel(option)</value>
      <webElementGuid>88038792-a32c-4083-8b15-7a8fb6cc6879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Management of Companies and Enterprises</value>
      <webElementGuid>376a924a-5b66-4d75-827d-f2eb5bedd9a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentMainDiv&quot;)/create-template[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;container-main canvas&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;margin-sm&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;row&quot;]/nav[@class=&quot;navbar navbar-default microsite-nav&quot;]/form[@class=&quot;canvas-form-m ng-invalid ng-invalid-required ng-valid-maxlength ng-dirty ng-valid-parse&quot;]/div[@class=&quot;canvas-nav template-canvas&quot;]/ul[@class=&quot;nav navbar-nav&quot;]/li[@class=&quot;template job-industry&quot;]/div[@class=&quot;col-sm-12&quot;]/oi-multiselect[@class=&quot;ng-pristine ng-untouched ng-isolate-scope ng-invalid ng-invalid-required&quot;]/div[@class=&quot;multiselect-dropdown&quot;]/ul[@class=&quot;multiselect-dropdown-optgroup ng-scope&quot;]/li[@class=&quot;multiselect-dropdown-optgroup-option ng-binding ng-scope active&quot;]</value>
      <webElementGuid>63c22ec1-0001-4d77-b778-cbddbaf7b404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>928e69c9-1b0c-41b7-80e8-2715a4f47764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>multiselect-dropdown-optgroup-option ng-binding ng-scope active</value>
      <webElementGuid>976fb792-204c-45e0-9e30-61a31c977207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-repeat</name>
      <type>Main</type>
      <value>option in options</value>
      <webElementGuid>ee445ff6-f135-4f53-9960-4ad7a8527268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'active': selectorPosition === groupPos[group] + $index}</value>
      <webElementGuid>1123f93e-eb59-49a6-8f6c-cf3c6b7f9e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>addItem(option)</value>
      <webElementGuid>6044e642-c5c0-4fcf-88c0-636cccddd068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-mouseenter</name>
      <type>Main</type>
      <value>setSelection(groupPos[group] + $index)</value>
      <webElementGuid>ae6c43dd-357a-4e05-b8e4-cd41c75dbb7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind-html</name>
      <type>Main</type>
      <value>getDropdownLabel(option)</value>
      <webElementGuid>0d30db93-11df-4251-9709-d8f85e957133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Management of Companies and Enterprises</value>
      <webElementGuid>4cb1d5ad-91e0-4b9f-9d56-a1d413a995a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentMainDiv&quot;)/create-template[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;container-main canvas&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;margin-sm&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;row&quot;]/nav[@class=&quot;navbar navbar-default microsite-nav&quot;]/form[@class=&quot;canvas-form-m ng-invalid ng-invalid-required ng-valid-maxlength ng-dirty ng-valid-parse&quot;]/div[@class=&quot;canvas-nav template-canvas&quot;]/ul[@class=&quot;nav navbar-nav&quot;]/li[@class=&quot;template job-industry&quot;]/div[@class=&quot;col-sm-12&quot;]/oi-multiselect[@class=&quot;ng-pristine ng-untouched ng-isolate-scope ng-invalid ng-invalid-required&quot;]/div[@class=&quot;multiselect-dropdown&quot;]/ul[@class=&quot;multiselect-dropdown-optgroup ng-scope&quot;]/li[@class=&quot;multiselect-dropdown-optgroup-option ng-binding ng-scope active&quot;]</value>
      <webElementGuid>5504e005-a2e6-4c4c-99e2-a702d53b48fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>360989a7-880a-4b18-aca9-65f6e097b19b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>multiselect-dropdown-optgroup-option ng-binding ng-scope active</value>
      <webElementGuid>18140e69-1db7-4232-8960-898b142d8e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-repeat</name>
      <type>Main</type>
      <value>option in options</value>
      <webElementGuid>649b9667-6089-424f-9e6a-d92d05af7937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'active': selectorPosition === groupPos[group] + $index}</value>
      <webElementGuid>333d7173-25c2-48aa-916c-84818d16a55b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>addItem(option)</value>
      <webElementGuid>ceeb1319-90e8-44d8-a3f5-921cc253c496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-mouseenter</name>
      <type>Main</type>
      <value>setSelection(groupPos[group] + $index)</value>
      <webElementGuid>64b7cca9-f488-44aa-9d19-a8231aa9e22e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind-html</name>
      <type>Main</type>
      <value>getDropdownLabel(option)</value>
      <webElementGuid>1ad156cd-d27a-42f5-be50-be8c340f54de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Management of Companies and Enterprises</value>
      <webElementGuid>0d9ecd91-3539-472f-b84e-6f66b4913031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentMainDiv&quot;)/create-template[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;container-main canvas&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;margin-sm&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;row&quot;]/nav[@class=&quot;navbar navbar-default microsite-nav&quot;]/form[@class=&quot;canvas-form-m ng-invalid ng-invalid-required ng-valid-maxlength ng-dirty ng-valid-parse&quot;]/div[@class=&quot;canvas-nav template-canvas&quot;]/ul[@class=&quot;nav navbar-nav&quot;]/li[@class=&quot;template job-industry&quot;]/div[@class=&quot;col-sm-12&quot;]/oi-multiselect[@class=&quot;ng-pristine ng-untouched ng-isolate-scope ng-invalid ng-invalid-required&quot;]/div[@class=&quot;multiselect-dropdown&quot;]/ul[@class=&quot;multiselect-dropdown-optgroup ng-scope&quot;]/li[@class=&quot;multiselect-dropdown-optgroup-option ng-binding ng-scope active&quot;]</value>
      <webElementGuid>4d202b51-2f8b-409d-80ff-f5d37f782d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>116dcf50-ad37-45d0-83dc-2478d823a020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>multiselect-dropdown-optgroup-option ng-binding ng-scope active</value>
      <webElementGuid>68a6e33b-f928-4db5-89fc-d43b2b2c41b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-repeat</name>
      <type>Main</type>
      <value>option in options</value>
      <webElementGuid>d3f74f3b-b88e-4d01-8645-739ce3aac752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'active': selectorPosition === groupPos[group] + $index}</value>
      <webElementGuid>cfbfd679-6dae-48cf-8ea9-4fb527713818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>addItem(option)</value>
      <webElementGuid>03e60faf-54e1-4278-8f59-00c7826282de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-mouseenter</name>
      <type>Main</type>
      <value>setSelection(groupPos[group] + $index)</value>
      <webElementGuid>f11a9c71-85b4-44b9-b77f-8566b6054845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind-html</name>
      <type>Main</type>
      <value>getDropdownLabel(option)</value>
      <webElementGuid>9baacfbc-1805-4c38-9a58-fe13c83547da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Management of Companies and Enterprises</value>
      <webElementGuid>6e7e741e-5e5a-4473-9c0e-11cbda62180f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentMainDiv&quot;)/create-template[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;container-main canvas&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;margin-sm&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;row&quot;]/nav[@class=&quot;navbar navbar-default microsite-nav&quot;]/form[@class=&quot;canvas-form-m ng-invalid ng-invalid-required ng-valid-maxlength ng-dirty ng-valid-parse&quot;]/div[@class=&quot;canvas-nav template-canvas&quot;]/ul[@class=&quot;nav navbar-nav&quot;]/li[@class=&quot;template job-industry&quot;]/div[@class=&quot;col-sm-12&quot;]/oi-multiselect[@class=&quot;ng-pristine ng-untouched ng-isolate-scope ng-invalid ng-invalid-required&quot;]/div[@class=&quot;multiselect-dropdown&quot;]/ul[@class=&quot;multiselect-dropdown-optgroup ng-scope&quot;]/li[@class=&quot;multiselect-dropdown-optgroup-option ng-binding ng-scope active&quot;]</value>
      <webElementGuid>32f0ff96-63e5-4bdd-a10c-b9d0e503dc7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>8ec33a81-bcae-4789-96cb-9057149e0294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>multiselect-dropdown-optgroup-option ng-binding ng-scope active</value>
      <webElementGuid>8101ab45-a761-4a78-8cff-ca536d56511a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-repeat</name>
      <type>Main</type>
      <value>option in options</value>
      <webElementGuid>29694c1a-305e-47b4-95a2-28960e51f3ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{'active': selectorPosition === groupPos[group] + $index}</value>
      <webElementGuid>62fec108-1ed5-4750-8510-243d7aa14cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>addItem(option)</value>
      <webElementGuid>745c371e-bb49-4472-b247-5e64603cbf23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-mouseenter</name>
      <type>Main</type>
      <value>setSelection(groupPos[group] + $index)</value>
      <webElementGuid>9195d9fb-7af8-4863-b961-444590ccc02b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind-html</name>
      <type>Main</type>
      <value>getDropdownLabel(option)</value>
      <webElementGuid>85d9b900-ff93-4d46-b495-b4b73f28ce59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Management of Companies and Enterprises</value>
      <webElementGuid>a6ab3d64-026e-4140-81cb-7f08816b0973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentMainDiv&quot;)/create-template[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;container-main canvas&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;margin-sm&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;row&quot;]/nav[@class=&quot;navbar navbar-default microsite-nav&quot;]/form[@class=&quot;canvas-form-m ng-invalid ng-invalid-required ng-valid-maxlength ng-dirty ng-valid-parse&quot;]/div[@class=&quot;canvas-nav template-canvas&quot;]/ul[@class=&quot;nav navbar-nav&quot;]/li[@class=&quot;template job-industry&quot;]/div[@class=&quot;col-sm-12&quot;]/oi-multiselect[@class=&quot;ng-pristine ng-untouched ng-isolate-scope ng-invalid ng-invalid-required&quot;]/div[@class=&quot;multiselect-dropdown&quot;]/ul[@class=&quot;multiselect-dropdown-optgroup ng-scope&quot;]/li[@class=&quot;multiselect-dropdown-optgroup-option ng-binding ng-scope active&quot;]</value>
      <webElementGuid>0f1cfab7-72be-4380-a6df-85b81cadb0d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentMainDiv']/create-template/div[2]/div/div[2]/div/div/div/nav/form/div/ul/li[2]/div/oi-multiselect/div[2]/ul/li</value>
      <webElementGuid>7905f59b-4013-4af0-8b12-675d0bd8fabd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::li[3]</value>
      <webElementGuid>57003dd1-5208-4595-a78e-418cf1c7b3b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hospitality &amp; Consumer Services'])[1]/preceding::li[1]</value>
      <webElementGuid>2fb9d7a0-8aaa-49d7-bdd9-dd2202d64ece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Government &amp; Public Administration'])[1]/preceding::li[2]</value>
      <webElementGuid>c1be783b-f2fd-4f80-a27c-6912e5be17ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li</value>
      <webElementGuid>9a11f656-8323-4efc-938b-4dffbbdb246c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Management of Companies and Enterprises' or . = 'Management of Companies and Enterprises')]</value>
      <webElementGuid>0e7063e7-1ebc-4dda-a1e5-89bf646f761d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
