<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_d</name>
   <tag></tag>
   <elementGuidId>85175eb7-86e9-4522-a2fa-ce5b5aacfb8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='contentMainDiv']/create-template/div[2]/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/div[2]/ol/li/ol/li/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ng-scope.ng-binding.color-blue-secondary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6e9b5c19-4fb0-4757-adf1-ac2c57016aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vm.selectPage(page,this)</value>
      <webElementGuid>0152cf74-4254-42eb-a582-b023cc581d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>vm.selectedPage.pageName==page.pageName?'color-blue-secondary':''</value>
      <webElementGuid>8938170f-9303-4e52-bb7d-86f23ee61b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>edb7c2e7-1279-4e06-9af9-218cfbddccdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>d</value>
      <webElementGuid>608dcecd-ec24-4c13-9386-9b600b7c70b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-animation</name>
      <type>Main</type>
      <value>am-flip-x</value>
      <webElementGuid>267e2963-b19a-4768-a3bb-8335f5bef649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-scope ng-binding color-blue-secondary</value>
      <webElementGuid>b7b331e8-2adb-4bda-b1e7-4684d690fd4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> d</value>
      <webElementGuid>9a0a9573-e682-4d79-8956-2d1611090920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentMainDiv&quot;)/create-template[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;container-main canvas&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;margin-sm&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;microsite-main mtop&quot;]/div[@class=&quot;col-lg-2 sidebar col-lg-2-canvas&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 padding-short&quot;]/div[@class=&quot;panel-default margin-none&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;map-list ng-scope&quot;]/div[@class=&quot;ng-scope angular-ui-tree&quot;]/ol[@class=&quot;map-list-inline remove-numbering ng-pristine ng-untouched ng-valid ng-scope angular-ui-tree-nodes&quot;]/li[@class=&quot;documentItem ng-scope angular-ui-tree-node&quot;]/ol[@class=&quot;remove-numbering ng-pristine ng-untouched ng-valid ng-scope angular-ui-tree-nodes&quot;]/li[@class=&quot;ng-scope angular-ui-tree-node&quot;]/div[@class=&quot;ng-scope angular-ui-tree-handle&quot;]/span[@class=&quot;ng-scope ng-binding color-blue-secondary&quot;]</value>
      <webElementGuid>2d31bf8e-23f1-4604-8768-7eaa472cacec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentMainDiv']/create-template/div[2]/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/div[2]/ol/li/ol/li/div/span</value>
      <webElementGuid>2c32b75f-12c3-488a-a518-498d2137154e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='c'])[1]/following::span[4]</value>
      <webElementGuid>9205cb9d-bf34-4040-9dec-4fecf65369f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location Selector Form'])[1]/following::span[6]</value>
      <webElementGuid>87da786f-2ce6-47e2-baf6-32307e16d9a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='d'])[2]/preceding::span[1]</value>
      <webElementGuid>47d798a8-2cb8-4d8a-992a-d02768b6de71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page Style'])[1]/preceding::span[3]</value>
      <webElementGuid>924bf1d4-c757-4d67-a4d0-4d9a896eee1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='d']/parent::*</value>
      <webElementGuid>2bc61631-1013-4f6e-8759-633a32d6f572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ol/li/div/span</value>
      <webElementGuid>065ad62f-ad7b-4f49-8561-59134c7ea392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' d' or . = ' d')]</value>
      <webElementGuid>48172b50-0ee9-4327-a0ee-d5fab038a614</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
