<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ApplyButtonLocator</name>
   <tag></tag>
   <elementGuidId>fa461c4e-2115-4044-b87d-9751f1059c8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[ng-click='handleMicrosite(job.microSiteLink)']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
