<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Auto_Software_EnggineerykQF</name>
   <tag></tag>
   <elementGuidId>be2ef7d7-4166-4040-9aa7-c4b44c3ebb6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='campaign_3961']/td[3]/div/span[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.move-icon-dec > a.link-text.link-color-black.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0e590c6d-a769-4162-9367-05653d0d4ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vm.openCampaignInfoDialog(campaign.campaignId,vm)</value>
      <webElementGuid>431c1577-2b17-41a2-80c1-4cd6b7433d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>6be22672-748a-4ec0-ab05-55147a1673f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link-text link-color-black ng-binding</value>
      <webElementGuid>4c4baea3-5f98-498d-b7f5-f7a471697198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#myModal</value>
      <webElementGuid>346c7cca-a00b-4e23-aff4-15b2b961ede8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Auto_Software_EnggineerykQF</value>
      <webElementGuid>7f371086-d1d0-44b1-99b7-d2c59a59f70e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;campaign_3961&quot;)/td[@class=&quot;icon-move&quot;]/div[@class=&quot;campTitle&quot;]/span[@class=&quot;move-icon-dec&quot;]/a[@class=&quot;link-text link-color-black ng-binding&quot;]</value>
      <webElementGuid>5d07b3ff-9917-49b4-92b5-5550cb2bf405</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='campaign_3961']/td[3]/div/span[2]/a</value>
      <webElementGuid>a45c37a0-e2cc-4f36-8d82-f58e8d8a9570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Auto_Software_EnggineerykQF')]</value>
      <webElementGuid>e00c7219-dfaf-4dc4-849c-fbcc13d75822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JOB_3961'])[1]/following::a[1]</value>
      <webElementGuid>b12e35f9-389c-4159-936e-4d3b990cbd23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bot'])[1]/following::a[2]</value>
      <webElementGuid>59bd0ecc-261b-4ed7-be63-d6f74daacac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Boost'])[1]/preceding::a[1]</value>
      <webElementGuid>5a934cfc-68c7-4cc8-9397-42e06d3e5db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable'])[1]/preceding::a[2]</value>
      <webElementGuid>03d10eea-c9c6-47c3-84a9-43c5fa7d69a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[38]</value>
      <webElementGuid>3c150e27-64fa-4247-bd60-48c4388122f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/span[2]/a</value>
      <webElementGuid>fa368ea3-1bc8-4cfc-a836-8b0e31e15c6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Auto_Software_EnggineerykQF' or . = 'Auto_Software_EnggineerykQF')]</value>
      <webElementGuid>25c4058b-2020-4cf7-b094-53dbb8ae8458</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
