<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_httpstestaccount.mobile-recruit.comm0vMkgXVVV</name>
   <tag></tag>
   <elementGuidId>83228cb8-d074-4a6a-afbe-d55d3359923c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='campaignDetailsDialog']/div/div/div[2]/div[2]/div/div/div/div[7]/div/div/p/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.form-control-static > a.link-text.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1d3fb0e5-65be-425d-b1b1-0e79c4b72a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-href</name>
      <type>Main</type>
      <value>https://testaccount.mobile-recruit.com/m/0vMkgXVVV</value>
      <webElementGuid>0fdd99c9-4357-443d-8976-7db308483943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link-text ng-binding</value>
      <webElementGuid>dc640573-23e4-4982-9b65-14008d98a319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>6b9bd406-f404-40c6-8b04-66281ea24118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://testaccount.mobile-recruit.com/m/0vMkgXVVV</value>
      <webElementGuid>d7b223cf-446e-43da-90ec-0fe6edb0dbe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> https://testaccount.mobile-recruit.com/m/0vMkgXVVV </value>
      <webElementGuid>21c34de6-f20c-4e9a-bd47-5b496403c9ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;campaignDetailsDialog&quot;)/div[@class=&quot;modal-dialog modal-large&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body-lg padding10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-8 col-md-8&quot;]/div[@class=&quot;mtop row&quot;]/div[@class=&quot;col-md-8&quot;]/div[@class=&quot;col-lg-12 padding-none ng-scope&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-8&quot;]/p[@class=&quot;form-control-static&quot;]/a[@class=&quot;link-text ng-binding&quot;]</value>
      <webElementGuid>7b080ad5-90bd-4ada-95ce-4b6294ff4722</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='campaignDetailsDialog']/div/div/div[2]/div[2]/div/div/div/div[7]/div/div/p/a</value>
      <webElementGuid>c4b90149-c6b6-47b0-ad82-aa1b4750e1dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'https://testaccount.mobile-recruit.com/m/0vMkgXVVV')]</value>
      <webElementGuid>d623fbcd-d4c7-4f78-8db4-19022bd212fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campaign URL -'])[1]/following::a[1]</value>
      <webElementGuid>fd7fc226-16af-4b0f-9246-2b22f9a3c333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/following::a[1]</value>
      <webElementGuid>e149b840-d45f-4a8e-8497-a327ff8f5411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assignee -'])[1]/preceding::a[1]</value>
      <webElementGuid>9d00749b-870b-4dbb-b6ad-30c626c5633c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rathi gaurav'])[1]/preceding::a[1]</value>
      <webElementGuid>f4c50ada-759c-4381-9369-0834b9f3a3ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='https://testaccount.mobile-recruit.com/m/0vMkgXVVV']/parent::*</value>
      <webElementGuid>aa041270-9e39-470c-b752-b773ebc9cb6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://testaccount.mobile-recruit.com/m/0vMkgXVVV')]</value>
      <webElementGuid>7d9ad9c3-3a0f-449c-9ea7-a2a9af04f760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>77758aa1-7259-4b09-bbf8-4e0ec931a52f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://testaccount.mobile-recruit.com/m/0vMkgXVVV' and (text() = ' https://testaccount.mobile-recruit.com/m/0vMkgXVVV ' or . = ' https://testaccount.mobile-recruit.com/m/0vMkgXVVV ')]</value>
      <webElementGuid>9a08b326-72f5-470a-8f13-242c21bad39b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
