<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_You have successfully Registered</name>
   <tag></tag>
   <elementGuidId>c053d3c9-c7fd-46e3-ab16-1fb9f2292709</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='contentMainDiv']/candidate-register-thanks/div/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>627919e6-442a-412a-b486-a3e54f23df81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You have successfully Registered!</value>
      <webElementGuid>d16ceb5c-2b94-42dd-8318-e940b01da155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentMainDiv&quot;)/candidate-register-thanks[@class=&quot;ng-scope&quot;]/div[@class=&quot;thanks-register&quot;]/h3[1]</value>
      <webElementGuid>54c8cf1f-e3be-468b-a5e4-c9ee1996d070</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentMainDiv']/candidate-register-thanks/div/h3</value>
      <webElementGuid>e7a2638b-04e7-4c69-8870-3670d4a336d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='You have successfully Registered!']/parent::*</value>
      <webElementGuid>fd9d132b-7f6e-44b7-927c-e7848e499fd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>9cb446a5-6d4d-4aa7-8d50-409bd3e35948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'You have successfully Registered!' or . = 'You have successfully Registered!')]</value>
      <webElementGuid>a9acf227-c17b-4457-b09f-f0eba81c4f34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
