<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Job Title_jobTitle</name>
   <tag></tag>
   <elementGuidId>12e407e1-187a-44c9-bd7a-d70675e73911</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jobTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jobTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>899f8ce7-0a75-40d1-a57f-10638f074004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jobTitle</value>
      <webElementGuid>b08e5670-95ea-4503-ad0b-ca5c873dfd1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-invalid ng-invalid-required</value>
      <webElementGuid>a8b3c29b-b6a1-4d88-baac-0710b3e4b488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a0e99da0-95b6-43e6-a445-dcc32d789fc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jobTitle</value>
      <webElementGuid>63b2b661-dd5c-4875-a94c-ff8aa2f089cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$ctrl.searchCriteria.jobTitle</value>
      <webElementGuid>132494ff-0ce3-4b4c-b7be-3dc5c3674f03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Job Title</value>
      <webElementGuid>c5a763a6-a48c-441c-bda1-eeda3f033b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-autoclose</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>780e18cf-c2de-49f0-963e-f40c93d401d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>bottom-right</value>
      <webElementGuid>279e1449-e28f-44a0-a979-bb57b7d6d226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobTitle&quot;)</value>
      <webElementGuid>59d1f3d2-5a64-4047-a0ac-aa20bf7dbf88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jobTitle']</value>
      <webElementGuid>84224377-e134-498b-9179-4f8f4c922982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='searchFilters']/div/filters/div/form/div[4]/div/input</value>
      <webElementGuid>6ef10399-7be7-4b63-9692-fec01d9ee100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>fae20cde-bcf0-4977-a82f-c953e4f61c6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'jobTitle' and @type = 'text' and @name = 'jobTitle' and @placeholder = 'Job Title']</value>
      <webElementGuid>4a8dd2a8-fb5e-44f9-8bf0-3ab27cf89739</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
