<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Software_Testing_geuT</name>
   <tag></tag>
   <elementGuidId>74882f01-48e7-4b45-831f-4cee5d6ca465</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='campaign_3938']/td[3]/div/span[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.move-icon-dec > a.link-text.link-color-black.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>68b10cec-957e-441a-9d5b-4934268e75dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vm.openCampaignInfoDialog(campaign.campaignId,vm)</value>
      <webElementGuid>6dc85c05-70bc-46d2-b234-b239c97679d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>c178ce8f-ca8d-4115-9e25-ed06cff14c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link-text link-color-black ng-binding</value>
      <webElementGuid>b55556b6-a2ee-484f-8f0f-fb675c889849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#myModal</value>
      <webElementGuid>9b1a83a0-1700-49e7-a199-cf90042397e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Software_Testing_geuT</value>
      <webElementGuid>2184c913-ddd6-45ae-9f6d-bd086ab25a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;campaign_3938&quot;)/td[@class=&quot;icon-move&quot;]/div[@class=&quot;campTitle&quot;]/span[@class=&quot;move-icon-dec&quot;]/a[@class=&quot;link-text link-color-black ng-binding&quot;]</value>
      <webElementGuid>4589355e-5f8c-4052-842a-ca7536d687ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='campaign_3938']/td[3]/div/span[2]/a</value>
      <webElementGuid>d4f47115-526c-4bb0-b523-9cc270a7a6f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Software_Testing_geuT')]</value>
      <webElementGuid>ca57223b-37f7-46db-9aa3-cc219483b03c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JOB_3938'])[1]/following::a[1]</value>
      <webElementGuid>c91daf24-0bbd-47ba-b288-e9c285745244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bot'])[1]/following::a[2]</value>
      <webElementGuid>9d10bdf2-e9cc-4a12-ae23-6ad314b3b7e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Boost'])[1]/preceding::a[2]</value>
      <webElementGuid>ad1fd4ec-87e2-4d4c-ac9b-fd9cc4794093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable'])[1]/preceding::a[3]</value>
      <webElementGuid>36bbcf22-1592-40e3-8d01-58cf29d9945f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[39]</value>
      <webElementGuid>f41ab11e-6e07-42b1-b570-4cd39e36de94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/span[2]/a</value>
      <webElementGuid>63fa37da-c6bb-4a2e-a734-0a89f3cc5d76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Software_Testing_geuT' or . = 'Software_Testing_geuT')]</value>
      <webElementGuid>00aee2f2-6f4f-4998-96dd-89c13308de33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
