<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Software_Testing_geuT</name>
   <tag></tag>
   <elementGuidId>9cffb588-5fa4-4356-8014-8b3d50684db8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span[class='move-icon-dec']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='campaign_3938']/td[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a2fc9b49-5ce9-46bb-a0a9-d718536d4475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>campTitle</value>
      <webElementGuid>59663730-607b-4067-9d4f-88cbfa404588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>     Software_Testing_geuT  </value>
      <webElementGuid>d2e47a44-79d0-4b44-99d2-55c118e9c56b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;campaign_3938&quot;)/td[@class=&quot;icon-move&quot;]/div[@class=&quot;campTitle&quot;]</value>
      <webElementGuid>4295c298-94de-4622-8d6f-03e2630495a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='campaign_3938']/td[3]/div</value>
      <webElementGuid>b6f673d0-8b36-4d86-9bda-35715c7967f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JOB_3938'])[1]/following::div[1]</value>
      <webElementGuid>3eb66cc7-d0dd-491a-8f03-1a4f0ba9a533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bot'])[1]/following::div[1]</value>
      <webElementGuid>3523df2d-be87-4415-a128-0086f71fa7ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Boost'])[1]/preceding::div[2]</value>
      <webElementGuid>fcbc204f-4d46-4ef1-904d-d0583e0b751b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div</value>
      <webElementGuid>572c06f5-a9e9-4986-a382-f3ab8f58b3ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '     Software_Testing_geuT  ' or . = '     Software_Testing_geuT  ')]</value>
      <webElementGuid>9d53c2ad-5722-4465-95ee-a19b1aaaa7b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
