<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>micrositeLinkLocator</name>
   <tag></tag>
   <elementGuidId>7b29a7c3-4d6e-4f74-bda4-cfe5f0a18ccd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='campaignDetailsDialog']/div/div/div[2]/div[2]/div/div/div/div[7]/div/div/p/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@ng-href = 'https://testaccount.mobile-recruit.com' and @class = 'link-text ng-binding' and @href = 'https://testaccount.mobile-recruit.com' and (text() = ' https://testaccount.mobile-recruit.com' or . = ' https://testaccount.mobile-recruit.com')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(7) .link-text.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>81744a59-1b11-43ad-ab6b-8b60ac7c1511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-href</name>
      <type>Main</type>
      <value>https://testaccount.mobile-recruit.com</value>
      <webElementGuid>314c68dd-145d-4e2d-b414-41cc1f7ac926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link-text ng-binding</value>
      <webElementGuid>ef5d61dd-57ea-44c9-add9-f0a8e6306ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>bef8c3e8-65ea-45f0-befe-3b5d37adcf7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://testaccount.mobile-recruit.com</value>
      <webElementGuid>c367988b-9c1f-456c-9ad0-530fdad8dfb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> https://testaccount.mobile-recruit.com</value>
      <webElementGuid>a0afb490-5950-4deb-886a-1a5e763ac409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;campaignDetailsDialog&quot;)/div[@class=&quot;modal-dialog modal-large&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body-lg padding10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-8 col-md-8&quot;]/div[@class=&quot;mtop row&quot;]/div[@class=&quot;col-md-8&quot;]/div[@class=&quot;col-lg-12 padding-none ng-scope&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-8&quot;]/p[@class=&quot;form-control-static&quot;]/a[@class=&quot;link-text ng-binding&quot;]</value>
      <webElementGuid>d4e37853-0c14-496e-b152-b8484b435609</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='campaignDetailsDialog']/div/div/div[2]/div[2]/div/div/div/div[7]/div/div/p/a</value>
      <webElementGuid>9c96e6b5-2fb5-421c-869e-20382fa8fbcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'https://testaccount.mobile-recruit.com/m/DxNmgVVV')]</value>
      <webElementGuid>37b091a6-3b9e-4ddc-b2d0-d426d110584d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campaign URL -'])[1]/following::a[1]</value>
      <webElementGuid>9716cfc6-b2dd-4757-a2b4-7794176f8fd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/following::a[1]</value>
      <webElementGuid>ba65b973-1ecf-43db-8eee-b885904704a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assignee -'])[1]/preceding::a[1]</value>
      <webElementGuid>a852312e-3efa-4ba1-bb82-0befd1aa9704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rathi gaurav'])[1]/preceding::a[1]</value>
      <webElementGuid>8d2c4eec-cf23-4820-8d6e-eaeb37415659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='https://testaccount.mobile-recruit.com/m/DxNmgVVV']/parent::*</value>
      <webElementGuid>a251212b-7b82-43fb-9596-ffceb60aa25b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://testaccount.mobile-recruit.com/m/DxNmgVVV')]</value>
      <webElementGuid>2291efe2-1fee-4967-b2ee-536e3f20207e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>dfb85d46-337f-418f-9ca1-f53de20a548d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://testaccount.mobile-recruit.com/m/DxNmgVVV' and (text() = ' https://testaccount.mobile-recruit.com/m/DxNmgVVV ' or . = ' https://testaccount.mobile-recruit.com/m/DxNmgVVV ')]</value>
      <webElementGuid>509b1749-61f5-4085-bead-c9421c1a7899</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
