<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__termsConditions</name>
   <tag></tag>
   <elementGuidId>9f83ea32-ea6d-454e-b751-16038dbf64cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;termsConditions&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='termsConditions']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af22adeb-5cdc-469b-beab-492e7dc2c88d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f84c7129-2d22-4fcd-abe8-9bdfad486845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-auto</value>
      <webElementGuid>c3849597-b812-4162-9288-6e66f5916ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>termsConditions</value>
      <webElementGuid>e16ecb3b-3355-4787-a8d8-0dcc3c216b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;login&quot;]/div[@class=&quot;wrapper wrapper-login&quot;]/div[@class=&quot;container container-signup login-signup-container&quot;]/div[@class=&quot;login-form&quot;]/form[@class=&quot;d-flex flex-wrap&quot;]/div[@class=&quot;align-content-between flex-column form-sub m-0 row&quot;]/div[@class=&quot;d-flex&quot;]/input[@class=&quot;m-auto&quot;]</value>
      <webElementGuid>3e578d0d-77c5-4f66-8e01-9d7cf688023a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='termsConditions']</value>
      <webElementGuid>52e1c930-d2f0-4c1a-add5-297ff3458c90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/form/div[7]/div/input</value>
      <webElementGuid>d83b9b45-d514-410c-9639-93eb1c8b913a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>6bb414c5-1c56-4150-9226-bd5b812f297f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'termsConditions']</value>
      <webElementGuid>dbd7869f-4e51-48f0-9e79-a668b0e11b21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
