<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__termsConditions</name>
   <tag></tag>
   <elementGuidId>22996eab-6607-4f0c-baba-eb15ab05266c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;termsConditions&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='termsConditions']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef2affa0-9064-4906-82cc-5f53208fd77c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>de132d28-117c-4ad0-8c46-c39164c1bbe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-auto</value>
      <webElementGuid>cdd90371-fadb-4518-bc8b-6d123915b222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>termsConditions</value>
      <webElementGuid>d83546fd-9b69-4c7e-8025-e11922c6c6a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;login&quot;]/div[@class=&quot;wrapper wrapper-login&quot;]/div[@class=&quot;container container-signup login-signup-container&quot;]/div[@class=&quot;login-form&quot;]/form[@class=&quot;d-flex flex-wrap&quot;]/div[@class=&quot;align-content-between flex-column form-sub m-0 row&quot;]/div[@class=&quot;d-flex&quot;]/input[@class=&quot;m-auto&quot;]</value>
      <webElementGuid>e3adb088-73d9-4929-929d-e4940b6a2f93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='termsConditions']</value>
      <webElementGuid>1895f63e-c041-4b46-b920-f9dad4ad9974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/form/div[7]/div/input</value>
      <webElementGuid>9cff14ea-db83-4963-be89-1acd2393f01d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>0d527345-b135-4758-9cca-bee4f7f97a73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'termsConditions']</value>
      <webElementGuid>d9f72747-2450-4553-80d0-403c1b6bffb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
