<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__selected-flag</name>
   <tag></tag>
   <elementGuidId>acea0cd8-00c3-4815-9d3a-fb96b7a987ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='step1']/div/div/div[2]/div/form/div[3]/div/div/div[2]/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5ad8e2cb-4950-44f6-843f-7e1ba3a23fe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selected-flag</value>
      <webElementGuid>ce6daa6f-5eb8-4fdd-b8db-3d1507b33257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>49a5a041-db23-470d-9404-51ae34bc3a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>United States: +1</value>
      <webElementGuid>19963260-5240-4938-b8a2-a09f90f44f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step1&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/form[@class=&quot;ng-invalid ng-invalid-required ng-valid-ng-intl-tel-input ng-dirty ng-valid-parse ng-valid-exists ng-invalid-pattern&quot;]/div[@class=&quot;row mot-country-code&quot;]/div[@class=&quot;col-lg-6&quot;]/div[@class=&quot;county-code-form&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;col-sm-7&quot;]/div[@class=&quot;intl-tel-input allow-dropdown&quot;]/div[@class=&quot;flag-container&quot;]/div[@class=&quot;selected-flag&quot;]</value>
      <webElementGuid>d925862f-5280-4d7d-9139-2ac876fb9a2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step1']/div/div/div[2]/div/form/div[3]/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>cd369163-8aef-47a7-afbd-0dd05b0480d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::div[5]</value>
      <webElementGuid>8a834bb3-2635-4e98-9588-b9132ed8e13f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Argentina'])[1]/preceding::div[5]</value>
      <webElementGuid>db6235b1-bf7a-4287-aedc-f7405621e12a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brazil (Brasil)'])[1]/preceding::div[7]</value>
      <webElementGuid>1c1af7b9-2b86-4465-a226-7230f73399e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>e84b2330-7185-4bea-8140-bc23a85856da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'United States: +1']</value>
      <webElementGuid>0f7e9fd2-f046-4468-8d49-31ba325e8f9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
