<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select-- Advertising, Arts, Entert_612296</name>
   <tag></tag>
   <elementGuidId>8d66dcbb-83a1-447f-9a31-d746834f5752</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='vm.accountDetailsForm.accountIndustryID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;vm.accountDetailsForm.accountIndustryID&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vm.accountDetailsForm.accountIndustryID</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>vm.accountDetailsForm.accountIndustryID</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-invalid ng-invalid-required</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>industry.id as industry.label for industry in vm.accountData.industries | orderBy:'label'</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select-- Advertising, Arts, Entertainment &amp; MediaAgriculture, Forestry, Fishing &amp; HuntingAutomotive, Aviation, Rail &amp; NauticalBiotechnology &amp; Medical ScienceBusiness, Finance, Insurance, Legal &amp; Real EstateEducation &amp; Social ServicesEnergy &amp; Environmental ServicesEnergy, Refinery &amp; UtilitiesGovernment &amp; Public AdministrationHospitality &amp; Consumer ServicesManagement of Companies and EnterprisesManufacturing &amp; ConstructionMilitary &amp; DefensePublic Administration &amp; Non-profitRetail &amp; Wholesale TradeTechnology, Electronics &amp; CommunicationsTransportation &amp; Warehousing</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step1&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;row&quot;]/form[@class=&quot;ng-invalid ng-invalid-required ng-dirty ng-valid-parse ng-valid-exists ng-invalid-pattern ng-valid-ng-intl-tel-input&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-6&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-7&quot;]/select[@class=&quot;form-control ng-pristine ng-untouched ng-invalid ng-invalid-required&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='vm.accountDetailsForm.accountIndustryID']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step1']/div/div/div[2]/div/form/div[5]/div/div/div/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Industry is required.'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GA Code'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'vm.accountDetailsForm.accountIndustryID' and (text() = '--Select-- Advertising, Arts, Entertainment &amp; MediaAgriculture, Forestry, Fishing &amp; HuntingAutomotive, Aviation, Rail &amp; NauticalBiotechnology &amp; Medical ScienceBusiness, Finance, Insurance, Legal &amp; Real EstateEducation &amp; Social ServicesEnergy &amp; Environmental ServicesEnergy, Refinery &amp; UtilitiesGovernment &amp; Public AdministrationHospitality &amp; Consumer ServicesManagement of Companies and EnterprisesManufacturing &amp; ConstructionMilitary &amp; DefensePublic Administration &amp; Non-profitRetail &amp; Wholesale TradeTechnology, Electronics &amp; CommunicationsTransportation &amp; Warehousing' or . = '--Select-- Advertising, Arts, Entertainment &amp; MediaAgriculture, Forestry, Fishing &amp; HuntingAutomotive, Aviation, Rail &amp; NauticalBiotechnology &amp; Medical ScienceBusiness, Finance, Insurance, Legal &amp; Real EstateEducation &amp; Social ServicesEnergy &amp; Environmental ServicesEnergy, Refinery &amp; UtilitiesGovernment &amp; Public AdministrationHospitality &amp; Consumer ServicesManagement of Companies and EnterprisesManufacturing &amp; ConstructionMilitary &amp; DefensePublic Administration &amp; Non-profitRetail &amp; Wholesale TradeTechnology, Electronics &amp; CommunicationsTransportation &amp; Warehousing')]</value>
   </webElementXpaths>
</WebElementEntity>
