<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>breadcrumbCandidatePoolPage</name>
   <tag></tag>
   <elementGuidId>121de2dc-33f2-4ad0-8b15-260a88e24770</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html//div[@id='contentMainDiv']/div[@id='wrapper']//ol[@class='breadcrumb']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>/html//div[@id='contentMainDiv']/div[@id='wrapper']//ol[@class='breadcrumb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
