<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>confirmSMSPopup</name>
   <tag></tag>
   <elementGuidId>dee4462f-eda8-4360-93ab-3bdcf1f6494b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[ng-click=&quot;answer('yes')&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
