<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_On-Boarding</name>
   <tag></tag>
   <elementGuidId>66718152-cfb4-40dc-a8d2-ccecc6c8ac81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='altra']/ul/li[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cbbd4112-ee2f-4da8-9842-439de5e20f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab-item</value>
      <webElementGuid>e0490a54-2434-4d2f-bf2e-9d57cc8e4960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>vm.getOnboardingDetails('ONBOARD_REFRESH', 1)</value>
      <webElementGuid>55a6eb5f-6025-45eb-b42d-dded18692519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>321edc28-d832-4a0b-9819-bb71615eaf17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#onboarding</value>
      <webElementGuid>0ed05fad-90b6-4c11-9323-4524d824ab16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tab</name>
      <type>Main</type>
      <value>ONBOARDING_TAB</value>
      <webElementGuid>5d75a550-aabd-481b-892d-0fe753bf6936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  On-Boarding </value>
      <webElementGuid>b20d19c7-498a-4dc4-a5cd-f0928e336e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;altra&quot;)/ul[@class=&quot;nav nav-tabs&quot;]/li[5]/a[@class=&quot;tab-item&quot;]</value>
      <webElementGuid>621c7d03-d080-40fc-baa3-45560cde2cb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='altra']/ul/li[5]/a</value>
      <webElementGuid>93f70e0c-9730-4bba-9db3-61bf9a50555a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Signing'])[1]/preceding::a[1]</value>
      <webElementGuid>52439cd1-51c6-4683-aec7-4e2eaf18de65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Document by Name or Label'])[1]/preceding::a[2]</value>
      <webElementGuid>abaaeec7-e39f-4f43-9fba-4b1a631bdc46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='On-Boarding']/parent::*</value>
      <webElementGuid>9eb8c3af-3431-4565-a650-0d3f03fcec4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#onboarding')]</value>
      <webElementGuid>37b61ee7-ae8d-41ec-91f6-1acd341a313d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li[5]/a</value>
      <webElementGuid>e2cfd9c2-739b-445c-9787-68eba53e9aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#onboarding' and (text() = '  On-Boarding ' or . = '  On-Boarding ')]</value>
      <webElementGuid>8c305341-748e-466b-a7dd-2b6c697fd3f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
