<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search Document by Name or Label_form_c5af69</name>
   <tag></tag>
   <elementGuidId>a38e70d6-74ab-4838-b114-da67bc3d2e09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='search'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.ui-select-search.ng-pristine.ng-untouched.ng-valid.ng-animate.ng-pristine-remove.ng-dirty-add.ng-valid-parse-add</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ddc286a-9fc2-4e40-a682-9ca0123c7287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>e616c5a6-006c-4fc5-a3a2-b96bdd855406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1368faff-a8e6-4e21-83e4-6f4f4ce8a8d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>69d874b8-4179-47f4-a0de-889a44c80a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6e86b0da-e78e-4ad6-af4b-51f2cfb1a869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select box</value>
      <webElementGuid>aece9bc0-3fc8-49ba-87cf-c0d9f652ed83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>ui-select-choices-2</value>
      <webElementGuid>5ab94e1f-2d29-4508-a779-9c26c4bd5922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ui-select-search ng-pristine ng-untouched ng-valid ng-animate ng-pristine-remove ng-dirty-add ng-valid-parse-add</value>
      <webElementGuid>518b985a-3525-4c6c-8219-eb0479fda505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{ 'ui-select-search-hidden' : !$select.searchEnabled }</value>
      <webElementGuid>b70076cc-8001-44e0-8aed-9d1de6e62ad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Document by Name or Label</value>
      <webElementGuid>fc70ab4e-08fe-494a-8878-6623b7901550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$select.search</value>
      <webElementGuid>85af1892-0540-4293-aa4d-a6c4a62abf93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>$select.open</value>
      <webElementGuid>e8bd0771-95fb-4841-9f71-9cfdee2dafb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapse1&quot;)/div[@class=&quot;panel-body&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;onboard-searchbar&quot;]/div[@class=&quot;ui-select-container ui-select-bootstrap dropdown ng-valid open&quot;]/input[@class=&quot;form-control ui-select-search ng-pristine ng-untouched ng-valid ng-animate ng-pristine-remove ng-dirty-add ng-valid-parse-add&quot;]</value>
      <webElementGuid>0691b08e-822b-4437-961c-0316545357f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='search'])[2]</value>
      <webElementGuid>8e1e45de-d9cf-4a46-a9a9-af74f9c228c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapse1']/div/div/div/div/input</value>
      <webElementGuid>2be98249-3c1d-4692-bdc3-6da5a37533e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>0bce1563-8467-480d-91fe-c7efc4b769c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @placeholder = 'Search Document by Name or Label']</value>
      <webElementGuid>c25ad1c5-8075-4345-a114-05f12d6b6aba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
