<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>94200c04-0980-4c22-9ad6-7f6191463739</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mCSB_2_container']/div/div/ul[4]/li/div/span[3]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>82ef8cc1-8005-4585-ad38-861254271df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images/failure.png</value>
      <webElementGuid>325af77a-e23c-486a-b1cc-45021ae788c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Failure</value>
      <webElementGuid>4cdcd6d6-4d0c-44ac-afb9-986bfef77b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mCSB_2_container&quot;)/div[@class=&quot;scroller&quot;]/div[@class=&quot;chat-history&quot;]/ul[@class=&quot;ng-scope&quot;]/li[@class=&quot;clearfix ng-scope&quot;]/div[@class=&quot;message-data text-right&quot;]/span[3]/img[1]</value>
      <webElementGuid>daf3d966-c0ae-4037-b986-d9b6afde42c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mCSB_2_container']/div/div/ul[4]/li/div/span[3]/img</value>
      <webElementGuid>b5d419dd-6cf1-4479-b71c-72a7d48879a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Failure'])[4]</value>
      <webElementGuid>3e8efe71-0b4b-40dd-8891-fef90aa4a4b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[4]/li/div/span[3]/img</value>
      <webElementGuid>34f17462-9c16-4814-81e0-87e01ec7813a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../images/failure.png' and @alt = 'Failure']</value>
      <webElementGuid>82fecb21-d6bf-4b01-9601-14ab2bcb31c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
