<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Logout</name>
   <tag></tag>
   <elementGuidId>d57c910a-2a97-436e-bda7-4b364c0ec443</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/div/div/div/nav/ul/li[6]/ul/li[2]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.border-bot-none > span.ng-scope</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>128bcf74-6d09-44e7-9b2d-96961b0598d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-translate</name>
      <type>Main</type>
      <value>label.user.logout</value>
      <webElementGuid>21519ae8-c6a6-482e-9c35-08a4833661ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-scope</value>
      <webElementGuid>af74a635-0cc1-4a34-a5ca-ce60bd0b4f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>07163fd1-6c43-4aa3-a4b2-3dde7c47565e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper-main&quot;)/div[@class=&quot;ng-scope&quot;]/div[@id=&quot;wrapper&quot;]/div[@class=&quot;header&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/nav[@class=&quot;navbar-default navbar-static-top&quot;]/ul[@class=&quot;nav navbar-top-links navbar-right&quot;]/li[@class=&quot;dropdown open&quot;]/ul[@class=&quot;dropdown-menu dropdown-user&quot;]/li[@class=&quot;ng-scope&quot;]/a[@class=&quot;border-bot-none&quot;]/span[@class=&quot;ng-scope&quot;]</value>
      <webElementGuid>431432ab-28ee-4b88-a793-ebdce30279cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div/div/div/nav/ul/li[6]/ul/li[2]/a/span</value>
      <webElementGuid>903f6a23-9ac8-45ec-a078-44e27f344233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Subscription(s)'])[1]/following::span[1]</value>
      <webElementGuid>4f8cedd7-5fc8-46ae-9468-66325b26f7b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Romit Romit'])[1]/following::span[1]</value>
      <webElementGuid>0d2488d7-eaa4-40bd-9a24-5410abee4e05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::span[1]</value>
      <webElementGuid>de780a0b-b87e-4d5b-9f87-22d8b787b871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable Interview Scheduling'])[1]/preceding::span[1]</value>
      <webElementGuid>dc827377-b11b-4e2b-b144-06662e7b3e18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>e8c4a162-05fe-43cf-b606-2e2a42e85c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/span</value>
      <webElementGuid>e3e21bb3-f2d9-4aeb-92e1-0ecc525edb35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>cf8ce74a-9ff4-4dd7-8ecd-6ec8903f4844</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
