<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Test Account_message-to-send</name>
   <tag></tag>
   <elementGuidId>bc93d39b-0177-49a4-85f4-5cfd474b3cac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='message-to-send']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#message-to-send</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>80d9e142-ac71-4588-9bcf-0430b9892e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>vm.smsBody</value>
      <webElementGuid>fbe68c6a-d2de-43b6-8f92-b11ecfc68fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>message-to-send</value>
      <webElementGuid>4e2f3e1a-d103-453e-8f13-e0cc160af1fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>message-to-send</value>
      <webElementGuid>2ab9144a-f59a-4668-8bf2-1dee6bf1c15a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type your message</value>
      <webElementGuid>3146e404-3e10-4920-9fdc-4b5ff586486e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>be632915-d2ea-41e0-aa9c-d41df7a22ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-animate ng-pristine-remove ng-dirty-add ng-valid-parse-add</value>
      <webElementGuid>020ae8e3-c775-4e71-926f-1b1e4fa4be36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;message-to-send&quot;)</value>
      <webElementGuid>2b74b0dc-251f-4fd6-acb0-ad58f32b1630</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='message-to-send']</value>
      <webElementGuid>0070a0d6-dd35-4d29-a0fc-f39b7103ba11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chats']/div/div[3]/div[2]/div/textarea</value>
      <webElementGuid>96d5553f-e922-4b40-80cb-640ac0e43a11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/textarea</value>
      <webElementGuid>cf8b3d37-54a6-4104-8a77-ac0bbf0314a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'message-to-send' and @id = 'message-to-send' and @placeholder = 'Type your message']</value>
      <webElementGuid>b8236c3a-7216-4a4f-b28c-d1f758976023</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
