<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Start Survey</name>
   <tag></tag>
   <elementGuidId>b744b427-0ddc-4860-8cda-c57aeef16681</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mail']/div/center/table/tbody/tr/td/table[2]/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[2]/td/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>df9d9b74-f9cb-4086-a949-973140478bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://testaccount.mobile-recruit.com/m/10Ifi5VVV?firstname=SurveyhBrLFg&amp;lastname=Candidate&amp;email=drizt@yopmail.com&amp;phonenumber=+911325001250</value>
      <webElementGuid>0c96e190-d232-4dd7-9742-8f6ced628330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Start Survey</value>
      <webElementGuid>0310bfb2-7a55-4402-98b4-afe8ad1f01cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mail&quot;)/div[1]/center[1]/table[1]/tbody[1]/tr[1]/td[1]/table[2]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[2]/td[1]/div[1]/a[1]</value>
      <webElementGuid>c056b13a-490c-4692-b8e7-3af65b9e9540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Yopmail/Page_Inbox/iframe_Undo_ifmail</value>
      <webElementGuid>e736764f-8965-4bf2-9518-645b55f2b4ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mail']/div/center/table/tbody/tr/td/table[2]/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[2]/td/div/a</value>
      <webElementGuid>d554d1ae-4b1d-4f4d-be68-2f4997507ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Start Survey')]</value>
      <webElementGuid>df049ff2-b47f-4451-9189-052c72554407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hi SurveyhBrLFg Candidate'])[1]/following::a[1]</value>
      <webElementGuid>fc02109b-7eed-44ce-8945-a190a9d42d33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::a[2]</value>
      <webElementGuid>2e132afc-524a-414a-b1c7-8287fab572c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='For Any Query Contact At'])[1]/preceding::a[1]</value>
      <webElementGuid>671e6a6a-4b0b-4626-bee9-743030512a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='support@mobile-talent.com'])[1]/preceding::a[1]</value>
      <webElementGuid>abb0c447-453f-43bd-a367-71cea6d59f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Start Survey']/parent::*</value>
      <webElementGuid>ae6bd1af-46b6-47fb-91f1-28e7635206ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://testaccount.mobile-recruit.com/m/10Ifi5VVV?firstname=SurveyhBrLFg&amp;lastname=Candidate&amp;email=drizt@yopmail.com&amp;phonenumber=+911325001250')]</value>
      <webElementGuid>639eab56-d1a7-4317-8e58-af04ac4332cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/a</value>
      <webElementGuid>3b573b92-755a-4f1f-980d-96b8f28f7c7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://testaccount.mobile-recruit.com/m/10Ifi5VVV?firstname=SurveyhBrLFg&amp;lastname=Candidate&amp;email=drizt@yopmail.com&amp;phonenumber=+911325001250' and (text() = ' Start Survey' or . = ' Start Survey')]</value>
      <webElementGuid>3dda4992-1841-4ae2-8c65-95b2c791b4fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
