<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Continue</name>
   <tag></tag>
   <elementGuidId>56f8a50b-149c-497c-9ad8-ff552ddb9b86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div[3]/div/div/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.carrot-flat-button.ng-scope > span.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d33ae2e0-0e9f-4d03-95a3-dc4eb5841867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-style</name>
      <type>Main</type>
      <value>{'color': vm.selectedPage.content.style.bodyStyle.buttonTextColor}</value>
      <webElementGuid>7a456df6-101d-4aa0-bf3b-fdae4a81ac14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>e84c2e64-df96-470a-b9bd-395ae5c928a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>d003103f-96e7-4720-a669-4b13261d8cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;microsite-min-height&quot;]/div[@class=&quot;grid_12 buttons&quot;]/div[1]/div[@class=&quot;ng-scope&quot;]/a[@class=&quot;carrot-flat-button ng-scope&quot;]/span[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>e01e563c-b02f-4fe9-aa9f-60b38ef5115a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[3]/div/div/a/span</value>
      <webElementGuid>cd0a58f4-f9bf-48cb-a5aa-a82c2ad507d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/following::span[1]</value>
      <webElementGuid>a57c7825-eeab-404d-a16a-2cfa28b8df34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bristol Center'])[1]/following::span[3]</value>
      <webElementGuid>1e19fb3e-88ad-4f1e-979f-5bc92976b8d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>e09578e5-a2d1-40a6-afda-3098b7559433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>ddf960a1-54e1-400b-bccb-f68cf6218e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>27808594-0b60-477f-8e2d-dcac430e20a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
