<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select-- Benefits Administrator Be_fd46d0</name>
   <tag></tag>
   <elementGuidId>c057e4f4-4b05-4969-a05b-77710581f3a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='campaignFunctionId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;campaignFunctionId&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>74f6ea0c-9041-4d53-abe6-3b4170152b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>isFunctionResponseReceived || $ctrl.campaign.familyId == undefined </value>
      <webElementGuid>51ff2f53-3d7c-4a81-b74e-bd43f88ebf0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>campaignFunctionId</value>
      <webElementGuid>595c3d4d-0739-4da3-9821-8993eb5e1394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$ctrl.campaign.functionID</value>
      <webElementGuid>b21083b7-0663-4460-b387-684c84181058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-invalid ng-invalid-required</value>
      <webElementGuid>6c3e7746-7031-4a2a-9270-efddb663cece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> --Select-- Benefits Administrator Benefits Manager Benefits Specialist Field Investigator Fraud Investigator Inspector Insurance Agent Insurance Sales Representative Investigator Lead Asset Protection Associate </value>
      <webElementGuid>515022f3-10ed-4de9-bfda-f9692100dc63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentMainDiv&quot;)/div[@class=&quot;container-main ptop10 ng-scope&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;fadeIn ng-scope&quot;]/form[@class=&quot;mnone ng-scope ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-ta-min-text ng-valid-min ng-dirty ng-valid-parse ng-valid-is-exists&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;wizard-area mobile-campaign-wizard&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;panel-body&quot;]/div[@class=&quot;col-md-10 col-lg-7 request-campaign&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-6&quot;]/select[@class=&quot;form-control ng-pristine ng-untouched ng-invalid ng-invalid-required&quot;]</value>
      <webElementGuid>75f47646-d825-4ae8-80cd-18b77fde06cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='campaignFunctionId']</value>
      <webElementGuid>ae822c1c-0a39-4e24-a9ef-cbe32f7242ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentMainDiv']/div[2]/div/div[4]/form/div/div/div[2]/div[3]/div/div/div/div[4]/div/select</value>
      <webElementGuid>e9e0c7c9-7776-4c81-b05e-a9e6cce4e970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::select[1]</value>
      <webElementGuid>f77c5364-3551-4d08-bfe4-f9e66ed8b7a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/preceding::select[1]</value>
      <webElementGuid>fc89bd18-0d3e-4dbe-8781-f786ccb8337d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/select</value>
      <webElementGuid>33d6179a-62dc-4d96-af9b-8d974a4c1a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'campaignFunctionId' and (text() = ' --Select-- Benefits Administrator Benefits Manager Benefits Specialist Field Investigator Fraud Investigator Inspector Insurance Agent Insurance Sales Representative Investigator Lead Asset Protection Associate ' or . = ' --Select-- Benefits Administrator Benefits Manager Benefits Specialist Field Investigator Fraud Investigator Inspector Insurance Agent Insurance Sales Representative Investigator Lead Asset Protection Associate ')]</value>
      <webElementGuid>1c834094-4763-4e26-a06f-b7dcc4d65398</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
